const KEY='nwceo_local_v3';
const SUPABASE_URL='https://vbkuvexyqehmpeeejqbh.supabase.co';
const SUPABASE_KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=v=>Number(v||0).toLocaleString('el-GR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
const empty={clients:[],programs:[],followups:[],orders:[],finance:[],tasks:[],reminders:[],success:[],documents:[],appointments:[],partners:[],measurements:[]};
let state={...empty}, currentView='dashboard', supa=null, cloud=false, userId=null;
try{state={...empty,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function setStatus(){const e=$('#cloudStatus');if(e){e.textContent=cloud?'☁️ Supabase συνδεδεμένο':'📱 Αποθηκεύεται στο κινητό';e.className='status '+(cloud?'online':'offline')}}
async function startCloud(){
  try{
    if(!window.supabase) throw new Error('Supabase library missing');
    supa=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
    const {data}=await supa.auth.getSession();
    if(data?.session?.user){userId=data.session.user.id;cloud=true;await loadCloud();return;}
    const r=await supa.auth.signInAnonymously();
    if(r?.data?.user){userId=r.data.user.id;cloud=true;await loadCloud();}
  }catch(e){cloud=false;console.warn('Cloud:',e?.message||e)}
  setStatus();
}
const cloudTables={clients:'clients',programs:'programs',followups:'follow_ups',orders:'orders',finance:'finance_transactions',tasks:'planner_tasks',reminders:'reminders',success:'daily_success',documents:'documents'};
function fromDb(table,x){
  if(table==='clients') return {...x,id:x.id,name:x.όνομα??x.name,phone:x.τηλέφωνο??x.phone,email:x.email,address:x.διεύθυνση??x.address,birth_date:x.birth_date,notes:x.σημειώσεις??x.notes,status:x.κατάσταση??x.status};
  if(table==='programs') return {...x,id:x.id,title:x.Τίτλος??x.τίτλος??x.title,calories:x.θερμίδες??x.calories,protein:x.Πρωτεΐνη??x.protein,description:x.Περιγραφή??x.περιγραφή??x.description,notes:x.Σημειώσεις??x.σημειώσεις??x.notes};
  return x;
}
function toDb(table,o){
  if(table==='programs') return {id:o.id,user_id:userId,client_id:o.client_id||null,Τίτλος:o.title||o.τίτλος||'',start_date:o.start_date||null,end_date:o.end_date||null,θερμίδες:o.calories===''?null:Number(o.calories||0),Πρωτεΐνη:o.protein===''?null:Number(o.protein||0),Περιγραφή:o.description||null,Σημειώσεις:o.notes||null,Κατάσταση:o.status||null};
  if(table==='clients') return {id:o.id,user_id:userId,όνομα:o.name||o.όνομα||'',τηλέφωνο:o.phone||o.τηλέφωνο||null,email:o.email||null,διεύθυνση:o.address||o.διεύθυνση||null,birth_date:o.birth_date||null,σημειώσεις:o.notes||o.σημειώσεις||null,κατάσταση:o.status||o.κατάσταση||null};
  return {...o,id:o.id,user_id:userId};
}
async function loadCloud(){
  if(!cloud)return;
  for(const [key,table] of Object.entries(cloudTables)){
    try{const {data,error}=await supa.from(table).select('*').eq('user_id',userId).order('created_at',{ascending:false});if(!error&&Array.isArray(data))state[key]=data.map(x=>fromDb(table,x));}catch(e){console.warn(table,e?.message||e)}
  }
  save();render(currentView);
}
async function insert(table,key,obj){
  const row={id:obj.id||uid(),...obj};state[key].unshift(row);save();render(currentView);
  if(!cloud)return;
  try{const {error}=await supa.from(table).insert(toDb(table,row));if(error)console.warn(table,error.message)}catch(e){console.warn(table,e)}
}
async function update(table,key,id,patch){
  state[key]=state[key].map(x=>x.id===id?{...x,...patch}:x);save();render(currentView);
  if(cloud)try{const {error}=await supa.from(table).update(toDb(table,{...patch,id})).eq('id',id).eq('user_id',userId);if(error)console.warn(table,error.message)}catch(e){console.warn(e)}
}
async function remove(table,key,id){
  state[key]=state[key].filter(x=>x.id!==id);save();render(currentView);
  if(cloud)try{await supa.from(table).delete().eq('id',id).eq('user_id',userId)}catch(e){console.warn(e)}
}
function nav(view){currentView=view;$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render(view)}
window.nav=nav;
function header(title,sub,action){return `<div class="row"><div><h1>${title}</h1><p>${sub}</p></div>${action?`<button class="primary" data-action="${action}">＋ Νέο</button>`:''}</div>`}
function dashboard(){const inc=state.finance.filter(x=>['income','έσοδο'].includes(String(x.transaction_type||'').toLowerCase())).reduce((a,x)=>a+Number(x.amount||0),0);const exp=state.finance.filter(x=>['expense','έξοδο'].includes(String(x.transaction_type||'').toLowerCase())).reduce((a,x)=>a+Number(x.amount||0),0);return `<section class="hero"><div><h1>Καλώς ήρθες, Nikoleta ✨</h1><p>Το προσωπικό σου <b>Wellness CEO</b>.</p></div><span id="cloudStatus" class="status">Σύνδεση…</span></section><div class="cards"><div class="card"><span>👥 Πελάτες</span><b>${state.clients.length}</b></div><div class="card"><span>📅 Ραντεβού σήμερα</span><b>${state.appointments.filter(x=>x.date===today()).length}</b></div><div class="card"><span>📞 Follow-ups</span><b>${state.followups.filter(x=>x.follow_up_date&&x.follow_up_date<=today()&&x.status!=='completed').length}</b></div><div class="card"><span>💰 Καθαρό</span><b>${money(inc-exp)}</b></div></div><div class="card"><h2>Γρήγορες ενέργειες</h2><div class="actions"><button class="primary" data-action="new-client">＋ Νέος πελάτης</button><button data-action="new-appointment">📅 Ραντεβού</button><button data-action="new-program">🥤 Πρόγραμμα</button><button data-action="new-task">📝 Εργασία</button><button data-action="new-reminder">🔔 Υπενθύμιση</button></div></div>`}
function clients(){return header('👥 Πελάτες','Πλήρης καρτέλα πελάτη.','new-client')+`<div class="list">${state.clients.length?state.clients.map(c=>`<article class="card item"><div><h3>${esc(c.name||c.όνομα||'Χωρίς όνομα')}</h3><p>📞 ${esc(c.phone||c.τηλέφωνο||'-')} · ✉️ ${esc(c.email||'-')}</p><p>${esc(c.notes||c.σημειώσεις||'')}</p></div><button class="danger" data-del="clients|${c.id}">Διαγραφή</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν πελάτες ακόμη.</div>`}</div>`}
function appointments(){return header('📅 Ραντεβού','Το ημερολόγιο των συναντήσεών σου.','new-appointment')+`<div class="list">${state.appointments.length?state.appointments.slice().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(a=>`<article class="card item"><div><h3>${esc(a.date)} · ${esc(a.time||'')}</h3><p><b>${esc(a.client||'-')}</b> · ${esc(a.type||'Ραντεβού')}</p><p>${esc(a.notes||'')}</p></div><button class="danger" data-del="appointments|${a.id}">Διαγραφή</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν ραντεβού.</div>`}</div>`}
function partners(){return header('🤝 Συνεργάτες','Συνεργασίες και επαφές.','new-partner')+`<div class="list">${state.partners.length?state.partners.map(p=>`<article class="card item"><div><h3>${esc(p.name)}</h3><p>${esc(p.type||'')} · 📞 ${esc(p.phone||'-')}</p><p>${esc(p.notes||'')}</p></div><button class="danger" data-del="partners|${p.id}">Διαγραφή</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν συνεργάτες.</div>`}</div>`}
function tanita(){return header('⚖️ Tanita','Ιστορικό μετρήσεων σώματος.','new-tanita')+`<div class="card tablewrap"><table><tr><th>Ημ/νία</th><th>Πελάτης</th><th>Βάρος</th><th>Λίπος</th><th>Μύες</th><th>Νερό</th><th>Σπλαχνικό</th></tr>${state.measurements.length?state.measurements.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(m=>`<tr><td>${esc(m.date)}</td><td>${esc(state.clients.find(c=>c.id===m.clientId)?.name||m.clientName||'-')}</td><td>${esc(m.weight||'-')}</td><td>${esc(m.fat||'-')}%</td><td>${esc(m.muscle||'-')}</td><td>${esc(m.water||'-')}%</td><td>${esc(m.visceral||'-')}</td></tr>`).join(''):`<tr><td colspan="7">Δεν υπάρχουν μετρήσεις.</td></tr>`}</table></div>`}
function programs(){return header('🥤 Προγράμματα','Θερμίδες, πρωτεΐνη, διάρκεια και σημειώσεις.','new-program')+`<div class="list">${state.programs.length?state.programs.map(p=>`<article class="card item"><div><h3>${esc(p.title||p.Τίτλος)}</h3><p>${esc(p.start_date||'')} → ${esc(p.end_date||'')} · ${esc(p.calories??p.θερμίδες??'-')} kcal · ${esc(p.protein??p.Πρωτεΐνη??'-')} g πρωτεΐνη</p><p>${esc(p.description||p.Περιγραφή||'')}</p><p>${esc(p.notes||p.Σημειώσεις||'')}</p></div><button class="danger" data-del="programs|${p.id}">Διαγραφή</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν προγράμματα.</div>`}</div>`}
function followups(){return header('📞 Follow-ups','Ποιον πρέπει να επικοινωνήσεις και πότε.')+`<div class="list">${state.followups.length?state.followups.map(f=>`<article class="card item"><div><h3>${esc(f.title)}</h3><p>${esc(f.follow_up_date||'')} ${esc(f.follow_up_time||'')} · ${f.status==='completed'?'✅ Ολοκληρώθηκε':'🔔 Εκκρεμεί'}</p><p>${esc(f.notes||'')}</p></div><button data-follow="${f.id}">${f.status==='completed'?'Αναίρεση':'Ολοκλήρωση'}</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν follow-ups.</div>`}</div>`}
function orders(){return header('📦 Παραγγελίες','Προϊόν, ποσότητα, τιμή και κατάσταση.','new-order')+`<div class="list">${state.orders.length?state.orders.map(o=>`<article class="card item"><div><h3>${esc(o.product_name)}</h3><p>${esc(o.order_date||'')} · ${esc(o.quantity||0)} × ${money(o.unit_price)} = <b>${money(o.total_amount)}</b></p><p>${esc(o.status||'')} · ${esc(o.notes||'')}</p></div><button class="danger" data-del="orders|${o.id}">Διαγραφή</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν παραγγελίες.</div>`}</div>`}
function finance(){const inc=state.finance.filter(x=>['income','έσοδο'].includes(String(x.transaction_type||'').toLowerCase())).reduce((a,x)=>a+Number(x.amount||0),0),exp=state.finance.filter(x=>['expense','έξοδο'].includes(String(x.transaction_type||'').toLowerCase())).reduce((a,x)=>a+Number(x.amount||0),0);return header('💰 Οικονομικά','Έσοδα, έξοδα και καθαρό αποτέλεσμα.')+`<div class="cards"><div class="card"><span>Έσοδα</span><b>${money(inc)}</b></div><div class="card"><span>Έξοδα</span><b>${money(exp)}</b></div><div class="card"><span>Καθαρό</span><b>${money(inc-exp)}</b></div></div><div class="actions"><button class="primary" data-action="income">＋ Έσοδο</button><button data-action="expense">＋ Έξοδο</button></div><div class="card"><h2>Κινήσεις</h2>${state.finance.length?state.finance.map(x=>`<p>📅 ${esc(x.transaction_date)} · <b>${esc(x.transaction_type)}</b> · ${money(x.amount)} · ${esc(x.category||'')} · ${esc(x.description||'')}</p>`).join(''):`<p class="empty">Καμία κίνηση.</p>`}</div>`}
function planner(){return header('📝 CEO Planner','Ημερήσιες εργασίες και προτεραιότητες.','new-task')+`<div class="list">${state.tasks.length?state.tasks.map(t=>`<article class="card item"><div><h3>${t.completed?'✅':'⬜'} ${esc(t.title)}</h3><p>${esc(t.task_date||'')} ${esc(t.start_time||'')} ${esc(t.end_time||'')} · ${esc(t.priority||'')}</p><p>${esc(t.description||'')}</p></div><button data-task="${t.id}">${t.completed?'Αναίρεση':'Ολοκληρώθηκε'}</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν εργασίες.</div>`}</div>`}
function reminders(){return header('🔔 Υπενθυμίσεις','Οι υπενθυμίσεις σου.','new-reminder')+`<div class="list">${state.reminders.length?state.reminders.map(r=>`<article class="card item"><div><h3>${r.completed?'✅':'🔔'} ${esc(r.title)}</h3><p>${esc(r.reminder_date)} · ${esc(r.reminder_time||'')}</p><p>${esc(r.notes||'')}</p></div><button data-reminder="${r.id}">${r.completed?'Αναίρεση':'Ολοκληρώθηκε'}</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν υπενθυμίσεις.</div>`}</div>`}
function success(){return header('🏆 Daily Success','Κατέγραψε τις νίκες της ημέρας.','new-success')+`<div class="list">${state.success.length?state.success.map(s=>`<article class="card item"><div><h3>${s.completed?'✅':'⬜'} ${esc(s.task)}</h3><p>${esc(s.success_date)}</p><p>${esc(s.notes||'')}</p></div><button data-success="${s.id}">${s.completed?'Αναίρεση':'Ολοκληρώθηκε'}</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν καταχωρίσεις.</div>`}</div>`}
function documents(){return header('📁 Έγγραφα','Η βιβλιοθήκη εγγράφων της εφαρμογής.')+`<div class="card"><p>Τα έγγραφα μπορούν να καταχωρούν τίτλο, όνομα αρχείου, τύπο και σύνδεση.</p></div><div class="list">${state.documents.length?state.documents.map(d=>`<article class="card item"><div><h3>📄 ${esc(d.title)}</h3><p>${esc(d.file_name||'')} · ${esc(d.file_type||'')}</p><p>${esc(d.file_path||'')}</p></div><button class="danger" data-del="documents|${d.id}">Διαγραφή</button></article>`).join(''):`<div class="card empty">Δεν υπάρχουν έγγραφα.</div>`}</div>`}
function clientOptions(){return state.clients.map(c=>({value:c.id,label:c.name||c.όνομα||'Πελάτης'}))}
function modal(title,fields,done){const box=document.createElement('div');box.className='modal';box.innerHTML=`<div class="modalbox"><h2>${title}</h2><form>${fields.map(f=>f.type==='select'?`<label>${f.label}<select name="${f.name}">${f.options.map(o=>`<option value="${esc(o.value)}">${esc(o.label)}</option>`).join('')}</select></label>`:`<label>${f.label}<input name="${f.name}" type="${f.type||'text'}" value="${esc(f.value||'')}" ${f.required?'required':''} ${f.step?`step="${f.step}"`:''}></label>`).join('')}<div class="actions"><button type="button" data-cancel>Άκυρο</button><button class="primary">Αποθήκευση</button></div></form></div>`;document.body.appendChild(box);box.querySelector('[data-cancel]').onclick=()=>box.remove();box.querySelector('form').onsubmit=e=>{e.preventDefault();done(Object.fromEntries(new FormData(e.target)));box.remove()}}
function action(a){
 if(a==='new-client')return modal('Νέος πελάτης',[{label:'Ονοματεπώνυμο',name:'name',required:true},{label:'Τηλέφωνο',name:'phone'},{label:'Email',name:'email'},{label:'Διεύθυνση',name:'address'},{label:'Ημερομηνία γέννησης',name:'birth_date',type:'date'},{label:'Σημειώσεις',name:'notes'}],v=>insert('clients','clients',v));
 if(a==='new-appointment')return modal('Νέο ραντεβού',[{label:'Πελάτης',name:'client'},{label:'Ημερομηνία',name:'date',type:'date',value:today(),required:true},{label:'Ώρα',name:'time',type:'time'},{label:'Τύπος',name:'type'},{label:'Σημειώσεις',name:'notes'}],v=>{state.appointments.unshift({id:uid(),...v});save();render(currentView)});
 if(a==='new-partner')return modal('Νέος συνεργάτης',[{label:'Όνομα',name:'name',required:true},{label:'Τύπος',name:'type'},{label:'Τηλέφωνο',name:'phone'},{label:'Σημειώσεις',name:'notes'}],v=>{state.partners.unshift({id:uid(),...v});save();render(currentView)});
 if(a==='new-tanita')return modal('Νέα μέτρηση Tanita',[{label:'Πελάτης',name:'clientId',type:'select',options:clientOptions()},{label:'Ημερομηνία',name:'date',type:'date',value:today(),required:true},{label:'Βάρος (kg)',name:'weight',type:'number',step:'0.1'},{label:'Λίπος (%)',name:'fat',type:'number',step:'0.1'},{label:'Μύες',name:'muscle',type:'number',step:'0.1'},{label:'Νερό (%)',name:'water',type:'number',step:'0.1'},{label:'Σπλαχνικό',name:'visceral',type:'number',step:'0.1'}],v=>{state.measurements.unshift({id:uid(),...v});save();render(currentView)});
 if(a==='new-program')return modal('Νέο πρόγραμμα',[{label:'Πελάτης',name:'client_id',type:'select',options:[{value:'',label:'Χωρίς πελάτη'},...clientOptions()]},{label:'Τίτλος',name:'title',required:true},{label:'Έναρξη',name:'start_date',type:'date'},{label:'Λήξη',name:'end_date',type:'date'},{label:'Θερμίδες',name:'calories',type:'number'},{label:'Πρωτεΐνη (g)',name:'protein',type:'number'},{label:'Περιγραφή',name:'description'},{label:'Σημειώσεις',name:'notes'},{label:'Κατάσταση',name:'status'}],v=>insert('programs','programs',v));
 if(a==='new-order')return modal('Νέα παραγγελία',[{label:'Πελάτης',name:'client_id',type:'select',options:[{value:'',label:'Χωρίς πελάτη'},...clientOptions()]},{label:'Ημερομηνία',name:'order_date',type:'date',value:today(),required:true},{label:'Προϊόν',name:'product_name',required:true},{label:'Ποσότητα',name:'quantity',type:'number',value:'1',required:true},{label:'Τιμή μονάδας (€)',name:'unit_price',type:'number',step:'0.01'},{label:'Σύνολο (€)',name:'total_amount',type:'number',step:'0.01'},{label:'Κατάσταση',name:'status'},{label:'Σημειώσεις',name:'notes'}],v=>{v.total_amount=v.total_amount||Number(v.quantity||0)*Number(v.unit_price||0);insert('orders','orders',v)});
 if(a==='income'||a==='expense')return modal(a==='income'?'Νέο έσοδο':'Νέο έξοδο',[{label:'Ποσό (€)',name:'amount',type:'number',step:'0.01',required:true},{label:'Ημερομηνία',name:'transaction_date',type:'date',value:today(),required:true},{label:'Κατηγορία',name:'category'},{label:'Περιγραφή',name:'description'}],v=>insert('finance_transactions','finance',{...v,transaction_type:a}));
 if(a==='new-task')return modal('Νέα εργασία',[{label:'Τίτλος',name:'title',required:true},{label:'Περιγραφή',name:'description'},{label:'Ημερομηνία',name:'task_date',type:'date',value:today(),required:true},{label:'Έναρξη',name:'start_time',type:'time'},{label:'Λήξη',name:'end_time',type:'time'},{label:'Προτεραιότητα',name:'priority'},{label:'Υπενθύμιση (λεπτά)',name:'reminder_minutes',type:'number',value:'0'}],v=>insert('planner_tasks','tasks',{...v,completed:false}));
 if(a==='new-reminder')return modal('Νέα υπενθύμιση',[{label:'Τίτλος',name:'title',required:true},{label:'Ημερομηνία',name:'reminder_date',type:'date',value:today(),required:true},{label:'Ώρα',name:'reminder_time',type:'time'},{label:'Υπενθύμιση (λεπτά)',name:'reminder_minutes',type:'number',value:'0'},{label:'Σημειώσεις',name:'notes'}],v=>insert('reminders','reminders',{...v,completed:false}));
 if(a==='new-success')return modal('Daily Success',[{label:'Ημερομηνία',name:'success_date',type:'date',value:today(),required:true},{label:'Εργασία / Νίκη',name:'task',required:true},{label:'Σημειώσεις',name:'notes'}],v=>insert('daily_success','success',{...v,completed:false}));
}
function render(view='dashboard'){currentView=view;const pages={dashboard,appointments,clients,partners,tanita,programs,followups,orders,finance,planner,reminders,success,documents};$('#app').innerHTML=(pages[view]||dashboard)();setStatus()}
document.addEventListener('click',e=>{const navBtn=e.target.closest('nav button[data-view]');if(navBtn){e.preventDefault();nav(navBtn.dataset.view);return}const act=e.target.closest('[data-action]');if(act){action(act.dataset.action);return}const del=e.target.closest('[data-del]');if(del){const [key,id]=del.dataset.del.split('|');const table=cloudTables[key]||key;if(confirm('Θέλεις διαγραφή;'))remove(table,key,id);return}const t=e.target.closest('[data-task]');if(t){const x=state.tasks.find(v=>v.id===t.dataset.task);if(x)update('planner_tasks','tasks',x.id,{completed:!x.completed});return}const r=e.target.closest('[data-reminder]');if(r){const x=state.reminders.find(v=>v.id===r.dataset.reminder);if(x)update('reminders','reminders',x.id,{completed:!x.completed});return}const s=e.target.closest('[data-success]');if(s){const x=state.success.find(v=>v.id===s.dataset.success);if(x)update('daily_success','success',x.id,{completed:!x.completed});return}const f=e.target.closest('[data-follow]');if(f){const x=state.followups.find(v=>v.id===f.dataset.follow);if(x)update('follow_ups','followups',x.id,{status:x.status==='completed'?'pending':'completed'});return}});
document.addEventListener('DOMContentLoaded',()=>{render('dashboard');startCloud();});
