const SUPABASE_URL='https://vbkuvexyqehmpeeejqbh.supabase.co';
const SUPABASE_KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY)||null;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>crypto.randomUUID(), today=()=>new Date().toISOString().slice(0,10);
const money=v=>Number(v||0).toLocaleString('el-GR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
const dateGR=v=>v?new Date(v+'T00:00:00').toLocaleDateString('el-GR',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
const time24=v=>v?String(v).slice(0,5):'—';
const stateKey='nwceo_final_v1';
const empty={clients:[],appointments:[],partners:[],measurements:[],programs:[],followups:[],orders:[],finance:[],tasks:[],reminders:[],success:[],documents:[]};
let state=JSON.parse(localStorage.getItem(stateKey)||'null')||structuredClone(empty);
let pending=JSON.parse(localStorage.getItem('nwceo_pending_final')||'[]');
let user=null,view='dashboard',online=navigator.onLine,syncing=false;
const tables={
clients:{table:'clients',fields:{name:'όνομα',phone:'τηλέφωνο',email:'email',address:'διεύθυνση',birth_date:'birth_date',notes:'σημειώσεις',status:'κατάσταση'}},
appointments:{table:'Ραντεβού',fields:{client_id:'client_id',title:'Τίτλος',date:'appointment_date',start_time:'start_time',end_time:'end_time',type:'appointment_type',status:'Κατάσταση',notes:'Σημειώσεις',reminder_minutes:'reminder_minutes'}},
partners:{table:'Συνεργάτες',fields:{name:'όνομα',phone:'τηλέφωνο',email:'email',business:'Επιχείρηση',notes:'Σημειώσεις',status:'Κατάσταση'}},
measurements:{table:'tanita_measurements',fields:{client_id:'client_id',date:'measurement_date',weight:'Βάρος',fat:'body_fat',muscle:'muscle_mass',water:'water_percent',bone:'bone_mass',visceral:'visceral_fat',calories:'θερμίδες',metabolic_age:'metabolic_age',fitness_score:'fitness_score',notes:'Σημειώσεις'}},
programs:{table:'Προγράμματα',fields:{client_id:'client_id',title:'Τίτλος',start_date:'start_date',end_date:'end_date',calories:'θερμίδες',protein:'Πρωτεΐνη',description:'Περιγραφή',notes:'Σημειώσεις',status:'Κατάσταση'}},
followups:{table:'follow_ups',fields:{client_id:'client_id',title:'Τίτλος',date:'follow_up_date',time:'follow_up_time',status:'Κατάσταση',notes:'Σημειώσεις',reminder_minutes:'reminder_minutes'}},
orders:{table:'Παραγγελίες',fields:{client_id:'client_id',date:'order_date',product:'product_name',quantity:'Ποσότητα',unit_price:'unit_price',total:'total_amount',status:'Κατάσταση',notes:'Σημειώσεις'}},
finance:{table:'finance_transactions',fields:{type:'transaction_type',amount:'Ποσό',date:'transaction_date',category:'Κατηγορία',description:'Περιγραφή',client_id:'client_id'}},
tasks:{table:'planner_tasks',fields:{title:'Τίτλος',description:'Περιγραφή',date:'task_date',start_time:'start_time',end_time:'end_time',completed:'ολοκληρώθηκε',reminder_minutes:'reminder_minutes',priority:'Προτεραιότητα'}},
reminders:{table:'Υπενθυμίσεις',fields:{title:'Τίτλος',date:'reminder_date',time:'reminder_time',reminder_minutes:'reminder_minutes',related_type:'related_type',related_id:'related_id',completed:'ολοκληρώθηκε',notes:'Σημειώσεις'}},
success:{table:'daily_success',fields:{date:'success_date',task:'Εργασία',completed:'ολοκληρώθηκε',notes:'Σημειώσεις'}},
documents:{table:'Έγγραφα',fields:{title:'Τίτλος',file_name:'file_name',file_path:'file_path',file_type:'file_type',file_size:'file_size',related_type:'related_type',related_id:'related_id'}}};
const numKeys=new Set(['amount','quantity','unit_price','total','weight','fat','muscle','water','bone','visceral','calories','protein','metabolic_age','fitness_score','file_size','reminder_minutes']);
const clientName=id=>state.clients.find(c=>c.id===id)?.name||'Χωρίς πελάτη';
function save(){localStorage.setItem(stateKey,JSON.stringify(state))}
function normalize(k,x){const o={...x,id:x.id||uid()};if(k==='appointments'){o.date=o.date||o.appointment_date||'';o.start_time=o.start_time||'';o.end_time=o.end_time||'';o.title=o.title||'Ραντεβού'}if(k==='clients')o.name=o.name||o.όνομα||'';return o}
Object.keys(state).forEach(k=>state[k]=(state[k]||[]).map(x=>normalize(k,x)));
function setSync(kind){const el=$('.sync-badge');if(!el)return;el.className='sync-badge '+kind;el.textContent=kind==='ok'?'☁️ Συγχρονισμένο':kind==='sync'?'↻ Συγχρονισμός…':kind==='offline'?'📴 Offline — αποθηκεύεται':'📱 Τοπικά στη συσκευή'}
function queue(op){pending.push(op);localStorage.setItem('nwceo_pending_final',JSON.stringify(pending))}
function row(k,o){const r={id:o.id,user_id:user?.id||null};for(const [key,dbk] of Object.entries(tables[k].fields)){let v=o[key];if(numKeys.has(key))v=v===''||v==null?null:Number(v);if(key==='completed')v=!!v;r[dbk]=v===''?null:v}return r}
async function sync(){if(!db||!user||!online||syncing)return;syncing=true;setSync('sync');try{for(const op of pending){if(op.type==='upsert'){const {error}=await db.from(tables[op.k].table).upsert(row(op.k,op.data),{onConflict:'id'});if(error)throw error}else{const {error}=await db.from(tables[op.k].table).delete().eq('id',op.id).eq('user_id',user.id);if(error)throw error}}pending=[];localStorage.setItem('nwceo_pending_final','[]');for(const k of Object.keys(tables)){const {data,error}=await db.from(tables[k].table).select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(!error&&data)state[k]=data.map(x=>normalize(k,x))}save();setSync('ok');render()}catch(e){console.warn(e);setSync('offline')}finally{syncing=false}}
function queueSync(){if(user&&online)sync()}
async function loadSession(){if(!db){render();return}try{const s=await db.auth.getSession();user=s.data.session?.user||null;if(user)await sync();else setSync('local')}catch(e){setSync('local')}db.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;setSync(user?(online?'ok':'offline'):'local');render()})}
window.addEventListener('online',()=>{online=true;sync()});window.addEventListener('offline',()=>{online=false;setSync('offline')});
function openAuth(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="auth"><div class="modal-card auth-card"><button class="x" data-close>×</button><div class="logo-mark">HL</div><div class="eyebrow">HEALTHY LIFE • WELLNESS CEO</div><h2>Σύνδεση</h2><p>Ο ίδιος λογαριασμός = ίδια δεδομένα σε όλες τις συσκευές.</p><label>Email<input id="ae" type="email" autocomplete="email"></label><label>Κωδικός<input id="ap" type="password" autocomplete="current-password"></label><div class="modal-actions"><button class="primary" data-auth="login">Σύνδεση</button><button data-auth="signup">Δημιουργία λογαριασμού</button></div><button class="link-button" data-auth="magic">✉️ Σύνδεση με σύνδεσμο email</button><div id="am" class="authmsg"></div></div></div>`)}
async function auth(mode){const email=$('#ae')?.value.trim(),password=$('#ap')?.value||'';if(!email){$('#am').textContent='Γράψε το email σου.';return}$('#am').textContent='Γίνεται σύνδεση…';let r;if(mode==='magic')r=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});else if(mode==='signup')r=await db.auth.signUp({email,password});else r=await db.auth.signInWithPassword({email,password});if(r.error){$('#am').textContent=r.error.message;return}if(mode==='magic'){$('#am').textContent='Έλεγξε το email σου και πάτησε τον σύνδεσμο.';return}if(!r.data.session){$('#am').textContent='Έλεγξε το email σου και μετά κάνε σύνδεση.';return}user=r.data.user;closeModal();await sync();render()}
function initials(n){return(n||'').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'N'}
function pageHead(title,sub,k){return `<div class="page-head"><div><div class="eyebrow">WELLNESS CEO</div><h1>${title}</h1><p>${sub}</p></div><button class="primary big" data-new="${k}">＋ Νέα εγγραφή</button></div>`}
function card(o,k){let n,meta;if(k==='clients'){n=o.name;meta=`${o.phone||'Χωρίς τηλέφωνο'} · ${o.status||'Ενεργός'}`}else if(k==='appointments'){n=clientName(o.client_id);meta=`${dateGR(o.date)} · ${time24(o.start_time)}${o.end_time?' – '+time24(o.end_time):''} · ${o.title||o.type||'Ραντεβού'}`}else if(k==='measurements'){n=clientName(o.client_id);meta=`${dateGR(o.date)} · ${o.weight||'—'} kg · ${o.fat||'—'}% λίπος · ${o.muscle||'—'} kg μυς`}else if(k==='finance'){n=o.description||o.category||'Κίνηση';meta=`${dateGR(o.date)} · ${money(o.amount)} · ${o.type||''}`}else if(k==='orders'){n=o.product||'Παραγγελία';meta=`${dateGR(o.date)} · ${o.quantity||0} × ${money(o.unit_price)}`}else{n=o.name||o.title||o.task||o.description||'Εγγραφή';meta=o.notes||o.status||''}return `<article class="data-card"><div class="avatar">${k==='clients'?esc(initials(n)):'✦'}</div><div class="card-main"><strong>${esc(n)}</strong><span>${esc(meta)}</span></div><div class="card-actions"><button class="icon-btn" data-edit="${k}" data-id="${o.id}">✎</button><button class="icon-btn danger" data-delete="${k}" data-id="${o.id}">⌫</button></div></article>`}
function list(k){const a=state[k]||[];return a.length?`<div class="data-list">${a.map(x=>card(x,k)).join('')}</div>`:`<div class="empty-state"><div>✦</div><strong>Δεν υπάρχουν εγγραφές ακόμη.</strong><span>Πάτησε «Νέα εγγραφή» για να ξεκινήσεις.</span></div>`}
function clientOptions(sel=''){return `<option value="">Επίλεξε πελάτη</option>`+state.clients.map(c=>`<option value="${esc(c.id)}" ${c.id===sel?'selected':''}>${esc(c.name)}</option>`).join('')}
const F=(l,n,t='text',v='',r='')=>`<label>${l}${r?' *':''}<input name="${n}" type="${t}" value="${esc(v)}" ${r}></label>`;
const S=(l,n,o)=>`<label>${l}<select name="${n}">${o}</select></label>`;
const T=(l,n,v='')=>`<label class="wide">${l}<textarea name="${n}">${esc(v)}</textarea></label>`;
function modal(k,id=''){const x=id?(state[k].find(a=>a.id===id)||{}):{};let h=`<div class="modal" id="editor"><form class="modal-card form-card" data-form="${k}" data-id="${id}"><button type="button" class="x" data-close>×</button><div class="form-head"><div class="logo-mark">HL</div><div><div class="eyebrow">HEALTHY LIFE</div><h2>${id?'Επεξεργασία':'Νέα εγγραφή'}</h2><p>${k==='appointments'?'Ραντεβού':k==='clients'?'Καρτέλα πελάτη':k}</p></div></div><div class="form-grid">`;
if(k==='clients')h+=F('Ονοματεπώνυμο','name','text',x.name,'required')+F('Τηλέφωνο','phone','tel',x.phone)+F('Email','email',x.email)+F('Ημερομηνία γέννησης','birth_date','date',x.birth_date)+F('Διεύθυνση','address',x.address)+S('Κατάσταση','status',`<option ${!x.status||x.status==='Ενεργός'?'selected':''}>Ενεργός</option><option ${x.status==='Follow-up'?'selected':''}>Follow-up</option><option ${x.status==='Ανενεργός'?'selected':''}>Ανενεργός</option>`)+T('Σημειώσεις','notes',x.notes);
if(k==='appointments')h+=S('Ονοματεπώνυμο πελάτη','client_id',clientOptions(x.client_id))+F('Τίτλος / λόγος','title','text',x.title||'Ραντεβού')+F('Ημερομηνία','date','date',x.date||today(),'required')+F('Ώρα έναρξης (24ωρο)','start_time','time',time24(x.start_time),'required')+F('Ώρα λήξης (24ωρο)','end_time','time',time24(x.end_time))+S('Τύπος','type',`<option ${!x.type||x.type==='Ραντεβού'?'selected':''}>Ραντεβού</option><option ${x.type==='Μέτρηση'?'selected':''}>Μέτρηση</option><option ${x.type==='Συμβουλευτική'?'selected':''}>Συμβουλευτική</option><option ${x.type==='Follow-up'?'selected':''}>Follow-up</option><option ${x.type==='Παρουσίαση'?'selected':''}>Παρουσίαση</option>`)+S('Κατάσταση','status',`<option ${!x.status||x.status==='Προγραμματισμένο'?'selected':''}>Προγραμματισμένο</option><option ${x.status==='Ολοκληρώθηκε'?'selected':''}>Ολοκληρώθηκε</option><option ${x.status==='Ακυρώθηκε'?'selected':''}>Ακυρώθηκε</option>`)+F('Υπενθύμιση (λεπτά πριν)','reminder_minutes','number',x.reminder_minutes||30)+T('Σημειώσεις','notes',x.notes);
if(k==='partners')h+=F('Ονοματεπώνυμο','name','text',x.name,'required')+F('Τηλέφωνο','phone','tel',x.phone)+F('Email','email',x.email)+F('Επιχείρηση','business',x.business)+S('Κατάσταση','status',`<option ${!x.status||x.status==='Ενεργός'?'selected':''}>Ενεργός</option><option>Ανενεργός</option>`)+T('Σημειώσεις','notes',x.notes);
if(k==='measurements')h+=S('Πελάτης','client_id',clientOptions(x.client_id))+F('Ημερομηνία','date','date',x.date||today(),'required')+F('Βάρος (kg)','weight','number',x.weight)+F('Σωματικό λίπος (%)','fat','number',x.fat)+F('Μυϊκή μάζα (kg)','muscle','number',x.muscle)+F('Νερό (%)','water','number',x.water)+F('Οστική μάζα','bone','number',x.bone)+F('Σπλαχνικό λίπος','visceral','number',x.visceral)+F('Θερμίδες','calories','number',x.calories)+F('Μεταβολική ηλικία','metabolic_age','number',x.metabolic_age)+F('Fitness Score','fitness_score','number',x.fitness_score)+T('Σημειώσεις','notes',x.notes);
if(k==='programs')h+=S('Πελάτης','client_id',clientOptions(x.client_id))+F('Τίτλος','title','text',x.title,'required')+F('Έναρξη','start_date','date',x.start_date||today())+F('Λήξη','end_date','date',x.end_date)+F('Θερμίδες','calories','number',x.calories)+F('Πρωτεΐνη (g)','protein','number',x.protein)+S('Κατάσταση','status',`<option ${!x.status||x.status==='Ενεργό'?'selected':''}>Ενεργό</option><option>Ολοκληρωμένο</option>`)+T('Περιγραφή','description',x.description)+T('Σημειώσεις','notes',x.notes);
if(k==='followups')h+=S('Πελάτης','client_id',clientOptions(x.client_id))+F('Τίτλος','title','text',x.title,'required')+F('Ημερομηνία','date','date',x.date||today())+F('Ώρα (24ωρο)','time','time',time24(x.time))+F('Υπενθύμιση (λεπτά)','reminder_minutes','number',x.reminder_minutes||30)+S('Κατάσταση','status',`<option ${!x.status||x.status==='Εκκρεμές'?'selected':''}>Εκκρεμές</option><option>Ολοκληρώθηκε</option>`)+T('Σημειώσεις','notes',x.notes);
if(k==='orders')h+=S('Πελάτης','client_id',clientOptions(x.client_id))+F('Ημερομηνία','date','date',x.date||today())+F('Προϊόν','product','text',x.product,'required')+F('Ποσότητα','quantity','number',x.quantity||1)+F('Τιμή μονάδας (€)','unit_price','number',x.unit_price)+F('Σύνολο (€)','total','number',x.total)+S('Κατάσταση','status',`<option ${!x.status||x.status==='Εκκρεμής'?'selected':''}>Εκκρεμής</option><option>Παραδόθηκε</option>`)+T('Σημειώσεις','notes',x.notes);
if(k==='finance')h+=S('Τύπος','type',`<option ${!x.type||x.type==='Έσοδο'?'selected':''}>Έσοδο</option><option>Έξοδο</option>`)+F('Ποσό (€)','amount','number',x.amount,'required')+F('Ημερομηνία','date','date',x.date||today())+F('Κατηγορία','category',x.category)+F('Περιγραφή','description',x.description)+S('Πελάτης','client_id',clientOptions(x.client_id));
if(k==='tasks')h+=F('Εργασία','title','text',x.title,'required')+F('Ημερομηνία','date','date',x.date||today())+F('Ώρα έναρξης (24ωρο)','start_time','time',time24(x.start_time))+F('Ώρα λήξης (24ωρο)','end_time','time',time24(x.end_time))+F('Υπενθύμιση (λεπτά)','reminder_minutes','number',x.reminder_minutes||30)+S('Προτεραιότητα','priority',`<option>Υψηλή</option><option selected>Κανονική</option><option>Χαμηλή</option>`)+T('Περιγραφή','description',x.description);
if(k==='reminders')h+=F('Τίτλος','title','text',x.title,'required')+F('Ημερομηνία','date','date',x.date||today())+F('Ώρα (24ωρο)','time','time',time24(x.time))+F('Υπενθύμιση (λεπτά)','reminder_minutes','number',x.reminder_minutes||30)+T('Σημειώσεις','notes',x.notes);
if(k==='success')h+=F('Εργασία','task','text',x.task,'required')+F('Ημερομηνία','date','date',x.date||today())+T('Σημειώσεις','notes',x.notes);
if(k==='documents')h+=F('Τίτλος','title','text',x.title,'required')+F('Όνομα αρχείου','file_name','text',x.file_name)+F('Τύπος αρχείου','file_type','text',x.file_type)+T('Σημειώσεις','notes',x.notes);
h+=`</div><div class="modal-actions"><button type="button" data-close>Ακύρωση</button><button class="primary" type="submit">💾 Αποθήκευση</button></div></form></div>`;return h}
function dashboard(){const a=state.appointments.filter(x=>x.date===today()).length;const net=state.finance.reduce((s,x)=>s+(x.type==='Έξοδο'?-Number(x.amount||0):Number(x.amount||0)),0);return `<section class="hero"><div><div class="eyebrow">HEALTHY LIFE • WELLNESS CEO</div><h1>Καλώς ήρθες, Nikoleta ✨</h1><p>Το προσωπικό σου Wellness CEO για πελάτες, ραντεβού, Tanita και καθημερινή οργάνωση.</p><div class="hero-actions"><button class="primary" data-new="clients">＋ Νέος πελάτης</button><button data-new="appointments">📅 Νέο ραντεβού</button><button data-new="tasks">📝 Νέα εργασία</button></div></div><div class="hero-logo"><div class="logo-ring">HEALTHY<br><b>LIFE</b><small>NUTRITION • BALANCE • WELLNESS</small></div></div></section><div class="stats"><div class="stat"><span>📅</span><b>${a}</b><small>Ραντεβού σήμερα</small></div><div class="stat"><span>👥</span><b>${state.clients.length}</b><small>Πελάτες</small></div><div class="stat"><span>⚖️</span><b>${state.measurements.length}</b><small>Μετρήσεις Tanita</small></div><div class="stat"><span>💰</span><b>${money(net)}</b><small>Καθαρό</small></div></div><div class="section-title"><div class="eyebrow">QUICK ACTIONS</div><h2>Γρήγορες ενέργειες</h2></div><div class="quick-grid"><button data-new="appointments">📅<span>Νέο ραντεβού</span></button><button data-new="clients">👥<span>Νέος πελάτης</span></button><button data-new="measurements">⚖️<span>Tanita</span></button><button data-new="finance">💰<span>Οικονομικά</span></button><button data-new="tasks">📝<span>Planner</span></button><button data-new="reminders">🔔<span>Υπενθύμιση</span></button></div></section>`}
const labels={appointments:['📅 Ραντεβού','Ημερολόγιο συναντήσεων'],clients:['👥 Πελάτες','Καρτέλες πελατών'],partners:['🤝 Συνεργάτες','Συνεργασίες'],measurements:['⚖️ Tanita','Μετρήσεις σώματος'],programs:['🥤 Προγράμματα','Προγράμματα ευεξίας'],followups:['📞 Follow-ups','Παρακολούθηση επαφών'],orders:['📦 Παραγγελίες','Προϊόντα και παραγγελίες'],finance:['💰 Οικονομικά','Έσοδα και έξοδα'],tasks:['📝 Planner','Η καθημερινή σου οργάνωση'],reminders:['🔔 Υπενθυμίσεις','Οι επόμενες υπενθυμίσεις'],success:['🏆 Daily Success','Οι καθημερινές σου νίκες'],documents:['📁 Έγγραφα','PDF και επαγγελματικά έγγραφα']};
function page(){if(view==='dashboard')return dashboard();const [t,s]=labels[view];const tools=view==='documents'?`<div class="doc-tools"><button class="primary" data-pdf="daily">📄 PDF ημερήσιας αναφοράς</button><button data-pdf="client">📄 PDF πρώτης καρτέλας πελάτη</button></div>`:'';return `<section class="page">${pageHead(t,s,view)}${tools}${list(view)}</section>`}
function render(){const app=$('#app');if(!app)return;$$('#nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));app.innerHTML=page()}
function openEditor(k,id=''){document.body.insertAdjacentHTML('beforeend',modal(k,id))}
function closeModal(){$$('.modal').forEach(x=>x.remove())}
function formData(f){const fd=new FormData(f),o={id:f.dataset.id||uid()};for(const [k,v] of fd.entries())o[k]=v;return o}
function printPDF(kind){let body;if(kind==='daily'){body=`<h1>Nikoleta Wellness CEO</h1><h2>Ημερήσια αναφορά — ${dateGR(today())}</h2><p>Πελάτες: ${state.clients.length}</p><p>Ραντεβού σήμερα: ${state.appointments.filter(x=>x.date===today()).length}</p><p>Follow-ups: ${state.followups.filter(x=>x.status!=='Ολοκληρώθηκε').length}</p>`}else{const c=state.clients[0];if(!c){alert('Πρόσθεσε πρώτα έναν πελάτη.');return}const ms=state.measurements.filter(x=>x.client_id===c.id);body=`<h1>Nikoleta Wellness CEO</h1><h2>Προσωπική αξιολόγηση</h2><h3>${esc(c.name)}</h3><p>Τηλέφωνο: ${esc(c.phone||'—')}</p><p>Email: ${esc(c.email||'—')}</p><h3>Μετρήσεις Tanita</h3>${ms.map(m=>`<p>${dateGR(m.date)} — ${m.weight||'—'} kg · ${m.fat||'—'}% λίπος · ${m.muscle||'—'} kg μυς</p>`).join('')||'<p>Δεν υπάρχουν μετρήσεις.</p>'}`}const w=window.open('','_blank');w.document.write(`<html><head><title>Nikoleta Wellness CEO</title><style>body{font-family:Arial;padding:42px;color:#19351d}h1{color:#245b2b}h2{color:#8b6d24}</style></head><body>${body}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
document.addEventListener('click',async e=>{const c=e.target.closest('[data-close]');if(c){closeModal();return}const v=e.target.closest('[data-view]');if(v){view=v.dataset.view;render();return}const n=e.target.closest('[data-new]');if(n){openEditor(n.dataset.new);return}const ed=e.target.closest('[data-edit]');if(ed){openEditor(ed.dataset.edit,ed.dataset.id);return}const del=e.target.closest('[data-delete]');if(del){if(!confirm('Να διαγραφεί αυτή η εγγραφή;'))return;state[del.dataset.delete]=state[del.dataset.delete].filter(x=>x.id!==del.dataset.id);save();queue({type:'delete',k:del.dataset.delete,id:del.dataset.id});queueSync();render();return}const ab=e.target.closest('[data-auth]');if(ab&&ab.dataset.auth!==''){await auth(ab.dataset.auth);return}const pdf=e.target.closest('[data-pdf]');if(pdf)printPDF(pdf.dataset.pdf);const acc=e.target.closest('.account-btn');if(acc)openAuth()});
document.addEventListener('submit',e=>{const f=e.target.closest('[data-form]');if(!f)return;e.preventDefault();const k=f.dataset.form,o=formData(f);if(k==='orders'&&(!o.total||Number(o.total)===0))o.total=Number(o.quantity||0)*Number(o.unit_price||0);const i=state[k].findIndex(x=>x.id===o.id);state[k][i>=0?i:state[k].length]=normalize(k,o);if(i<0)state[k].unshift(state[k].pop());save();queue({type:'upsert',k,data:state[k].find(x=>x.id===o.id)});localStorage.setItem('nwceo_pending_final',JSON.stringify(pending));closeModal();render();queueSync()});
loadSession();render();
