const KEY='nwceo_local_v4';
const SUPABASE_URL='https://vbkuvexyqehmpeeejqbh.supabase.co';
const SUPABASE_KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';

const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=v=>Number(v||0).toLocaleString('el-GR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
const fmtDate=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString('el-GR'):'-';

const EMPTY={clients:[],appointments:[],partners:[],measurements:[],programs:[],followups:[],orders:[],finance:[],tasks:[],reminders:[],success:[],documents:[]};
let state={...EMPTY}, currentView='dashboard', supa=null, cloud=false, userId=null;
let tableProfiles={};
try{
  const old=JSON.parse(localStorage.getItem(KEY)||'{}');
  const legacy1=JSON.parse(localStorage.getItem('nwceo_local_v3')||'{}');
  const legacy2=JSON.parse(localStorage.getItem('nikoletaWellnessCEOData')||'{}');
  const legacy3=JSON.parse(localStorage.getItem('nikoletaWellnessCEO')||'{}');
  state={...EMPTY,...legacy3,...legacy2,...legacy1,...old};
}catch{}

const CLOUD_TABLES={clients:'clients',programs:'programs',followups:'follow_ups',orders:'orders',finance:'finance_transactions',tasks:'planner_tasks',reminders:'reminders',success:'daily_success',documents:'documents'};
const CANDIDATE_TABLES={appointments:['appointments'],partners:['partners','collaborators'],measurements:['tanita_measurements','measurements','tanita']};

function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function normalizeState(){
  if((!Array.isArray(state.measurements)||state.measurements.length===0)&&Array.isArray(state.tanita)&&state.tanita.length) state.measurements=state.tanita;
  if((!Array.isArray(state.tasks)||state.tasks.length===0)&&Array.isArray(state.planner)&&state.planner.length) state.tasks=state.planner;
  if(!Array.isArray(state.success)) state.success=[];
  if(!Array.isArray(state.documents)) state.documents=[];
  state.appointments=(state.appointments||[]).map(normalizeAppointment);
  state.clients=(state.clients||[]).map(normalizeClient);
  state.partners=(state.partners||[]).map(normalizePartner);
  state.measurements=(state.measurements||[]).map(normalizeMeasurement);
  state.programs=(state.programs||[]).map(normalizeProgram);
  state.followups=(state.followups||[]).map(normalizeGeneric);
}
function setStatus(){const e=$('#cloudStatus');if(e){e.textContent=cloud?'☁️ Supabase συνδεδεμένο':'📱 Αποθηκεύεται στο κινητό';e.className='status '+(cloud?'online':'offline')}}
function normalizeClient(x){return {...x,id:x.id,name:x.όνομα??x.name??'',phone:x.τηλέφωνο??x.phone??'',email:x.email??'',address:x.διεύθυνση??x.address??'',birth_date:x.birth_date??'',notes:x.σημειώσεις??x.notes??'',status:x.κατάσταση??x.status??''}}
function normalizeProgram(x){return {...x,id:x.id,client_id:x.client_id??'',title:x.Τίτλος??x.τίτλος??x.title??'',start_date:x.start_date??'',end_date:x.end_date??'',calories:x.θερμίδες??x.calories??'',protein:x.Πρωτεΐνη??x.protein??'',description:x.Περιγραφή??x.περιγραφή??x.description??'',notes:x.Σημειώσεις??x.σημειώσεις??x.notes??'',status:x.Κατάσταση??x.κατάσταση??x.status??''}}
function normalizeGeneric(x){return {...x,id:x.id}}
function normalizeAppointment(x){return {...x,id:x.id,client_id:x.client_id??x.clientId??'',client:x.client??x.πελάτης??'',title:x.title??x.Τίτλος??'',date:x.date??x.appointment_date??'',time:x.time??x.appointment_time??'',type:x.type??x.τύπος??'',notes:x.notes??x.σημειώσεις??x.note??'',status:x.status??x.κατάσταση??'',reminder_minutes:x.reminder_minutes??0}}
function normalizePartner(x){return {...x,id:x.id,name:x.name??x.όνομα??'',type:x.type??x.τύπος??'',phone:x.phone??x.τηλέφωνο??'',email:x.email??'',notes:x.notes??x.σημειώσεις??''}}
function normalizeMeasurement(x){return {...x,id:x.id,client_id:x.client_id??x.clientId??'',date:x.date??x.measurement_date??'',weight:x.weight??'',fat:x.fat??x.body_fat??'',muscle:x.muscle??x.muscle_mass??'',water:x.water??'',visceral:x.visceral??x.visceral_fat??'',bone:x.bone??x.bone_mass??'',metabolic_age:x.metabolic_age??''}}
normalizeState();

function toDb(table,o){
  const id=o.id||uid();
  if(table==='clients') return {id,user_id:userId,όνομα:o.name??o.όνομα??'',τηλέφωνο:o.phone??o.τηλέφωνο??null,email:o.email??null,διεύθυνση:o.address??o.διεύθυνση??null,birth_date:o.birth_date||null,σημειώσεις:o.notes??o.σημειώσεις??null,κατάσταση:o.status??o.κατάσταση??null};
  if(table==='programs') return {id,user_id:userId,client_id:o.client_id||null,Τίτλος:o.title??o.Τίτλος??'',start_date:o.start_date||null,end_date:o.end_date||null,θερμίδες:o.calories===''?null:Number(o.calories||0),Πρωτεΐνη:o.protein===''?null:Number(o.protein||0),Περιγραφή:o.description||null,Σημειώσεις:o.notes||null,Κατάσταση:o.status||null};
  if(table==='follow_ups') return {id,user_id:userId,client_id:o.client_id||null,Τίτλος:o.title||'',follow_up_date:o.follow_up_date||null,follow_up_time:o.follow_up_time||null,Κατάσταση:o.status||null,Σημειώσεις:o.notes||null,reminder_minutes:Number(o.reminder_minutes||0)};
  if(table==='orders') return {id,user_id:userId,client_id:o.client_id||null,order_date:o.order_date||today(),product_name:o.product_name||'',Ποσότητα:Number(o.quantity||0),unit_price:o.unit_price===''?null:Number(o.unit_price||0),total_amount:o.total_amount===''?null:Number(o.total_amount||0),Κατάσταση:o.status||null,Σημειώσεις:o.notes||null};
  if(table==='finance_transactions') return {id,user_id:userId,transaction_type:o.transaction_type||'income',Ποσό:Number(o.amount||0),transaction_date:o.transaction_date||today(),Κατηγορία:o.category||null,Περιγραφή:o.description||null,client_id:o.client_id||null};
  if(table==='planner_tasks') return {id,user_id:userId,Τίτλος:o.title||'',Περιγραφή:o.description||null,task_date:o.task_date||today(),start_time:o.start_time||null,end_time:o.end_time||null,ολοκληρώθηκε:!!o.completed,reminder_minutes:Number(o.reminder_minutes||0),Προτεραιότητα:o.priority||null};
  if(table==='reminders') return {id,user_id:userId,Τίτλος:o.title||'',reminder_date:o.reminder_date||today(),reminder_time:o.reminder_time||null,reminder_minutes:Number(o.reminder_minutes||0),related_type:o.related_type||null,related_id:o.related_id||null,ολοκληρώθηκε:!!o.completed,Σημειώσεις:o.notes||null};
  if(table==='daily_success') return {id,user_id:userId,success_date:o.success_date||today(),Εργασία:o.task||'',ολοκληρώθηκε:!!o.completed,Σημειώσεις:o.notes||null};
  if(table==='documents') return {id,user_id:userId,Τίτλος:o.title||'',file_name:o.file_name||null,file_path:o.file_path||null,file_type:o.file_type||null,file_size:o.file_size?Number(o.file_size):null,related_type:o.related_type||null,related_id:o.related_id||null};
  return {...o,id,user_id:userId};
}

async function startCloud(){
  try{
    if(!window.supabase) throw new Error('Supabase library missing');
    supa=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
    const s=await supa.auth.getSession();
    if(s?.data?.session?.user){userId=s.data.session.user.id;cloud=true;await loadCloud();setStatus();return}
    const r=await supa.auth.signInAnonymously();
    if(r?.data?.user){userId=r.data.user.id;cloud=true;await loadCloud();setStatus();return}
    throw new Error('Δεν έγινε σύνδεση');
  }catch(e){cloud=false;console.warn('Supabase:',e?.message||e);setStatus()}
}
async function queryTable(table,key,normalizer){
  try{
    const {data,error}=await supa.from(table).select('*').eq('user_id',userId).order('created_at',{ascending:false});
    if(error) throw error;
    if(Array.isArray(data)){
      if(data.length||!state[key]?.length) state[key]=data.map(normalizer);
      tableProfiles[table]=data[0]?Object.keys(data[0]):[];
      return true;
    }
  }catch(e){console.warn(`Cloud ${table}:`,e?.message||e)}
  return false;
}
async function loadCloud(){
  if(!cloud)return;
  await queryTable('clients','clients',normalizeClient);
  await queryTable('programs','programs',normalizeProgram);
  await queryTable('follow_ups','followups',normalizeGeneric);
  await queryTable('orders','orders',normalizeGeneric);
  await queryTable('finance_transactions','finance',normalizeGeneric);
  await queryTable('planner_tasks','tasks',x=>({...x,id:x.id,completed:x.ολοκληρώθηκε??x.completed??false,title:x.Τίτλος??x.title??'',description:x.Περιγραφή??x.description??'',task_date:x.task_date??'',start_time:x.start_time??'',end_time:x.end_time??'',reminder_minutes:x.reminder_minutes??0,priority:x.Προτεραιότητα??x.priority??''}));
  await queryTable('reminders','reminders',x=>({...x,id:x.id,completed:x.ολοκληρώθηκε??x.completed??false,title:x.Τίτλος??x.title??'',reminder_date:x.reminder_date??'',reminder_time:x.reminder_time??'',reminder_minutes:x.reminder_minutes??0,notes:x.Σημειώσεις??x.notes??''}));
  await queryTable('daily_success','success',x=>({...x,id:x.id,completed:x.ολοκληρώθηκε??x.completed??false,success_date:x.success_date??'',task:x.Εργασία??x.task??'',notes:x.Σημειώσεις??x.notes??''}));
  await queryTable('documents','documents',normalizeGeneric);
  for(const [key,cands] of Object.entries(CANDIDATE_TABLES)) for(const t of cands) if(await queryTable(t,key,key==='appointments'?normalizeAppointment:key==='partners'?normalizePartner:normalizeMeasurement)) break;
  save();render(currentView);
}
async function cloudInsert(table,obj){if(!cloud)return;try{const {error}=await supa.from(table).insert(toDb(table,obj));if(error)console.warn(`Αποθήκευση ${table}:`,error.message)}catch(e){console.warn(e)}}
async function cloudUpdate(table,id,obj){if(!cloud)return;try{const row=toDb(table,{...obj,id});delete row.user_id;const {error}=await supa.from(table).update(row).eq('id',id).eq('user_id',userId);if(error)console.warn(`Ενημέρωση ${table}:`,error.message)}catch(e){console.warn(e)}}
async function cloudDelete(table,id){if(!cloud)return;try{await supa.from(table).delete().eq('id',id).eq('user_id',userId)}catch(e){console.warn(e)}}
async function insert(key,obj,table=CLOUD_TABLES[key]){const row={id:obj.id||uid(),...obj};state[key].unshift(row);save();render(currentView);if(table)await cloudInsert(table,row)}
async function update(key,id,patch,table=CLOUD_TABLES[key]){state[key]=state[key].map(x=>x.id===id?{...x,...patch}:x);save();render(currentView);if(table)await cloudUpdate(table,id,patch)}
async function remove(key,id,table=CLOUD_TABLES[key]){state[key]=state[key].filter(x=>x.id!==id);save();render(currentView);if(table)await cloudDelete(table,id)}

function header(title,sub,action){return `<div class="row"><div><h1>${title}</h1><p>${sub}</p></div>${action?`<button class="primary" data-action="${action}">＋ Νέο</button>`:''}</div>`}
function clientName(id,name){return name||state.clients.find(c=>c.id===id)?.name||'-'}
function clientOptions(){return [{value:'',label:'Χωρίς πελάτη'},...state.clients.map(c=>({value:c.id,label:c.name||'Πελάτης'}))]}
function editDelete(key,id){return `<div class="row-actions"><button class="small" data-edit="${key}|${id}">✏️ Επεξεργασία</button><button class="small danger" data-del="${key}|${id}">🗑️ Διαγραφή</button></div>`}

function dashboard(){const inc=state.finance.filter(x=>['income','έσοδο'].includes(String(x.transaction_type||'').toLowerCase())).reduce((a,x)=>a+Number(x.amount||x.Ποσό||0),0);const exp=state.finance.filter(x=>['expense','έξοδο'].includes(String(x.transaction_type||'').toLowerCase())).reduce((a,x)=>a+Number(x.amount||x.Ποσό||0),0);return `<section class="hero"><div><h1>Καλώς ήρθες, Nikoleta ✨</h1><p>Το προσωπικό σου <b>Wellness CEO</b>.</p></div><span id="cloudStatus" class="status">Σύνδεση…</span></section><div class="cards"><div class="card"><span>👥 Πελάτες</span><b>${state.clients.length}</b></div><div class="card"><span>📅 Ραντεβού σήμερα</span><b>${state.appointments.filter(x=>(x.date||x.appointment_date)===today()).length}</b></div><div class="card"><span>📞 Follow-ups</span><b>${state.followups.filter(x=>(x.follow_up_date||'')<=today()&&x.status!=='completed').length}</b></div><div class="card"><span>💰 Καθαρό</span><b>${money(inc-exp)}</b></div></div><div class="card"><h2>Γρήγορες ενέργειες</h2><div class="actions"><button class="primary" data-action="new-client">＋ Νέος πελάτης</button><button data-action="new-appointment">📅 Ραντεβού</button><button data-action="new-tanita">⚖️ Tanita</button><button data-action="new-program">🥤 Πρόγραμμα</button><button data-action="new-followup">📞 Follow-up</button><button data-action="new-task">📝 Εργασία</button><button data-action="new-reminder">🔔 Υπενθύμιση</button></div></div>`}
function appointments(){const items=[...state.appointments].sort((a,b)=>(`${a.date||''} ${a.time||''}`).localeCompare(`${b.date||''} ${b.time||''}`));return header('📅 Ραντεβού','Το ημερολόγιο των συναντήσεών σου.','new-appointment')+`<div class="list">${items.length?items.map(a=>`<article class="card item"><div><h3>${esc(fmtDate(a.date))} · ${esc(a.time||'')}</h3><p><b>${esc(clientName(a.client_id,a.client))}</b> · ${esc(a.title||a.type||'Ραντεβού')}</p><p>${esc(a.notes||'')}</p><p class="muted">${esc(a.status||'')}</p></div>${editDelete('appointments',a.id)}</article>`).join(''):`<div class="card empty">Δεν υπάρχουν ραντεβού.</div>`}</div>`}
function clients(){return header('👥 Πελάτες','Πλήρης καρτέλα πελάτη με ιστορικό.','new-client')+`<div class="list">${state.clients.length?state.clients.map(c=>`<article class="card item"><div><h3>${esc(c.name||c.όνομα)}</h3><p>📞 ${esc(c.phone||c.τηλέφωνο||'-')} · ✉️ ${esc(c.email||'-')}</p><p>${esc(c.notes||c.σημειώσεις||'')}</p></div><div class="row-actions"><button class="small primary" data-profile="${c.id}">📂 Καρτέλα</button><button class="small" data-edit="clients|${c.id}">✏️ Επεξεργασία</button><button class="small danger" data-del="clients|${c.id}">🗑️ Διαγραφή</button></div></article>`).join(''):`<div class="card empty">Δεν υπάρχουν πελάτες ακόμη.</div>`}</div>`}
function clientProfile(id){const c=state.clients.find(x=>x.id===id);if(!c)return clients();const ap=state.appointments.filter(x=>x.client_id===id||x.clientId===id);const pr=state.programs.filter(x=>x.client_id===id);const fu=state.followups.filter(x=>x.client_id===id);const or=state.orders.filter(x=>x.client_id===id);const tm=state.measurements.filter(x=>x.client_id===id||x.clientId===id);return `<div class="row"><div><h1>📂 Καρτέλα: ${esc(c.name)}</h1><p>Όλες οι πληροφορίες του πελάτη σε ένα σημείο.</p></div><button data-action="view:clients">← Πίσω</button></div><div class="cards"><div class="card"><b>${ap.length}</b><span>Ραντεβού</span></div><div class="card"><b>${tm.length}</b><span>Tanita</span></div><div class="card"><b>${pr.length}</b><span>Προγράμματα</span></div><div class="card"><b>${fu.length}</b><span>Follow-ups</span></div></div><div class="card"><h2>Στοιχεία</h2><p>📞 ${esc(c.phone||'-')} · ✉️ ${esc(c.email||'-')}</p><p>🏠 ${esc(c.address||'-')}</p><p>${esc(c.notes||'')}</p></div><div class="card"><h2>Ραντεβού</h2>${ap.length?ap.map(x=>`<p>📅 ${esc(fmtDate(x.date))} ${esc(x.time||'')} · ${esc(x.title||x.type||'')} · ${esc(x.notes||'')}</p>`).join(''):'<p>Δεν υπάρχουν.</p>'}</div><div class="card"><h2>Tanita</h2>${tm.length?tm.map(x=>`<p>⚖️ ${esc(fmtDate(x.date))} · ${esc(x.weight||'-')} kg · λίπος ${esc(x.fat||'-')}% · μύες ${esc(x.muscle||'-')}</p>`).join(''):'<p>Δεν υπάρχουν.</p>'}</div><div class="card"><h2>Προγράμματα</h2>${pr.length?pr.map(x=>`<p>🥤 <b>${esc(x.title||x.Τίτλος)}</b> · ${esc(x.calories||x.θερμίδες||'-')} kcal · ${esc(x.protein||x.Πρωτεΐνη||'-')} g</p>`).join(''):'<p>Δεν υπάρχουν.</p>'}</div><div class="card"><h2>Follow-ups</h2>${fu.length?fu.map(x=>`<p>📞 ${esc(x.follow_up_date||'')} · ${esc(x.title||x.Τίτλος||'')} · ${esc(x.notes||x.Σημειώσεις||'')}</p>`).join(''):'<p>Δεν υπάρχουν.</p>'}</div><div class="card"><h2>Παραγγελίες</h2>${or.length?or.map(x=>`<p>📦 ${esc(x.product_name)} · ${esc(x.quantity||x.Ποσότητα||0)} × ${money(x.unit_price)} = ${money(x.total_amount)}</p>`).join(''):'<p>Δεν υπάρχουν.</p>'}</div>`}
function partners(){return header('🤝 Συνεργάτες','Γυμναστήρια, κομμωτήρια, κέντρα ομορφιάς, φαρμακεία κ.ά.','new-partner')+`<div class="list">${state.partners.length?state.partners.map(p=>`<article class="card item"><div><h3>${esc(p.name)}</h3><p>${esc(p.type||'')} · 📞 ${esc(p.phone||'-')} · ✉️ ${esc(p.email||'-')}</p><p>${esc(p.notes||'')}</p></div>${editDelete('partners',p.id)}</article>`).join(''):`<div class="card empty">Δεν υπάρχουν συνεργάτες.</div>`}</div>`}
function tanita(){return header('⚖️ Tanita','Ιστορικό μετρήσεων σώματος.','new-tanita')+`<div class="card tablewrap"><table><tr><th>Ημ/νία</th><th>Πελάτης</th><th>Βάρος</th><th>Λίπος</th><th>Μύες</th><th>Νερό</th><th>Σπλαχνικό</th><th></th></tr>${state.measurements.length?state.measurements.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(m=>`<tr><td>${esc(fmtDate(m.date))}</td><td>${esc(clientName(m.client_id,m.clientName))}</td><td>${esc(m.weight||'-')} kg</td><td>${esc(m.fat||'-')}%</td><td>${esc(m.muscle||'-')}</td><td>${esc(m.water||'-')}%</td><td>${esc(m.visceral||'-')}</td><td>${editDelete('measurements',m.id)}</td></tr>`).join(''):`<tr><td colspan="8">Δεν υπάρχουν μετρήσεις.</td></tr>`}</table></div>`}
function programs(){return header('🥤 Προγράμματα','Θερμίδες, πρωτεΐνη, διάρκεια, περιγραφή και σημειώσεις.','new-program')+`<div class="list">${state.programs.length?state.programs.map(p=>`<article class="card item"><div><h3>${esc(p.title||p.Τίτλος)}</h3><p>${esc(fmtDate(p.start_date))} → ${esc(fmtDate(p.end_date))} · ${esc(p.calories||p.θερμίδες||'-')} kcal · ${esc(p.protein||p.Πρωτεΐνη||'-')} g</p><p>👤 ${esc(clientName(p.client_id))}</p><p>${esc(p.description||p.Περιγραφή||'')}</p><p>${esc(p.notes||p.Σημειώσεις||'')}</p></div>${editDelete('programs',p.id)}</article>`).join(''):`<div class="card empty">Δεν υπάρχουν προγράμματα.</div>`}</div>`}
function followups(){return header('📞 Follow-ups','Ποιον πρέπει να επικοινωνήσεις και πότε.','new-followup')+`<div class="list">${state.followups.length?state.followups.map(f=>`<article class="card item"><div><h3>${esc(f.title||f.Τίτλος)}</h3><p>👤 ${esc(clientName(f.client_id))} · ${esc(fmtDate(f.follow_up_date))} ${esc(f.follow_up_time||'')}</p><p>${f.status==='completed'?'✅ Ολοκληρώθηκε':'🔔 Εκκρεμεί'} · ${esc(f.notes||f.Σημειώσεις||'')}</p></div><div class="row-actions"><button class="small" data-follow="${f.id}">${f.status==='completed'?'↩️ Αναίρεση':'✅ Ολοκλήρωση'}</button><button class="small" data-edit="followups|${f.id}">✏️ Επεξεργασία</button><button class="small danger" data-del="followups|${f.id}">🗑️ Διαγραφή</button></div></article>`).join(''):`<div class="card empty">Δεν υπάρχουν follow-ups.</div>`}</div>`}
function orders(){return header('📦 Παραγγελίες','Προϊόν, ποσότητα, τιμή και κατάσταση.','new-order')+`<div class="list">${state.orders.length?state.orders.map(o=>`<article class="card item"><div><h3>${esc(o.product_name)}</h3><p>👤 ${esc(clientName(o.client_id))} · ${esc(fmtDate(o.order_date))}</p><p>${esc(o.quantity||o.Ποσότητα||0)} × ${money(o.unit_price)} = <b>${money(o.total_amount)}</b></p><p>${esc(o.status||o.Κατάσταση||'')} · ${esc(o.notes||o.Σημειώσεις||'')}</p></div>${editDelete('orders',o.id)}</article>`).join(''):`<div class="card empty">Δεν υπάρχουν παραγγελίες.</div>`}</div>`}
function finance(){const inc=state.finance.filter(x=>['income','έσοδο'].includes(String(x.transaction_type||'').toLowerCase())).reduce((a,x)=>a+Number(x.amount||x.Ποσό||0),0),exp=state.finance.filter(x=>['expense','έξοδο'].includes(String(x.transaction_type||'').toLowerCase())).reduce((a,x)=>a+Number(x.amount||x.Ποσό||0),0);return header('💰 Οικονομικά','Έσοδα, έξοδα και καθαρό αποτέλεσμα.')+`<div class="cards"><div class="card"><span>Έσοδα</span><b>${money(inc)}</b></div><div class="card"><span>Έξοδα</span><b>${money(exp)}</b></div><div class="card"><span>Καθαρό</span><b>${money(inc-exp)}</b></div></div><div class="actions"><button class="primary" data-action="income">＋ Έσοδο</button><button data-action="expense">＋ Έξοδο</button></div><div class="list">${state.finance.length?state.finance.map(x=>`<article class="card item"><div><h3>${esc(x.transaction_type||'')}</h3><p>${esc(fmtDate(x.transaction_date))} · <b>${money(x.amount||x.Ποσό)}</b> · ${esc(x.category||x.Κατηγορία||'')}</p><p>${esc(x.description||x.Περιγραφή||'')}</p></div>${editDelete('finance',x.id)}</article>`).join(''):`<div class="card empty">Καμία κίνηση.</div>`}</div>`}
function planner(){return header('📝 Planner','Ημερήσιες εργασίες και προτεραιότητες.','new-task')+`<div class="list">${state.tasks.length?state.tasks.map(t=>`<article class="card item"><div><h3>${t.completed?'✅':'⬜'} ${esc(t.title||t.Τίτλος)}</h3><p>${esc(fmtDate(t.task_date))} ${esc(t.start_time||'')} ${esc(t.end_time||'')} · ${esc(t.priority||t.Προτεραιότητα||'')}</p><p>${esc(t.description||t.Περιγραφή||'')}</p></div><div class="row-actions"><button class="small" data-task="${t.id}">${t.completed?'↩️ Αναίρεση':'✅ Ολοκληρώθηκε'}</button><button class="small" data-edit="tasks|${t.id}">✏️ Επεξεργασία</button><button class="small danger" data-del="tasks|${t.id}">🗑️ Διαγραφή</button></div></article>`).join(''):`<div class="card empty">Δεν υπάρχουν εργασίες.</div>`}</div>`}
function reminders(){return header('🔔 Υπενθυμίσεις','Οι υπενθυμίσεις σου.','new-reminder')+`<div class="list">${state.reminders.length?state.reminders.map(r=>`<article class="card item"><div><h3>${r.completed?'✅':'🔔'} ${esc(r.title||r.Τίτλος)}</h3><p>${esc(fmtDate(r.reminder_date))} · ${esc(r.reminder_time||'')}</p><p>${esc(r.notes||r.Σημειώσεις||'')}</p></div><div class="row-actions"><button class="small" data-reminder="${r.id}">${r.completed?'↩️ Αναίρεση':'✅ Ολοκληρώθηκε'}</button><button class="small" data-edit="reminders|${r.id}">✏️ Επεξεργασία</button><button class="small danger" data-del="reminders|${r.id}">🗑️ Διαγραφή</button></div></article>`).join(''):`<div class="card empty">Δεν υπάρχουν υπενθυμίσεις.</div>`}</div>`}
function success(){return header('🏆 Daily Success','Κατέγραψε τις νίκες της ημέρας.','new-success')+`<div class="list">${state.success.length?state.success.map(s=>`<article class="card item"><div><h3>${s.completed?'✅':'⬜'} ${esc(s.task||s.Εργασία)}</h3><p>${esc(fmtDate(s.success_date))}</p><p>${esc(s.notes||s.Σημειώσεις||'')}</p></div><div class="row-actions"><button class="small" data-success="${s.id}">${s.completed?'↩️ Αναίρεση':'✅ Ολοκληρώθηκε'}</button><button class="small" data-edit="success|${s.id}">✏️ Επεξεργασία</button><button class="small danger" data-del="success|${s.id}">🗑️ Διαγραφή</button></div></article>`).join(''):`<div class="card empty">Δεν υπάρχουν καταχωρίσεις.</div>`}</div>`}
function documents(){return header('📁 Έγγραφα','Τίτλος, αρχείο, τύπος και σύνδεση.','new-document')+`<div class="list">${state.documents.length?state.documents.map(d=>`<article class="card item"><div><h3>📄 ${esc(d.title||d.Τίτλος)}</h3><p>${esc(d.file_name||'')} · ${esc(d.file_type||'')}</p><p>${esc(d.file_path||'')}</p></div>${editDelete('documents',d.id)}</article>`).join(''):`<div class="card empty">Δεν υπάρχουν έγγραφα.</div>`}</div>`}

function modal(title,fields,done){const box=document.createElement('div');box.className='modal';box.innerHTML=`<div class="modalbox"><h2>${title}</h2><form>${fields.map(f=>{const val=f.value??'';if(f.type==='textarea')return `<label>${f.label}<textarea name="${f.name}" ${f.required?'required':''}>${esc(val)}</textarea></label>`;if(f.type==='select')return `<label>${f.label}<select name="${f.name}">${f.options.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(val)?'selected':''}>${esc(o.label)}</option>`).join('')}</select></label>`;return `<label>${f.label}<input name="${f.name}" type="${f.type||'text'}" value="${esc(val)}" ${f.required?'required':''} ${f.step?`step="${f.step}"`:''}></label>`}).join('')}<div class="actions"><button type="button" data-cancel>Άκυρο</button><button class="primary">Αποθήκευση</button></div></form></div>`;document.body.appendChild(box);box.querySelector('[data-cancel]').onclick=()=>box.remove();box.querySelector('form').onsubmit=e=>{e.preventDefault();done(Object.fromEntries(new FormData(e.target)));box.remove()}}
function fieldsFor(key){
 if(key==='clients')return [['name','Ονοματεπώνυμο','text',true],['phone','Τηλέφωνο','text'],['email','Email','email'],['address','Διεύθυνση','text'],['birth_date','Ημερομηνία γέννησης','date'],['status','Κατάσταση','text'],['notes','Σημειώσεις','textarea']];
 if(key==='appointments')return [['client_id','Πελάτης','select',false,clientOptions()],['date','Ημερομηνία','date',true],['time','Ώρα','time'],['title','Τίτλος / Τύπος','text'],['status','Κατάσταση','text'],['reminder_minutes','Υπενθύμιση (λεπτά)','number'],['notes','Σημειώσεις','textarea']];
 if(key==='partners')return [['name','Όνομα / Επιχείρηση','text',true],['type','Τύπος συνεργάτη','text'],['phone','Τηλέφωνο','text'],['email','Email','email'],['notes','Σημειώσεις','textarea']];
 if(key==='measurements')return [['client_id','Πελάτης','select',false,clientOptions()],['date','Ημερομηνία','date',true],['weight','Βάρος (kg)','number'],['fat','Λίπος (%)','number'],['muscle','Μυϊκή μάζα','number'],['water','Νερό (%)','number'],['visceral','Σπλαχνικό λίπος','number'],['bone','Οστική μάζα','number'],['metabolic_age','Μεταβολική ηλικία','number']];
 if(key==='programs')return [['client_id','Πελάτης','select',false,clientOptions()],['title','Τίτλος','text',true],['start_date','Έναρξη','date'],['end_date','Λήξη','date'],['calories','Θερμίδες','number'],['protein','Πρωτεΐνη (g)','number'],['description','Περιγραφή','textarea'],['notes','Σημειώσεις','textarea'],['status','Κατάσταση','text']];
 if(key==='followups')return [['client_id','Πελάτης','select',false,clientOptions()],['title','Τίτλος','text',true],['follow_up_date','Ημερομηνία','date',true],['follow_up_time','Ώρα','time'],['status','Κατάσταση','text'],['reminder_minutes','Υπενθύμιση (λεπτά)','number'],['notes','Σημειώσεις','textarea']];
 if(key==='orders')return [['client_id','Πελάτης','select',false,clientOptions()],['order_date','Ημερομηνία','date',true],['product_name','Προϊόν','text',true],['quantity','Ποσότητα','number',true],['unit_price','Τιμή μονάδας (€)','number'],['total_amount','Σύνολο (€)','number'],['status','Κατάσταση','text'],['notes','Σημειώσεις','textarea']];
 if(key==='finance')return [['transaction_type','Τύπος','select',true,[{value:'income',label:'Έσοδο'},{value:'expense',label:'Έξοδο'}]],['amount','Ποσό (€)','number',true],['transaction_date','Ημερομηνία','date',true],['category','Κατηγορία','text'],['description','Περιγραφή','text']];
 if(key==='tasks')return [['title','Εργασία','text',true],['description','Περιγραφή','textarea'],['task_date','Ημερομηνία','date',true],['start_time','Έναρξη','time'],['end_time','Λήξη','time'],['priority','Προτεραιότητα','text'],['reminder_minutes','Υπενθύμιση (λεπτά)','number']];
 if(key==='reminders')return [['title','Τίτλος','text',true],['reminder_date','Ημερομηνία','date',true],['reminder_time','Ώρα','time'],['reminder_minutes','Υπενθύμιση (λεπτά)','number'],['notes','Σημειώσεις','textarea']];
 if(key==='success')return [['success_date','Ημερομηνία','date',true],['task','Εργασία / Νίκη','text',true],['notes','Σημειώσεις','textarea']];
 if(key==='documents')return [['title','Τίτλος','text',true],['file_name','Όνομα αρχείου','text'],['file_path','Σύνδεσμος / Διαδρομή','text'],['file_type','Τύπος αρχείου','text'],['file_size','Μέγεθος','number']];
 return [];
}
function getVal(existing,key){if(key==='name')return existing.name??existing.όνομα??'';if(key==='phone')return existing.phone??existing.τηλέφωνο??'';if(key==='email')return existing.email??'';if(key==='address')return existing.address??existing.διεύθυνση??'';if(key==='notes')return existing.notes??existing.Σημειώσεις??'';if(key==='title')return existing.title??existing.Τίτλος??'';if(key==='status')return existing.status??existing.Κατάσταση??'';if(key==='description')return existing.description??existing.Περιγραφή??'';if(key==='calories')return existing.calories??existing.θερμίδες??'';if(key==='protein')return existing.protein??existing.Πρωτεΐνη??'';if(key==='quantity')return existing.quantity??existing.Ποσότητα??'';if(key==='unit_price')return existing.unit_price??'';if(key==='total_amount')return existing.total_amount??'';if(key==='transaction_type')return existing.transaction_type??'income';if(key==='amount')return existing.amount??existing.Ποσό??'';if(key==='transaction_date')return existing.transaction_date??'';if(key==='task')return existing.task??existing.Εργασία??'';return existing[key]??''}
function openEditor(key,id){const existing=state[key].find(x=>x.id===id);if(!existing)return;const defs=fieldsFor(key);modal(key==='clients'?'Επεξεργασία πελάτη':key==='appointments'?'Επεξεργασία ραντεβού':key==='partners'?'Επεξεργασία συνεργάτη':key==='measurements'?'Επεξεργασία Tanita':`Επεξεργασία ${key}`,defs.map(d=>({name:d[0],label:d[1],type:d[2],required:d[3],options:d[4],value:getVal(existing,d[0])})),v=>saveEdit(key,id,v))}
async function saveEdit(key,id,v){if(key==='orders'&&!v.total_amount)v.total_amount=Number(v.quantity||0)*Number(v.unit_price||0);await update(key,id,v,CLOUD_TABLES[key])}
function openNew(key){const defs=fieldsFor(key);modal(key==='clients'?'Νέος πελάτης':key==='appointments'?'Νέο ραντεβού':key==='partners'?'Νέος συνεργάτης':key==='measurements'?'Νέα μέτρηση Tanita':`Νέο ${key}`,defs.map(d=>({name:d[0],label:d[1],type:d[2],required:d[3],options:d[4],value:d[0]==='date'||d[0].endsWith('_date')?today():d[0]==='quantity'?'1':d[0]==='reminder_minutes'?'0':''})),async v=>{if(key==='orders'&&!v.total_amount)v.total_amount=Number(v.quantity||0)*Number(v.unit_price||0);await insert(key,v,CLOUD_TABLES[key])})}
function render(view='dashboard'){currentView=view;const pages={dashboard,appointments,clients,partners,tanita,programs,followups,orders,finance,planner,reminders,success,documents};$('#app').innerHTML=(pages[view]||dashboard)();setStatus()}
function action(a){if(a.startsWith('view:')){nav(a.slice(5));return}if(a==='new-client')return openNew('clients');if(a==='new-appointment')return openNew('appointments');if(a==='new-partner')return openNew('partners');if(a==='new-tanita')return openNew('measurements');if(a==='new-program')return openNew('programs');if(a==='new-followup')return openNew('followups');if(a==='new-order')return openNew('orders');if(a==='income'||a==='expense'){const defs=fieldsFor('finance');return modal(a==='income'?'Νέο έσοδο':'Νέο έξοδο',defs.map(d=>({name:d[0],label:d[1],type:d[2],required:d[3],options:d[4],value:d[0]==='transaction_type'?a:d[0]==='transaction_date'?today():''})),v=>insert('finance',v,'finance_transactions'))}if(a==='new-task')return openNew('tasks');if(a==='new-reminder')return openNew('reminders');if(a==='new-success')return openNew('success');if(a==='new-document')return openNew('documents')}
function nav(view){currentView=view;render(view)}
window.nav=nav;
document.addEventListener('click',e=>{const navBtn=e.target.closest('nav button[data-view]');if(navBtn){e.preventDefault();nav(navBtn.dataset.view);return}const act=e.target.closest('[data-action]');if(act){action(act.dataset.action);return}const ed=e.target.closest('[data-edit]');if(ed){const [key,id]=ed.dataset.edit.split('|');openEditor(key,id);return}const prof=e.target.closest('[data-profile]');if(prof){renderProfile(prof.dataset.profile);return}const del=e.target.closest('[data-del]');if(del){const [key,id]=del.dataset.del.split('|');if(confirm('Θέλεις να διαγράψεις αυτή την καταχώριση;'))remove(key,id,CLOUD_TABLES[key]);return}const t=e.target.closest('[data-task]');if(t){const x=state.tasks.find(v=>v.id===t.dataset.task);if(x)update('tasks',x.id,{completed:!x.completed},'planner_tasks');return}const r=e.target.closest('[data-reminder]');if(r){const x=state.reminders.find(v=>v.id===r.dataset.reminder);if(x)update('reminders',x.id,{completed:!x.completed},'reminders');return}const s=e.target.closest('[data-success]');if(s){const x=state.success.find(v=>v.id===s.dataset.success);if(x)update('success',x.id,{completed:!x.completed},'daily_success');return}const f=e.target.closest('[data-follow]');if(f){const x=state.followups.find(v=>v.id===f.dataset.follow);if(x)update('followups',x.id,{status:x.status==='completed'?'pending':'completed'},'follow_ups');return}});
function renderProfile(id){currentView='profile';$('#app').innerHTML=clientProfile(id);setStatus()}
document.addEventListener('DOMContentLoaded',()=>{render('dashboard');startCloud()});