/* Nikoleta Wellness CEO — polished production UI */
const SUPABASE_URL='https://vbkuvexyqehmpeeejqbh.supabase.co';
const SUPABASE_KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY)||null;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>crypto.randomUUID();
const today=()=>new Date().toISOString().slice(0,10);
const money=v=>Number(v||0).toLocaleString('el-GR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
const dateGR=v=>v?new Date(v+'T00:00:00').toLocaleDateString('el-GR',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
const time24=v=>v?String(v).slice(0,5):'—';
const stateKey='nwceo_final_v1';
const empty={clients:[],appointments:[],partners:[],measurements:[],programs:[],followups:[],orders:[],finance:[],tasks:[],reminders:[],success:[],documents:[]};
let state=JSON.parse(localStorage.getItem(stateKey)||'null')||structuredClone(empty);
let user=null,view='dashboard',editing=null,online=navigator.onLine,syncing=false;
const tables={
 clients:{table:'clients',fields:{name:'όνομα',phone:'τηλέφωνο',email:'email',address:'διεύθυνση',birth_date:'birth_date',notes:'σημειώσεις',status:'κατάσταση'}},
 appointments:{table:'Ραντεβού',fields:{client_id:'client_id',title:'Τίτλος',date:'appointment_date',start_time:'start_time',end_time:'end_time',type:'appointment_type',status:'Κατάσταση',notes:'Σημειώσεις',reminder_minutes:'reminder_minutes'}},
 partners:{table:'Συνεργάτες',fields:{name:'όνομα',phone:'τηλέφωνο',email:'email',business:'Επιχείρηση',notes:'Σημειώσεις',status:'Κατάσταση'}},
 measurements:{table:'tanita_measurements',fields:{client_id:'client_id',date:'measurement_date',weight:'Βάρος',fat:'body_fat',muscle:'muscle_mass',water:'water_percent',bone:'bone_mass',visceral:'visceral_fat',calories:'θερμίδες',metabolic_age:'metabolic_age',fitness_score:'fitness_score',notes:'Σημειώσεις'}},
 programs:{table:'Προγράμματα',fields:{client_id:'client_id',title:'Τίτλος',start_date:'start_date',end_date:'end_date',calories:'θερμίδες',protein:'Πρωτεΐνη',description:'Περιγραφή',notes:'Σημειώσεις',status:'Κατάσταση'}},
 followups:{table:'follow_ups',fields:{client_id:'client_id',title:'Τίτλος',date:'follow_up_date',time:'follow_up_time',status:'Κατάσταση',notes:'Σημειώσεις',reminder_minutes:'reminder_minutes'}},
 orders:{table:'Παραγγελίες',fields:{client_id:'client_id',date:'order_date',product:'product_name',quantity:'Ποσότητα',unit_price:'unit_price',total:'total_amount',status:'Κατάσταση',notes:'Σημειώσεις'}},
 finance:{table:'finance_transactions',fields:{type:'transaction_type',amount:'Ποσό',date:'transaction_date',category:'Κατηγορία',description:'Περιγραφή',client_id:'client_id'}},
 tasks:{table:'planner_tasks',fields:{title:'Τίτλος',description:'Περιγραφή',date:'task_date',start_time:'start_time',end_time:'end_time',completed:'ολοκληρώθηκε',reminder_minutes:'reminder_minutes',priority:'Προτεραιότητα'}},
 reminders:{table:'Υπενθυμίσεις',fields:{title:'Τίτλος',date:'reminder_date',time:'reminder_time',reminder_minutes:'reminder_minutes',related_type:'related_type',related_id:'related_id',completed:'ολοκληρώθηκε',notes:'Σημειώσεις'}},
 success:{table:'daily_success',fields:{date:'success_date',task:'Εργασία',completed:'ολοκληρώθηκε',notes:'Σημειώσεις'}},
 documents:{table:'Έγγραφα',fields:{title:'Τίτλος',file_name:'file_name',file_path:'file_path',file_type:'file_type',file_size:'file_size',related_type:'related_type',related_id:'related_id'}}
};
const numKeys=new Set(['amount','quantity','unit_price','total','weight','fat','muscle','water','bone','visceral','calories','protein','metabolic_age','fitness_score','file_size','reminder_minutes']);
const clientName=id=>state.clients.find(c=>c.id===id)?.name||'Χωρίς πελάτη';
function save(){localStorage.setItem(stateKey,JSON.stringify(state));}
function mark(){save();render();queueSync();}
function normalize(k,x){const o={...x,id:x.id||uid()};if(k==='appointments'){o.date=o.date||o.appointment_date||'';o.start_time=o.start_time||'';o.end_time=o.end_time||'';o.title=o.title||o.Τίτλος||'Ραντεβού'}if(k==='clients')o.name=o.name||o.όνομα||'';return o}
Object.keys(state).forEach(k=>state[k]=(state[k]||[]).map(x=>normalize(k,x)));
let pending=JSON.parse(localStorage.getItem('nwceo_pending_final')||'[]');
function queue(op){pending.push(op);localStorage.setItem('nwceo_pending_final',JSON.stringify(pending));}
function row(k,o){const r={id:o.id,user_id:user?.id||null};for(const [key,dbk] of Object.entries(tables[k].fields)){let v=o[key];if(numKeys.has(key))v=v===''||v==null?null:Number(v);if(key==='completed')v=!!v;r[dbk]=v===''?null:v}return r}
async function sync(){if(!db||!user||!online||syncing)return;syncing=true;setSync('sync');try{
  for(const op of pending){if(op.type==='upsert')await db.from(tables[op.k].table).upsert(row(op.k,op.data),{onConflict:'id'});if(op.type==='delete')await db.from(tables[op.k].table).delete().eq('id',op.id).eq('user_id',user.id)}
  pending=[];localStorage.setItem('nwceo_pending_final','[]');
  for(const k of Object.keys(tables)){const {data}=await db.from(tables[k].table).select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(data)state[k]=data.map(x=>normalize(k,x));}
  save();setSync('ok');render();
}catch(e){console.warn(e);setSync('offline')}finally{syncing=false}}
function queueSync(){if(user&&online)sync()}
async function loadSession(){if(!db){render();return}const s=await db.auth.getSession();user=s.data.session?.user||null;if(user)await sync();else render();db.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;setSync(user?(online?'ok':'offline'):'local');render()})}
function setSync(kind){const el=$('.sync-badge');if(!el)return;el.className='sync-badge '+kind;el.innerHTML=kind==='ok'?'☁️ Συγχρονισμένο':kind==='sync'?'↻ Συγχρονισμός…':kind==='offline'?'📴 Offline — αποθηκεύεται':'📱 Μόνο στη συσκευή'}
window.addEventListener('online',()=>{online=true;setSync(user?'sync':'local');sync()});window.addEventListener('offline',()=>{online=false;setSync('offline')});
function openAuth(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="auth"><div class="modal-card auth-card"><button class="x" data-close>×</button><div class="brand-mini">🌿</div><h2>Σύνδεση Wellness CEO</h2><p>Ο ίδιος λογαριασμός = τα ίδια δεδομένα σε κινητό, tablet και υπολογιστή.</p><label>Email<input id="ae" type="email" autocomplete="email"></label><label>Κωδικός<input id="ap" type="password" autocomplete="current-password"></label><div class="modal-actions"><button class="primary" data-auth="login">Σύνδεση</button><button data-auth="signup">Δημιουργία λογαριασμού</button></div><div id="am" class="authmsg"></div></div></div>`)}
async function auth(mode){const email=$('#ae')?.value.trim(),password=$('#ap')?.value;if(!email||password.length<6){$('#am').textContent='Βάλε email και κωδικό τουλάχιστον 6 χαρακτήρων.';return}$('#am').textContent='Γίνεται σύνδεση…';const r=mode==='signup'?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(r.error){$('#am').textContent=r.error.message;return}if(!r.data.session){$('#am').textContent='Έλεγξε το email σου και μετά συνδέσου.';return}user=r.data.user;$('#auth')?.remove();await sync();render()}
function initials(n){return (n||'').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'N'}
function pageHead(title,sub,button=''){return `<div class="page-head"><div><div class="eyebrow">WELLNESS CEO</div><h1>${title}</h1><p>${sub}</p></div>${button?`<button class="primary big" data-new="${button}">＋ Νέα εγγραφή</button>`:''}</div>`}
function card(item,k){const n=k==='clients'?item.name:k==='appointments'?clientName(item.client_id):k==='partners'?item.name:k==='measurements'?clientName(item.client_id):item.title||item.description||item.product||item.task||item.category||'Εγγραφή';let meta='';if(k==='appointments')meta=`${dateGR(item.date)} · ${time24(item.start_time)}${item.end_time?'–'+time24(item.end_time):''} · ${item.type||'Ραντεβού'}`;else if(k==='clients')meta=`${item.phone||'Χωρίς τηλέφωνο'} · ${item.status||'Ενεργός'}`;else if(k==='measurements')meta=`${dateGR(item.date)} · ${item.weight||'—'} kg · ${item.fat||'—'}% λίπος · ${item.muscle||'—'} kg μυς`;else meta=item.notes||item.description||item.status||'';return `<div class="data-card"><div class="avatar">${k==='clients'||k==='partners'?esc(initials(n)):'✦'}</div><div class="card-main"><strong>${esc(n)}</strong><span>${esc(meta)}</span></div><div class="card-actions"><button class="icon-btn" data-edit="${k}" data-id="${item.id}" aria-label="Επεξεργασία">✎</button><button class="icon-btn danger" data-delete="${k}" data-id="${item.id}" aria-label="Διαγραφή">⌫</button></div></div>`}
function list(k,items,emptyText='Δεν υπάρχουν εγγραφές ακόμη.'){return items.length?`<div class="data-list">${items.map(x=>card(x,k)).join('')}</div>`:`<div class="empty-state"><div>✦</div><strong>${emptyText}</strong><span>Πάτησε «Νέα εγγραφή» για να ξεκινήσεις.</span></div>`}
function clientOptions(sel=''){return `<option value="">Χωρίς σύνδεση</option>`+state.clients.map(c=>`<option value="${esc(c.id)}" ${c.id===sel?'selected':''}>${esc(c.name)}</option>`).join('')}
const F=(label,name,type='text',value='',req='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${req}></label>`;
const S=(label,name,opts)=>`<label>${label}<select name="${name}">${opts}</select></label>`;
const T=(label,name,value='')=>`<label class="wide">${label}<textarea name="${name}">${esc(value)}</textarea></label>`;
function modal(k,id=''){const x=id?(state[k].find(a=>a.id===id)||{}):{};let h=`<div class="modal" id="editor"><form class="modal-card form-card" data-form="${k}" data-id="${id}"><button type="button" class="x" data-close>×</button><div class="form-head"><div class="brand-mini">🌿</div><div><div class="eyebrow">WELLNESS CEO</div><h2>${id?'Επεξεργασία':'Νέα εγγραφή'}</h2><p>${labelFor(k)}</p></div></div><div class="form-grid">`;
if(k==='clients')h+=F('Ονοματεπώνυμο *','name','text',x.name,'required')+F('Τηλέφωνο','phone','tel',x.phone)+F('Email','email',x.email)+F('Ημερομηνία γέννησης','birth_date','date',x.birth_date)+F('Διεύθυνση','address',x.address)+S('Κατάσταση','status',`<option ${x.status==='Ενεργός'||!x.status?'selected':''}>Ενεργός</option><option ${x.status==='Ανενεργός'?'selected':''}>Ανενεργός</option><option ${x.status==='Follow-up'?'selected':''}>Follow-up</option>`)+T('Σημειώσεις','notes',x.notes);
if(k==='appointments')h+=F('Ονοματεπώνυμο πελάτη *','client_name','text',clientName(x.client_id)==='Χωρίς πελάτη'?'':clientName(x.client_id),'required')+S('Σύνδεση με υπάρχοντα πελάτη','client_id',clientOptions(x.client_id))+F('Τίτλος ραντεβού','title','text',x.title||'Ραντεβού','required')+F('Ημερομηνία','date','date',x.date||today(),'required')+F('Ώρα έναρξης (24ωρο)','start_time','time',time24(x.start_time))+F('Ώρα λήξης (24ωρο)','end_time','time',time24(x.end_time))+F('Τύπος','type','text',x.type||'Wellness')+F('Υπενθύμιση (λεπτά πριν)','reminder_minutes','number',x.reminder_minutes||0)+S('Κατάσταση','status',`<option ${!x.status||x.status==='Προγραμματισμένο'?'selected':''}>Προγραμματισμένο</option><option ${x.status==='Ολοκληρώθηκε'?'selected':''}>Ολοκληρώθηκε</option><option ${x.status==='Ακυρώθηκε'?'selected':''}>Ακυρώθηκε</option>`)+T('Σημειώσεις','notes',x.notes);
if(k==='partners')h+=F('Ονοματεπώνυμο *','name','text',x.name,'required')+F('Τηλέφωνο','phone','tel',x.phone)+F('Email','email',x.email)+F('Επιχείρηση','business',x.business)+S('Κατάσταση','status',`<option>Ενεργός</option><option>Ανενεργός</option>`)+T('Σημειώσεις','notes',x.notes);
if(k==='measurements')h+=S('Πελάτης','client_id',clientOptions(x.client_id))+F('Ημερομηνία','date','date',x.date||today(),'required')+F('Βάρος (kg)','weight','number',x.weight)+F('Σωματικό λίπος (%)','fat','number',x.fat)+F('Μυϊκή μάζα (kg)','muscle','number',x.muscle)+F('Νερό (%)','water','number',x.water)+F('Οστική μάζα (kg)','bone','number',x.bone)+F('Σπλαχνικό λίπος','visceral','number',x.visceral)+F('Θερμίδες','calories','number',x.calories)+F('Μεταβολική ηλικία','metabolic_age','number',x.metabolic_age)+F('Fitness Score','fitness_score','number',x.fitness_score)+T('Σημειώσεις','notes',x.notes);
if(k==='programs')h+=S('Πελάτης','client_id',clientOptions(x.client_id))+F('Τίτλος','title','text',x.title,'required')+F('Έναρξη','start_date','date',x.start_date||today())+F('Λήξη','end_date','date',x.end_date)+F('Θερμίδες','calories','number',x.calories)+F('Πρωτεΐνη (g)','protein','number',x.protein)+S('Κατάσταση','status','<option>Ενεργό</option><option>Ολοκληρωμένο</option><option>Πρόχειρο</option>')+T('Περιγραφή','description',x.description)+T('Σημειώσεις','notes',x.notes);
if(k==='followups')h+=S('Πελάτης','client_id',clientOptions(x.client_id))+F('Τίτλος','title','text',x.title,'required')+F('Ημερομηνία','date','date',x.date||today())+F('Ώρα (24ωρο)','time','time',time24(x.time))+F('Υπενθύμιση','reminder_minutes','number',x.reminder_minutes||0)+S('Κατάσταση','status','<option>Ανοιχτό</option><option>Ολοκληρώθηκε</option>')+T('Σημειώσεις','notes',x.notes);
if(k==='orders')h+=S('Πελάτης','client_id',clientOptions(x.client_id))+F('Ημερομηνία','date','date',x.date||today())+F('Προϊόν','product','text',x.product,'required')+F('Ποσότητα','quantity','number',x.quantity||1)+F('Τιμή μονάδας (€)','unit_price','number',x.unit_price)+F('Σύνολο (€)','total','number',x.total)+S('Κατάσταση','status','<option>Εκκρεμεί</option><option>Παραγγέλθηκε</option><option>Παραδόθηκε</option>')+T('Σημειώσεις','notes',x.notes);
if(k==='finance')h+=S('Τύπος','type','<option value="income">Έσοδο</option><option value="expense">Έξοδο</option>')+F('Ποσό (€)','amount','number',x.amount,'required')+F('Ημερομηνία','date','date',x.date||today())+F('Κατηγορία','category','text',x.category)+F('Περιγραφή','description','text',x.description)+S('Πελάτης','client_id',clientOptions(x.client_id));
if(k==='tasks')h+=F('Εργασία','title','text',x.title,'required')+F('Ημερομηνία','date','date',x.date||today())+F('Ώρα έναρξης','start_time','time',time24(x.start_time))+F('Ώρα λήξης','end_time','time',time24(x.end_time))+S('Προτεραιότητα','priority','<option>Κανονική</option><option>Υψηλή</option><option>Άμεση</option>')+F('Υπενθύμιση','reminder_minutes','number',x.reminder_minutes||0)+T('Περιγραφή','description',x.description);
if(k==='reminders')h+=F('Τίτλος','title','text',x.title,'required')+F('Ημερομηνία','date','date',x.date||today())+F('Ώρα (24ωρο)','time','time',time24(x.time))+F('Λεπτά πριν','reminder_minutes','number',x.reminder_minutes||0)+T('Σημειώσεις','notes',x.notes);
if(k==='success')h+=F('Εργασία','task','text',x.task,'required')+F('Ημερομηνία','date','date',x.date||today())+T('Σημειώσεις','notes',x.notes);
return h+`</div><div class="modal-actions"><button type="button" data-close>Ακύρωση</button><button class="primary" type="submit">✓ Αποθήκευση</button></div></form></div>`}
function labelFor(k){return ({clients:'Καρτέλα πελάτη',appointments:'Ραντεβού και υπενθύμιση',partners:'Δίκτυο συνεργατών',measurements:'Καταγραφή Tanita',programs:'Πρόγραμμα ευεξίας',followups:'Σύστημα Follow-up',orders:'Παραγγελία προϊόντων',finance:'Έσοδα και έξοδα',tasks:'Ημερήσιο Planner',reminders:'Υπενθυμίσεις',success:'Daily Success'})[k]||'Wellness CEO'}
function dashboard(){const ap=state.appointments.filter(a=>a.date===today());const active=state.clients.filter(c=>(c.status||'Ενεργός')!=='Ανενεργός').length;const openFU=state.followups.filter(x=>x.status!=='Ολοκληρώθηκε').length;const income=state.finance.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount||0),0),expense=state.finance.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount||0),0);return `<section class="hero"><div class="hero-copy"><div class="eyebrow">NIKOΛETA WELLNESS CEO</div><h1>Καλώς ήρθες, Nikoleta <span>✦</span></h1><p>Οργάνωσε την επιχείρησή σου όμορφα, απλά και από παντού.</p><div class="hero-actions"><button class="primary" data-new="clients">＋ Νέος πελάτης</button><button data-new="appointments">📅 Ραντεβού</button><button data-new="measurements">⚖️ Tanita</button><button data-view="documents">📄 PDF</button></div></div><div class="hero-seal">HEALTHY<br><b>LIFE</b><small>WELLNESS</small></div></section><div class="stats"><div class="stat"><span>📅</span><b>${ap.length}</b><small>Ραντεβού σήμερα</small></div><div class="stat"><span>👥</span><b>${active}</b><small>Ενεργοί πελάτες</small></div><div class="stat"><span>📞</span><b>${openFU}</b><small>Ανοιχτά follow-ups</small></div><div class="stat"><span>💰</span><b>${money(income-expense)}</b><small>Καθαρό αποτέλεσμα</small></div></div><div class="dashboard-grid"><div class="panel"><div class="panel-head"><h2>Σήμερα</h2><button data-view="appointments">Όλα τα ραντεβού →</button></div>${ap.length?ap.slice(0,5).map(a=>card(a,'appointments')).join(''):'<div class="soft-empty">Δεν έχεις ραντεβού για σήμερα.</div>'}</div><div class="panel"><div class="panel-head"><h2>Γρήγορες ενέργειες</h2></div><div class="quick-grid"><button data-new="clients">👥<b>Νέος πελάτης</b><small>Νέα καρτέλα</small></button><button data-new="appointments">📅<b>Νέο ραντεβού</b><small>Με ώρα 24ωρου</small></button><button data-new="measurements">⚖️<b>Tanita</b><small>Νέα μέτρηση</small></button><button data-view="documents">📄<b>Έγγραφα / PDF</b><small>Προεπισκόπηση</small></button></div></div></div>`}
function appointments(){const items=[...state.appointments].sort((a,b)=>(a.date+a.start_time).localeCompare(b.date+b.start_time));return pageHead('📅 Ραντεβού','Όλα τα ραντεβού σου, με ονοματεπώνυμο και 24ωρη ώρα.','appointments')+`<div class="toolbar"><input id="search" placeholder="🔎 Αναζήτηση ονόματος…"><span>${items.length} ραντεβού</span></div>${list('appointments',items,'Δεν υπάρχουν ραντεβού ακόμη.')}`}
function clients(){return pageHead('👥 Καρτέλες Πελατών','Καταγραφή · Παρακολούθηση · Υποστήριξη','clients')+`<div class="toolbar"><input id="search" placeholder="🔎 Αναζήτηση πελάτη…"><span>${state.clients.length} πελάτες</span></div>${list('clients',state.clients,'Δεν έχεις καταχωρήσει πελάτες ακόμη.')}`}
function generic(k,title,sub){return pageHead(title,sub,k)+list(k,state[k])}
function documents(){return pageHead('📁 Έγγραφα & PDF','Δημιούργησε αναφορά πελάτη και άνοιξέ την άμεσα για αποθήκευση ως PDF.')+`<div class="document-grid"><div class="panel"><h2>Προσωπική αξιολόγηση</h2><p>Όνομα, τελευταία Tanita, στόχοι και σημειώσεις.</p><label>Πελάτης<select id="pdfClient">${clientOptions()}</select></label><button class="primary big" data-pdf>📄 Δημιουργία PDF</button></div><div class="panel"><h2>Πώς αποθηκεύεται</h2><p>Πατάς «Δημιουργία PDF» → ανοίγει καθαρή αναφορά → «Εκτύπωση» → «Αποθήκευση ως PDF».</p><div class="pdf-note">Το PDF ανοίγει σε ξεχωριστό παράθυρο και είναι έτοιμο για εκτύπωση.</div></div></div><div class="panel"><div class="panel-head"><h2>Αποθηκευμένα έγγραφα</h2></div>${state.documents.length?list('documents',state.documents):'<div class="soft-empty">Τα έγγραφα που δημιουργείς από εδώ εμφανίζονται στη βιβλιοθήκη.</div>'}</div>`}
function render(){const app=$('#app');if(!app)return;$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));let html=view==='dashboard'?dashboard():view==='appointments'?appointments():view==='clients'?clients():view==='documents'?documents():view==='partners'?generic('partners','🤝 Συνεργάτες','Συνεργασίες και επαφές'):view==='measurements'?generic('measurements','⚖️ Tanita','Όλες οι μετρήσεις σώματος'):view==='programs'?generic('programs','🥤 Προγράμματα','Προγράμματα διατροφής και ευεξίας'):view==='followups'?generic('followups','📞 Follow-ups','Ποιον χρειάζεται να καλέσεις'):view==='orders'?generic('orders','📦 Παραγγελίες','Παραγγελίες και εκκρεμότητες'):view==='finance'?generic('finance','💰 Οικονομικά','Έσοδα και έξοδα'):view==='tasks'?generic('tasks','📝 Planner','Η καθημερινή σου οργάνωση'):view==='reminders'?generic('reminders','🔔 Υπενθυμίσεις','Ό,τι δεν θέλεις να ξεχάσεις'):view==='success'?generic('success','🏆 Daily Success','Μικρές νίκες κάθε μέρα'):dashboard();app.innerHTML=html;setSync(user?(online?'ok':'offline'):'local')}
function edit(k,id){document.body.insertAdjacentHTML('beforeend',modal(k,id))}
function remove(k,id){if(!confirm('Να διαγραφεί αυτή η εγγραφή;'))return;state[k]=state[k].filter(x=>x.id!==id);queue({type:'delete',k,id});mark()}
function createClientByName(name){let c=state.clients.find(x=>x.name.trim().toLowerCase()===name.trim().toLowerCase());if(c)return c; c={id:uid(),name:name.trim(),status:'Ενεργός',notes:'Δημιουργήθηκε αυτόματα από ραντεβού'};state.clients.push(c);queue({type:'upsert',k:'clients',data:c});return c}
function saveForm(form){const k=form.dataset.form,id=form.dataset.id;const fd=new FormData(form),o={id:id||uid()};for(const [key,v] of fd.entries())o[key]=v;if(k==='appointments'){const typed=(o.client_name||'').trim();let c=state.clients.find(x=>x.id===o.client_id);if(!c&&typed)c=createClientByName(typed);o.client_id=c?.id||'';delete o.client_name;o.reminder_minutes=Number(o.reminder_minutes||0)}if(k==='orders'&&!o.total)o.total=Number(o.quantity||0)*Number(o.unit_price||0);if(['measurements','finance','orders','programs'].includes(k))Object.keys(o).forEach(z=>{if(numKeys.has(z))o[z]=o[z]===''?'':Number(o[z])});if(k==='success')o.completed=!!o.completed;const idx=state[k].findIndex(x=>x.id===o.id);if(idx>=0)state[k][idx]={...state[k][idx],...o};else state[k].unshift(o);queue({type:'upsert',k,data:o});form.closest('.modal')?.remove();mark()}
function searchFilter(){const q=$('#search')?.value.trim().toLowerCase();if(!q)return;const cards=$$('.data-card');cards.forEach(c=>c.style.display=c.textContent.toLowerCase().includes(q)?'':'none')}
function pdf(){const id=$('#pdfClient')?.value;if(!id){alert('Διάλεξε πρώτα πελάτη.');return}const c=state.clients.find(x=>x.id===id);const ms=state.measurements.filter(x=>x.client_id===id).sort((a,b)=>(b.date||'').localeCompare(a.date||''));const m=ms[0]||{};const a=state.appointments.filter(x=>x.client_id===id).sort((x,y)=>(y.date||'').localeCompare(x.date||''))[0]||{};const w=window.open('','_blank');if(!w)return;w.document.write(`<!doctype html><html lang="el"><head><meta charset="utf-8"><title>Wellness Report - ${esc(c.name)}</title><style>body{font-family:Arial,sans-serif;margin:0;background:#f7f4ea;color:#233a29}.sheet{max-width:820px;margin:30px auto;background:#fffdf8;padding:42px;border:1px solid #ddd3b8;border-radius:22px}.brand{text-align:center;font-size:30px;color:#245b2b;font-weight:800}.gold{color:#b69a4b}.hero{display:flex;gap:20px;align-items:center;border-bottom:1px solid #e6dfcd;padding:22px 0}.avatar{width:80px;height:80px;border-radius:50%;background:#eaf1e5;display:grid;place-items:center;font-size:26px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}.box{border:1px solid #e4ddca;border-radius:14px;padding:14px;background:#fbfaf5}.box b{display:block;font-size:20px;margin-top:5px}.section{margin-top:26px}.print{display:block;margin:24px auto;padding:12px 18px;background:#245b2b;color:#fff;border:0;border-radius:12px;font-size:16px}@media print{.print{display:none}.sheet{margin:0;border:0}}</style></head><body><div class="sheet"><div class="brand">HEALTHY <span class="gold">LIFE</span></div><div style="text-align:center">NIKOΛETA WELLNESS CEO · ΠΡΟΣΩΠΙΚΗ ΑΞΙΟΛΟΓΗΣΗ</div><div class="hero"><div class="avatar">${esc(initials(c.name))}</div><div><h1>${esc(c.name)}</h1><div>${esc(c.phone||'')} ${esc(c.email||'')}</div><div>Κατάσταση: ${esc(c.status||'Ενεργός')}</div></div></div><div class="grid"><div class="box">Βάρος<b>${m.weight||'—'} kg</b></div><div class="box">Σωματικό λίπος<b>${m.fat||'—'} %</b></div><div class="box">Μυϊκή μάζα<b>${m.muscle||'—'} kg</b></div><div class="box">Μεταβολική ηλικία<b>${m.metabolic_age||'—'}</b></div></div><div class="section"><h2>Τελευταία μέτρηση Tanita</h2><p>Ημερομηνία: ${dateGR(m.date)} · Νερό: ${m.water||'—'}% · Σπλαχνικό: ${m.visceral||'—'}</p></div><div class="section"><h2>Τελευταίο ραντεβού</h2><p>${dateGR(a.date)} · ${time24(a.start_time)} · ${esc(a.title||'Ραντεβού')}</p></div><div class="section"><h2>Σημειώσεις</h2><p>${esc(c.notes||'—')}</p></div><button class="print" onclick="window.print()">🖨 Εκτύπωση / Αποθήκευση ως PDF</button></div></body></html>`);w.document.close();const d={id:uid(),title:`Προσωπική αξιολόγηση — ${c.name}`,file_name:`wellness-${c.id}.pdf`,file_type:'PDF',related_type:'client',related_id:c.id};state.documents.unshift(d);queue({type:'upsert',k:'documents',data:d});save()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();return}if(b.dataset.new){edit(b.dataset.new);return}if(b.dataset.edit){edit(b.dataset.edit,b.dataset.id);return}if(b.dataset.delete){remove(b.dataset.delete,b.dataset.id);return}if(b.dataset.close){b.closest('.modal')?.remove();return}if(b.dataset.auth){auth(b.dataset.auth);return}if(b.dataset.pdf){pdf();return}if(b.dataset.view==='documents'){view='documents';render()}});
document.addEventListener('submit',e=>{if(e.target.matches('[data-form]')){e.preventDefault();saveForm(e.target)}});
document.addEventListener('input',e=>{if(e.target.id==='search')searchFilter()});
$('#app')?.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;render()}});
render();loadSession();
