const SUPABASE_URL='https://vbkuvexyqehmpeeejqbh.supabase.co';
const SUPABASE_KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>crypto.randomUUID();
const today=()=>new Date().toISOString().slice(0,10);
const fmtDate=v=>v?new Date(v+'T00:00:00').toLocaleDateString('el-GR'):'—';
const fmtTime=v=>{if(!v)return '—';const m=String(v).match(/^(\d{1,2}):(\d{2})/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:String(v)};
const money=v=>Number(v||0).toLocaleString('el-GR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
let userId=null,cloud=false,current='dashboard';
const S={clients:[],appointments:[],partners:[],measurements:[],programs:[],followups:[],orders:[],finance:[],tasks:[],reminders:[],success:[],documents:[]};
let state=JSON.parse(localStorage.getItem('nwceo_local_v5')||'null')||S;
const tables={clients:'clients',appointments:'Ραντεβού',partners:'Συνεργάτες',measurements:'tanita_measurements',programs:'Προγράμματα',followups:'follow_ups',orders:'Παραγγελίες',finance:'finance_transactions',tasks:'planner_tasks',reminders:'Υπενθυμίσεις',success:'daily_success',documents:'Έγγραφα'};
const normalize=(key,x)=>{const o={...x,id:x.id||uid()};
 if(key==='clients')Object.assign(o,{name:x.όνομα??x.name??'',phone:x.τηλέφωνο??x.phone??'',email:x.email??'',address:x.διεύθυνση??x.address??'',birth_date:x.birth_date??'',notes:x.σημειώσεις??x.notes??'',status:x.κατάσταση??x.status??''});
 if(key==='appointments')Object.assign(o,{client_id:x.client_id??'',title:x.Τίτλος??x.title??'',date:x.appointment_date??x.date??'',start_time:x.start_time??x.time??'',end_time:x.end_time??'',type:x.appointment_type??x.type??'',status:x.Κατάσταση??x.status??'',notes:x.Σημειώσεις??x.notes??'',reminder_minutes:x.reminder_minutes??0});
 if(key==='partners')Object.assign(o,{name:x.όνομα??x.name??'',phone:x.τηλέφωνο??x.phone??'',email:x.email??'',business:x.Επιχείρηση??x.business??'',notes:x.Σημειώσεις??x.notes??'',status:x.Κατάσταση??x.status??''});
 if(key==='measurements')Object.assign(o,{client_id:x.client_id??'',date:x.measurement_date??x.date??'',weight:x.Βάρος??x.weight??'',fat:x.body_fat??'',muscle:x.muscle_mass??'',water:x.water_percent??'',bone:x.bone_mass??'',visceral:x.visceral_fat??'',calories:x.θερμίδες??x.calories??'',metabolic_age:x.metabolic_age??'',fitness_score:x.fitness_score??'',notes:x.Σημειώσεις??x.notes??''});
 if(key==='programs')Object.assign(o,{client_id:x.client_id??'',title:x.Τίτλος??x.title??'',start_date:x.start_date??'',end_date:x.end_date??'',calories:x.θερμίδες??'',protein:x.Πρωτεΐνη??'',description:x.Περιγραφή??'',notes:x.Σημειώσεις??'',status:x.Κατάσταση??''});
 if(key==='followups')Object.assign(o,{client_id:x.client_id??'',title:x.Τίτλος??x.title??'',date:x.follow_up_date??'',time:x.follow_up_time??'',status:x.Κατάσταση??'',notes:x.Σημειώσεις??'',reminder_minutes:x.reminder_minutes??0});
 if(key==='orders')Object.assign(o,{client_id:x.client_id??'',date:x.order_date??'',product:x.product_name??'',quantity:x.Ποσότητα??'',unit_price:x.unit_price??'',total:x.total_amount??'',status:x.Κατάσταση??'',notes:x.Σημειώσεις??''});
 if(key==='finance')Object.assign(o,{type:x.transaction_type??'',amount:x.Ποσό??'',date:x.transaction_date??'',category:x.Κατηγορία??'',description:x.Περιγραφή??'',client_id:x.client_id??''});
 if(key==='tasks')Object.assign(o,{title:x.Τίτλος??x.title??'',description:x.Περιγραφή??x.description??'',date:x.task_date??'',start_time:x.start_time??'',end_time:x.end_time??'',completed:x.ολοκληρώθηκε??x.completed??false,reminder_minutes:x.reminder_minutes??0,priority:x.Προτεραιότητα??x.priority??''});
 if(key==='reminders')Object.assign(o,{title:x.Τίτλος??x.title??'',date:x.reminder_date??'',time:x.reminder_time??'',reminder_minutes:x.reminder_minutes??0,related_type:x.related_type??'',related_id:x.related_id??'',completed:x.ολοκληρώθηκε??x.completed??false,notes:x.Σημειώσεις??x.notes??''});
 if(key==='success')Object.assign(o,{date:x.success_date??'',task:x.Εργασία??x.task??'',completed:x.ολοκληρώθηκε??x.completed??false,notes:x.Σημειώσεις??''});
 if(key==='documents')Object.assign(o,{title:x.Τίτλος??x.title??'',file_name:x.file_name??'',file_path:x.file_path??'',file_type:x.file_type??'',file_size:x.file_size??0,related_type:x.related_type??'',related_id:x.related_id??''});
 return o};
Object.keys(S).forEach(k=>state[k]=(Array.isArray(state[k])?state[k]:[]).map(x=>normalize(k,x)));
function save(){localStorage.setItem('nwceo_local_v5',JSON.stringify(state))}
function clientName(id){return state.clients.find(c=>c.id===id)?.name||'—'}
function opts(selected=''){return `<option value="">Χωρίς πελάτη</option>`+state.clients.map(c=>`<option value="${esc(c.id)}" ${c.id===selected?'selected':''}>${esc(c.name||'Χωρίς όνομα')}</option>`).join('')}
async function login(){try{const s=await db.auth.getSession();if(s.data.session){userId=s.data.session.user.id}else{const r=await db.auth.signInAnonymously();userId=r.data.user.id}cloud=!!userId}catch(e){console.warn(e);cloud=false}}
async function load(){if(!cloud)return;for(const k of Object.keys(tables)){try{const {data,error}=await db.from(tables[k]).select('*').eq('user_id',userId).order('created_at',{ascending:false});if(!error&&Array.isArray(data)&&data.length)state[k]=data.map(x=>normalize(k,x))}catch(e){console.warn(k,e.message)}}save()}
function dbRow(k,o){const id=o.id||uid();
 if(k==='clients')return {id,user_id:userId,όνομα:o.name,τηλέφωνο:o.phone||null,email:o.email||null,διεύθυνση:o.address||null,birth_date:o.birth_date||null,σημειώσεις:o.notes||null,κατάσταση:o.status||null};
 if(k==='appointments')return {id,user_id:userId,client_id:o.client_id||null,Τίτλος:o.title||'Ραντεβού',appointment_date:o.date,start_time:o.start_time,end_time:o.end_time||null,appointment_type:o.type||null,Κατάσταση:o.status||null,Σημειώσεις:o.notes||null,reminder_minutes:Number(o.reminder_minutes||0)};
 if(k==='partners')return {id,user_id:userId,όνομα:o.name,τηλέφωνο:o.phone||null,email:o.email||null,Επιχείρηση:o.business||null,Σημειώσεις:o.notes||null,Κατάσταση:o.status||null};
 if(k==='measurements')return {id,user_id:userId,client_id:o.client_id||null,measurement_date:o.date,Βάρος:o.weight===''?null:Number(o.weight),body_fat:o.fat===''?null:Number(o.fat),muscle_mass:o.muscle===''?null:Number(o.muscle),water_percent:o.water===''?null:Number(o.water),bone_mass:o.bone===''?null:Number(o.bone),visceral_fat:o.visceral===''?null:Number(o.visceral),θερμίδες:o.calories===''?null:Number(o.calories),metabolic_age:o.metabolic_age===''?null:Number(o.metabolic_age),fitness_score:o.fitness_score===''?null:Number(o.fitness_score),Σημειώσεις:o.notes||null};
 if(k==='programs')return {id,user_id:userId,client_id:o.client_id||null,Τίτλος:o.title,start_date:o.start_date||null,end_date:o.end_date||null,θερμίδες:o.calories===''?null:Number(o.calories),Πρωτεΐνη:o.protein===''?null:Number(o.protein),Περιγραφή:o.description||null,Σημειώσεις:o.notes||null,Κατάσταση:o.status||null};
 if(k==='followups')return {id,user_id:userId,client_id:o.client_id||null,Τίτλος:o.title,follow_up_date:o.date,follow_up_time:o.time||null,Κατάσταση:o.status||null,Σημειώσεις:o.notes||null,reminder_minutes:Number(o.reminder_minutes||0)};
 if(k==='orders')return {id,user_id:userId,client_id:o.client_id||null,order_date:o.date,product_name:o.product,Ποσότητα:Number(o.quantity||0),unit_price:o.unit_price===''?null:Number(o.unit_price),total_amount:o.total===''?null:Number(o.total),Κατάσταση:o.status||null,Σημειώσεις:o.notes||null};
 if(k==='finance')return {id,user_id:userId,transaction_type:o.type,Ποσό:Number(o.amount||0),transaction_date:o.date,Κατηγορία:o.category||null,Περιγραφή:o.description||null,client_id:o.client_id||null};
 if(k==='tasks')return {id,user_id:userId,Τίτλος:o.title,Περιγραφή:o.description||null,task_date:o.date,start_time:o.start_time||null,end_time:o.end_time||null,ολοκληρώθηκε:!!o.completed,reminder_minutes:Number(o.reminder_minutes||0),Προτεραιότητα:o.priority||null};
 if(k==='reminders')return {id,user_id:userId,Τίτλος:o.title,reminder_date:o.date,reminder_time:o.time||null,reminder_minutes:Number(o.reminder_minutes||0),related_type:o.related_type||null,related_id:o.related_id||null,ολοκληρώθηκε:!!o.completed,Σημειώσεις:o.notes||null};
 if(k==='success')return {id,user_id:userId,success_date:o.date,Εργασία:o.task,ολοκληρώθηκε:!!o.completed,Σημειώσεις:o.notes||null};
 return {id,user_id:userId,Τίτλος:o.title,file_name:o.file_name||null,file_path:o.file_path||null,file_type:o.file_type||null,file_size:o.file_size?Number(o.file_size):null,related_type:o.related_type||null,related_id:o.related_id||null};}
async function add(k,o){const row=normalize(k,{id:uid(),...o});state[k].unshift(row);save();render();if(cloud){const {error}=await db.from(tables[k]).insert(dbRow(k,row));if(error)console.warn(error)}}
async function edit(k,id,o){state[k]=state[k].map(x=>x.id===id?normalize(k,{...x,...o}):x);save();render();if(cloud){const {error}=await db.from(tables[k]).update(dbRow(k,state[k].find(x=>x.id===id))).eq('id',id).eq('user_id',userId);if(error)console.warn(error)}}
async function del(k,id){state[k]=state[k].filter(x=>x.id!==id);save();render();if(cloud)await db.from(tables[k]).delete().eq('id',id).eq('user_id',userId)}
function actions(k,id){return `<span class="actions"><button class="small" data-edit="${k}|${id}">✏️ Επεξεργασία</button><button class="small danger" data-del="${k}|${id}">🗑️ Διαγραφή</button></span>`}
function layout(title,sub,body,newAction){return `<section>${title?`<div class="row"><div><h1>${title}</h1><p>${sub||''}</p></div>${newAction?`<button class="primary" data-new="${newAction}">＋ Νέο</button>`:''}</div>`:''}${body}</section>`}
function form(k,id=''){const x=id?state[k].find(a=>a.id===id)||{}:{};const inp=(label,name,type='text',val='',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(val)}" ${extra}></label>`;let h=`<form class="modal-form" data-form="${k}" data-id="${id}">`;
 if(k==='clients')h+=inp('Ονοματεπώνυμο','name','text',x.name,'required')+inp('Τηλέφωνο','phone','tel',x.phone)+inp('Email','email','email',x.email)+inp('Ημερομηνία γέννησης','birth_date','date',x.birth_date)+inp('Διεύθυνση','address','text',x.address)+inp('Κατάσταση','status','text',x.status)+`<label>Σημειώσεις<textarea name="notes">${esc(x.notes)}</textarea></label>`;
 if(k==='appointments')h+=`<label>Ονοματεπώνυμο πελάτη<select name="client_id" required>${opts(x.client_id)}</select></label>`+inp('Τίτλος','title','text',x.title||'Ραντεβού','required')+inp('Ημερομηνία','date','date',x.date||today(),'required')+inp('Ώρα έναρξης (24ωρη)','start_time','time',fmtTime(x.start_time),'required')+inp('Ώρα λήξης (24ωρη)','end_time','time',fmtTime(x.end_time))+inp('Τύπος','type','text',x.type)+inp('Κατάσταση','status','text',x.status)+inp('Υπενθύμιση λεπτά πριν','reminder_minutes','number',x.reminder_minutes||0)+`<label>Σημειώσεις<textarea name="notes">${esc(x.notes)}</textarea></label>`;
 if(k==='partners')h+=inp('Ονοματεπώνυμο','name','text',x.name,'required')+inp('Τηλέφωνο','phone','tel',x.phone)+inp('Email','email','email',x.email)+inp('Επιχείρηση','business','text',x.business)+inp('Κατάσταση','status','text',x.status)+`<label>Σημειώσεις<textarea name="notes">${esc(x.notes)}</textarea></label>`;
 if(k==='measurements')h+=`<label>Πελάτης<select name="client_id">${opts(x.client_id)}</select></label>`+inp('Ημερομηνία','date','date',x.date||today(),'required')+inp('Βάρος','weight','number',x.weight,'step="0.1"')+inp('Σωματικό λίπος %','fat','number',x.fat,'step="0.1"')+inp('Μυϊκή μάζα','muscle','number',x.muscle,'step="0.1"')+inp('Νερό %','water','number',x.water,'step="0.1"')+inp('Οστική μάζα','bone','number',x.bone,'step="0.1"')+inp('Σπλαχνικό λίπος','visceral','number',x.visceral,'step="0.1"')+inp('Θερμίδες','calories','number',x.calories)+inp('Μεταβολική ηλικία','metabolic_age','number',x.metabolic_age)+inp('Fitness score','fitness_score','number',x.fitness_score)+`<label>Σημειώσεις<textarea name="notes">${esc(x.notes)}</textarea></label>`;
 if(k==='programs')h+=`<label>Πελάτης<select name="client_id">${opts(x.client_id)}</select></label>`+inp('Τίτλος','title','text',x.title,'required')+inp('Έναρξη','start_date','date',x.start_date)+inp('Λήξη','end_date','date',x.end_date)+inp('Θερμίδες','calories','number',x.calories)+inp('Πρωτεΐνη g','protein','number',x.protein)+inp('Κατάσταση','status','text',x.status)+`<label>Περιγραφή<textarea name="description">${esc(x.description)}</textarea></label><label>Σημειώσεις<textarea name="notes">${esc(x.notes)}</textarea></label>`;
 if(k==='followups')h+=`<label>Πελάτης<select name="client_id">${opts(x.client_id)}</select></label>`+inp('Τίτλος','title','text',x.title,'required')+inp('Ημερομηνία','date','date',x.date||today(),'required')+inp('Ώρα (24ωρη)','time','time',fmtTime(x.time))+inp('Κατάσταση','status','text',x.status)+inp('Υπενθύμιση λεπτά πριν','reminder_minutes','number',x.reminder_minutes||0)+`<label>Σημειώσεις<textarea name="notes">${esc(x.notes)}</textarea></label>`;
 if(k==='orders')h+=`<label>Πελάτης<select name="client_id">${opts(x.client_id)}</select></label>`+inp('Ημερομηνία','date','date',x.date||today())+inp('Προϊόν','product','text',x.product,'required')+inp('Ποσότητα','quantity','number',x.quantity||1)+inp('Τιμή μονάδας','unit_price','number',x.unit_price,'step="0.01"')+inp('Σύνολο','total','number',x.total,'step="0.01"')+inp('Κατάσταση','status','text',x.status)+`<label>Σημειώσεις<textarea name="notes">${esc(x.notes)}</textarea></label>`;
 if(k==='finance')h+=`<label>Τύπος<select name="type"><option value="income" ${x.type==='income'?'selected':''}>Έσοδο</option><option value="expense" ${x.type==='expense'?'selected':''}>Έξοδο</option></select></label>`+inp('Ποσό','amount','number',x.amount,'step="0.01" required')+inp('Ημερομηνία','date','date',x.date||today())+inp('Κατηγορία','category','text',x.category)+inp('Περιγραφή','description','text',x.description)+`<label>Πελάτης<select name="client_id">${opts(x.client_id)}</select></label>`;
 if(k==='tasks')h+=inp('Εργασία','title','text',x.title,'required')+inp('Ημερομηνία','date','date',x.date||today())+inp('Ώρα έναρξης 24ωρη','start_time','time',fmtTime(x.start_time))+inp('Ώρα λήξης 24ωρη','end_time','time',fmtTime(x.end_time))+inp('Προτεραιότητα','priority','text',x.priority)+`<label>Περιγραφή<textarea name="description">${esc(x.description)}</textarea></label>`;
 if(k==='reminders')h+=inp('Τίτλος','title','text',x.title,'required')+inp('Ημερομηνία','date','date',x.date||today())+inp('Ώρα 24ωρη','time','time',fmtTime(x.time))+inp('Υπενθύμιση λεπτά πριν','reminder_minutes','number',x.reminder_minutes||0)+`<label>Σημειώσεις<textarea name="notes">${esc(x.notes)}</textarea></label>`;
 if(k==='success')h+=inp('Εργασία','task','text',x.task,'required')+inp('Ημερομηνία','date','date',x.date||today())+`<label>Σημειώσεις<textarea name="notes">${esc(x.notes)}</textarea></label>`;
 return h+`<div class="modal-actions"><button type="button" data-close>Ακύρωση</button><button class="primary" type="submit">💾 Αποθήκευση</button></div></form>`}
function list(k,rows,cols){return `<div class="cards">${rows.length?rows.map(x=>`<article class="card">${cols.map(c=>`<div><small>${c[0]}</small><strong>${esc(typeof c[1]==='function'?c[1](x):x[c[1]])}</strong></div>`).join('')}${actions(k,x.id)}</article>`).join(''):`<div class="empty">Δεν υπάρχουν καταχωρίσεις.</div>`}</div>`}
function render(){let body='';
 if(current==='dashboard'){const inc=state.finance.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount||0),0),exp=state.finance.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount||0),0);body=layout('Καλώς ήρθες, Nikoleta ✨','Το προσωπικό σου Wellness CEO',`<div class="stats"><div>👥 Πελάτες<strong>${state.clients.length}</strong></div><div>📅 Ραντεβού σήμερα<strong>${state.appointments.filter(x=>x.date===today()).length}</strong></div><div>📞 Follow-ups<strong>${state.followups.filter(x=>x.status!=='ολοκληρώθηκε').length}</strong></div><div>💰 Καθαρό<strong>${money(inc-exp)}</strong></div></div><div class="quick"><button data-new="clients">＋ Νέος πελάτης</button><button data-new="appointments">📅 Ραντεβού</button><button data-new="programs">🥤 Πρόγραμμα</button><button data-new="tasks">📝 Εργασία</button><button data-new="reminders">🔔 Υπενθύμιση</button></div>`)}
 if(current==='appointments')body=layout('📅 Ραντεβού','Ημερολόγιο συναντήσεων',`<div class="cards">${state.appointments.length?state.appointments.map(x=>`<article class="card appointment"><div><small>ΟΝΟΜΑΤΕΠΩΝΥΜΟ</small><strong>${esc(clientName(x.client_id))}</strong></div><div><small>ΗΜΕΡΟΜΗΝΙΑ</small><strong>${fmtDate(x.date)}</strong></div><div><small>ΩΡΑ</small><strong>${fmtTime(x.start_time)}${x.end_time?' – '+fmtTime(x.end_time):''}</strong></div><div><small>ΤΙΤΛΟΣ</small><strong>${esc(x.title)}</strong></div><div><small>ΤΥΠΟΣ</small><strong>${esc(x.type||'—')}</strong></div><div><small>ΣΗΜΕΙΩΣΕΙΣ</small><strong>${esc(x.notes||'—')}</strong></div>${actions('appointments',x.id)}</article>`).join(''):`<div class="empty">Δεν υπάρχουν ραντεβού.</div>`}</div>`,'appointments');
 if(current==='clients')body=layout('👥 Πελάτες','Προσωπικές καρτέλες πελατών',list('clients',state.clients,[['Ονοματεπώνυμο',x=>x.name],['Τηλέφωνο',x=>x.phone||'—'],['Email',x=>x.email||'—'],['Κατάσταση',x=>x.status||'—']]),'clients');
 if(current==='partners')body=layout('🤝 Συνεργάτες','Συνεργασίες και επαφές',list('partners',state.partners,[['Ονοματεπώνυμο',x=>x.name],['Επιχείρηση',x=>x.business||'—'],['Τηλέφωνο',x=>x.phone||'—']]),'partners');
 if(current==='measurements')body=layout('⚖️ Tanita','Μετρήσεις σώματος',list('measurements',state.measurements,[['Πελάτης',x=>clientName(x.client_id)],['Ημερομηνία',x=>fmtDate(x.date)],['Βάρος',x=>x.weight?x.weight+' kg':'—'],['Λίπος',x=>x.fat?x.fat+' %':'—'],['Μύες',x=>x.muscle||'—']]),'measurements');
 if(current==='programs')body=layout('🥤 Προγράμματα','Προγράμματα ευεξίας',list('programs',state.programs,[['Πελάτης',x=>clientName(x.client_id)],['Τίτλος',x=>x.title],['Θερμίδες',x=>x.calories||'—'],['Πρωτεΐνη',x=>x.protein?x.protein+' g':'—'],['Κατάσταση',x=>x.status||'—']]),'programs');
 if(current==='followups')body=layout('📞 Follow-ups','Επικοινωνίες που πρέπει να γίνουν',list('followups',state.followups,[['Πελάτης',x=>clientName(x.client_id)],['Τίτλος',x=>x.title],['Ημερομηνία',x=>fmtDate(x.date)],['Ώρα',x=>fmtTime(x.time)],['Κατάσταση',x=>x.status||'—']]),'followups');
 if(current==='orders')body=layout('📦 Παραγγελίες','Προϊόντα και παραγγελίες',list('orders',state.orders,[['Πελάτης',x=>clientName(x.client_id)],['Προϊόν',x=>x.product],['Ποσότητα',x=>x.quantity],['Σύνολο',x=>x.total?money(x.total):'—'],['Κατάσταση',x=>x.status||'—']]),'orders');
 if(current==='finance')body=layout('💰 Οικονομικά','Έσοδα και έξοδα',list('finance',state.finance,[['Τύπος',x=>x.type==='income'?'Έσοδο':'Έξοδο'],['Ποσό',x=>money(x.amount)],['Ημερομηνία',x=>fmtDate(x.date)],['Κατηγορία',x=>x.category||'—'],['Περιγραφή',x=>x.description||'—']]),'finance');
 if(current==='tasks')body=layout('📝 Planner','Καθημερινές εργασίες',list('tasks',state.tasks,[['Εργασία',x=>x.title],['Ημερομηνία',x=>fmtDate(x.date)],['Ώρα',x=>fmtTime(x.start_time)],['Ολοκληρώθηκε',x=>x.completed?'Ναι':'Όχι']]),'tasks');
 if(current==='reminders')body=layout('🔔 Υπενθυμίσεις','Υπενθυμίσεις και ειδοποιήσεις',list('reminders',state.reminders,[['Τίτλος',x=>x.title],['Ημερομηνία',x=>fmtDate(x.date)],['Ώρα',x=>fmtTime(x.time)],['Ολοκληρώθηκε',x=>x.completed?'Ναι':'Όχι']]),'reminders');
 if(current==='success')body=layout('🏆 Daily Success','Οι καθημερινές νίκες σου',list('success',state.success,[['Εργασία',x=>x.task],['Ημερομηνία',x=>fmtDate(x.date)],['Ολοκληρώθηκε',x=>x.completed?'Ναι':'Όχι']]),'success');
 if(current==='documents')body=layout('📁 Έγγραφα','Εδώ εμφανίζονται και ανοίγουν τα PDF που είναι αποθηκευμένα στο Supabase.',`<div class="upload"><input id="pdfFile" type="file" accept="application/pdf"><button class="primary" id="uploadPdf">📤 Ανέβασε PDF</button></div><div class="cards">${state.documents.length?state.documents.map(x=>`<article class="card"><div><small>ΑΡΧΕΙΟ</small><strong>${esc(x.file_name||x.title)}</strong></div><div><small>ΤΥΠΟΣ</small><strong>${esc(x.file_type||'PDF')}</strong></div><div class="doc-actions"><button class="small" data-open-pdf="${esc(x.id)}">👁️ Άνοιγμα PDF</button>${actions('documents',x.id)}</div></article>`).join(''):`<div class="empty">Δεν υπάρχουν αποθηκευμένα έγγραφα.</div>`}</div>`);
 $('#app').innerHTML=body;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===current));}
function openModal(html){const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-box"><button class="modal-x" data-close>×</button>${html}</div>`;document.body.appendChild(m)}
async function openPdf(id){const d=state.documents.find(x=>x.id===id);if(!d)return;if(/^https?:\/\//.test(d.file_path)){window.open(d.file_path,'_blank');return}const paths=[d.file_path,d.file_name].filter(Boolean);for(const bucket of ['documents','pdfs','files']){for(const p of paths){try{const r=await db.storage.from(bucket).createSignedUrl(p,3600);if(r.data?.signedUrl){window.open(r.data.signedUrl,'_blank');return}}catch(e){}}}alert('Δεν βρέθηκε το PDF στο Storage. Το αρχείο υπάρχει στη βάση ως καταχώριση, αλλά χρειάζεται σωστό file_path/bucket.')}
async function uploadPdf(){const f=$('#pdfFile')?.files?.[0];if(!f)return alert('Διάλεξε πρώτα PDF.');if(f.type!=='application/pdf')return alert('Διάλεξε αρχείο PDF.');if(!cloud)return alert('Η σύνδεση με Supabase δεν είναι ενεργή.');const path=`${userId}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let uploaded=false;for(const bucket of ['documents','pdfs','files']){try{const r=await db.storage.from(bucket).upload(path,f,{contentType:'application/pdf',upsert:false});if(!r.error){await add('documents',{title:f.name,file_name:f.name,file_path:path,file_type:'application/pdf',file_size:f.size});uploaded=true;break}}catch(e){}}if(!uploaded)alert('Δεν βρέθηκε διαθέσιμο bucket για PDF στο Supabase. Αν έχεις δημιουργήσει bucket, δώσε του όνομα documents.')}
document.addEventListener('click',async e=>{const n=e.target.closest('[data-view]');if(n){current=n.dataset.view;render();return}const nw=e.target.closest('[data-new]');if(nw){openModal(form(nw.dataset.new));return}const ed=e.target.closest('[data-edit]');if(ed){const [k,id]=ed.dataset.edit.split('|');openModal(form(k,id));return}const de=e.target.closest('[data-del]');if(de){const [k,id]=de.dataset.del.split('|');if(confirm('Να διαγραφεί αυτή η καταχώριση;'))await del(k,id);return}if(e.target.closest('[data-close]')){e.target.closest('.modal')?.remove();return}const pdf=e.target.closest('[data-open-pdf]');if(pdf){await openPdf(pdf.dataset.openPdf);return}if(e.target.id==='uploadPdf')await uploadPdf()});
document.addEventListener('submit',async e=>{const f=e.target.closest('[data-form]');if(!f)return;e.preventDefault();const k=f.dataset.form,id=f.dataset.id||'';const o=Object.fromEntries(new FormData(f).entries());if(k==='tasks'||k==='reminders'||k==='success')o.completed=false;if(k==='orders'&&o.total==='')o.total=Number(o.quantity||0)*Number(o.unit_price||0);if(id)await edit(k,id,o);else await add(k,o);f.closest('.modal')?.remove()});
(async()=>{await login();await load();render()})();
