(()=>{
  const DB_URL='https://vbkuvexyqehmpeeejqbh.supabase.co';
  const DB_KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
  const APP_URL='https://nikolp2022.github.io/nikoleta-wellness-ceo/';
  const getDb=()=>window.supabase?.createClient?.(DB_URL,DB_KEY);
  const msg=t=>{const el=document.querySelector('#am');if(el){el.textContent=t;el.style.display='block'}};
  const fields=()=>({email:document.querySelector('#ae')?.value.trim()||'',password:document.querySelector('#ap')?.value||''});
  const ensureButton=()=>{const box=document.querySelector('#auth .modal-actions');if(box&&!box.parentElement.querySelector('[data-auth="forgot"]'))box.insertAdjacentHTML('afterend','<button type="button" class="link-button" data-auth="forgot">🔑 Ξέχασα τον κωδικό μου</button>')};
  const paint=async()=>{const db=getDb();if(!db)return;const {data}=await db.auth.getSession();const u=data?.session?.user||null;document.querySelectorAll('.account-btn').forEach(b=>{b.textContent=u?'☁️ Συνδεδεμένη':'☁️ Σύνδεση';b.classList.toggle('connected',!!u);b.title=u?(u.email||'Συνδεδεμένη'):'Σύνδεση'});document.querySelectorAll('.sync-badge').forEach(b=>{if(u){b.className='sync-badge ok';b.textContent=navigator.onLine?'☁️ Συγχρονισμένο':'📴 Offline — αποθηκεύεται'}});return u};
  async function handle(mode){const db=getDb();if(!db){msg('❌ Δεν φορτώθηκε η σύνδεση.');return}const {email,password}=fields();if(!email){msg('⚠️ Γράψε πρώτα το email σου.');return}if((mode==='signup'||mode==='login')&&password.length<6){msg('⚠️ Ο κωδικός πρέπει να έχει τουλάχιστον 6 χαρακτήρες.');return}if(mode==='forgot'){msg('⏳ Στέλνω email…');const r=await db.auth.resetPasswordForEmail(email,{redirectTo:APP_URL+'?password-reset=1'});msg(r.error?'❌ '+r.error.message:'✅ Έστειλα email. Πάτησε Reset password.');return}msg('⏳ Γίνεται σύνδεση…');let r;if(mode==='magic')r=await db.auth.signInWithOtp({email,options:{emailRedirectTo:APP_URL,shouldCreateUser:true}});else if(mode==='signup')r=await db.auth.signUp({email,password,options:{emailRedirectTo:APP_URL}});else r=await db.auth.signInWithPassword({email,password});if(r.error){msg('❌ '+r.error.message);return}if(mode==='magic'){msg('✅ Έλεγξε το email σου.');return}if(mode==='signup'&&!r.data?.session){msg('✅ Έλεγξε το email σου για επιβεβαίωση.');return}await paint();window.dispatchEvent(new CustomEvent('nwceo-auth-ready',{detail:r.data?.session}));document.querySelector('#auth')?.remove();if(typeof window.render==='function')window.render()}
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-auth]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();handle(b.dataset.auth)},true);
  document.addEventListener('click',e=>{const b=e.target.closest?.('.account-btn');if(!b)return;if(!document.querySelector('#auth')&&typeof window.openAuth==='function'){e.preventDefault();window.openAuth();setTimeout(ensureButton,0)}},true);
  new MutationObserver(()=>{if(document.querySelector('#auth'))ensureButton();paint()}).observe(document.body,{childList:true,subtree:true});
  if(window.supabase){const db=getDb();db?.auth.onAuthStateChange(()=>setTimeout(paint,0))}window.addEventListener('focus',paint);window.addEventListener('pageshow',paint);window.addEventListener('online',paint);paint();
})();