(()=>{
'use strict';
if(window.__NWCEO_CLIENTS254)return;window.__NWCEO_CLIENTS254=true;
const URL='https://vbkuvexyqehmpeeejqbh.supabase.co',KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCxH_Gk';
const sb=window.supabase?.createClient(URL,KEY);if(!sb)return;
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const uid=async()=>((await sb.auth.getUser()).data?.user||null);
const idFrom=()=>location.hash.startsWith('#client/')?decodeURIComponent(location.hash.slice(8).split('/')[0]):'';
const sectionFrom=()=>location.hash.startsWith('#client/')?decodeURIComponent(location.hash.slice(8).split('/')[1]||'home'):'home';
const app=()=>document.querySelector('#app');
const go=h=>{if(location.hash!==h)location.hash=h;else window.dispatchEvent(new HashChangeEvent('hashchange'))};
const css=document.createElement('style');css.textContent=`
.nw254{padding:18px 0 80px}.nw254-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.nw254 h1,.nw254 h2{color:#245b2b;margin:0}.nw254-sub{color:#667085;margin-top:5px}.nw254-tools{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.nw254 input,.nw254 textarea,.nw254 select{width:100%;box-sizing:border-box;padding:11px;border:1px solid #ccd6cc;border-radius:10px;font:inherit;background:#fff;color:#182018}.nw254-search{max-width:520px}.nw254-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:13px}.nw254-card{background:linear-gradient(145deg,#fffdf8,#f8fbf7);border:1px solid #dfe8df;border-radius:19px;padding:15px;box-shadow:0 8px 25px #173b1910}.nw254-card:hover{box-shadow:0 12px 32px #173b1920}.nw254-profile{display:flex;gap:12px;align-items:center}.nw254-avatar{width:64px;height:64px;border-radius:17px;background:#edf6ee;border:1px solid #d7e5d7;display:grid;place-items:center;color:#245b2b;font-weight:900;font-size:25px;object-fit:cover;flex:none}.nw254-card b{color:#245b2b}.nw254-muted{color:#667085;font-size:13px}.nw254-chip{display:inline-block;padding:5px 9px;border-radius:999px;background:#edf6ee;color:#245b2b;font-size:11px;font-weight:900;margin:3px 3px 0 0}.nw254-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.nw254 button{border:1px solid #d5ddd5;background:#fff;border-radius:10px;padding:9px 12px;font:inherit;font-weight:800;color:#245b2b;cursor:pointer}.nw254 .primary{background:#245b2b;color:#fff;border-color:#245b2b}.nw254 .danger{color:#a40000;border-color:#e4caca}.nw254-modal{position:fixed;inset:0;z-index:900000;background:#0008;display:grid;place-items:center;padding:14px}.nw254-box{width:min(820px,96vw);max-height:93vh;overflow:auto;background:#fffdf8;border-radius:22px;padding:18px;box-shadow:0 25px 90px #0008}.nw254-form{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.nw254-field{display:flex;flex-direction:column;gap:5px;font-weight:800;color:#344054}.nw254-full{grid-column:1/-1}.nw254-foot{display:flex;justify-content:flex-end;gap:8px;grid-column:1/-1}.nw254-banner{background:linear-gradient(135deg,#f1f8f1,#fffdf8);border:1px solid #dfe8df;border-radius:20px;padding:16px;margin-bottom:14px}.nw254-sections{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:12px}.nw254-section{background:#fff;border:1px solid #dfe8df;border-radius:17px;padding:14px}.nw254-section h3{margin:0 0 5px;color:#245b2b}.nw254-row{padding:9px 0;border-bottom:1px solid #edf0ed}.nw254-row:last-child{border-bottom:0}.nw254-error{background:#fff2f2;border:1px solid #eccaca;color:#a40000;padding:10px;border-radius:10px;margin-top:10px}.nw254-ok{background:#f1f8f1;border:1px solid #d2e3d2;color:#245b2b;padding:10px;border-radius:10px;margin-top:10px}@media(max-width:650px){.nw254-form{grid-template-columns:1fr}.nw254-full,.nw254-foot{grid-column:1}.nw254-grid{grid-template-columns:1fr}}
`;document.head.appendChild(css);
function modal(title,html,save){const m=document.createElement('div');m.className='nw254-modal';m.innerHTML=`<div class="nw254-box"><div style="display:flex;justify-content:space-between;align-items:center"><h2>${title}</h2><button type="button" data-close>×</button></div><form class="nw254-form">${html}<div class="nw254-foot"><button type="button" data-close>Άκυρο</button><button class="primary" type="submit">Αποθήκευση</button></div></form></div>`;document.body.appendChild(m);m.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>m.remove());m.querySelector('form').onsubmit=e=>{e.preventDefault();save(new FormData(e.target),m)};return m}
const fld=(n,l,t,v='',full=false,req='')=>`<label class="nw254-field ${full?'nw254-full':''}"><span>${l}</span><input name="${n}" type="${t}" value="${esc(v)}" ${req}></label>`;
const ta=(n,l,v='')=>`<label class="nw254-field nw254-full"><span>${l}</span><textarea name="${n}">${esc(v)}</textarea></label>`;
const sel=(n,l,v,opts)=>`<label class="nw254-field"><span>${l}</span><select name="${n}">${opts.map(([a,b])=>`<option value="${a}" ${String(v||'')===a?'selected':''}>${b}</option>`).join('')}</select></label>`;
async function client(id){const u=await uid();if(!u)return null;const r=await sb.from('clients').select('*').eq('id',id).eq('user_id',u.id).maybeSingle();return r.data||null}
async function list(){const u=await uid();if(!u)return {data:[],error:{message:'Δεν υπάρχει ενεργή σύνδεση.'}};return await sb.from('clients').select('*').eq('user_id',u.id).order('name',{ascending:true})}
function clientModal(existing){const c=existing||{};return modal(existing?'✏️ Επεξεργασία πελάτη':'👤 Νέος πελάτης',fld('name','Όνομα *','text',c.name||'',false,'required')+fld('phone','Τηλέφωνο','tel',c.phone||'')+fld('email','Email','email',c.email||'')+fld('address','Διεύθυνση','text',c.address||'')+fld('area','Περιοχή','text',c.area||'')+fld('birth_date','Ημερομηνία γέννησης','date',c.birth_date||'')+fld('start_date','Ημερομηνία έναρξης','date',c.start_date||'')+fld('goal','Στόχος','text',c.goal||'')+fld('photo_url','URL φωτογραφίας','url',c.photo_url||'',true)+sel('status','Κατάσταση',c.status||'active',[['active','Ενεργός'],['inactive','Ανενεργός'],['lead','Υποψήφιος'],['paused','Σε παύση']])+ta('notes','Σημειώσεις',c.notes||''),async(fd,m)=>{const u=await uid();if(!u){alert('Δεν υπάρχει ενεργή σύνδεση.');return}const p={user_id:u.id,name:String(fd.get('name')||'').trim(),phone:String(fd.get('phone')||'').trim()||null,email:String(fd.get('email')||'').trim()||null,address:String(fd.get('address')||'').trim()||null,area:String(fd.get('area')||'').trim()||null,birth_date:fd.get('birth_date')||null,start_date:fd.get('start_date')||null,goal:String(fd.get('goal')||'').trim()||null,photo_url:String(fd.get('photo_url')||'').trim()||null,status:fd.get('status')||'active',notes:String(fd.get('notes')||'').trim()||null,updated_at:new Date().toISOString()};if(!p.name){alert('Γράψε το όνομα του πελάτη.');return}let r=existing?await sb.from('clients').update(p).eq('id',existing.id).eq('user_id',u.id):await sb.from('clients').insert(p).select();if(r.error){m.querySelector('.nw254-error')?.remove();m.querySelector('form').insertAdjacentHTML('afterbegin',`<div class="nw254-error">Δεν αποθηκεύτηκε: ${esc(r.error.message)}</div>`);return}m.remove();go('#clients')}})}
async function renderClients(){const h=app();if(!h)return;const r=await list();if(r.error){h.innerHTML=`<section class="nw254"><div class="nw254-banner"><h1>👥 Πελάτες</h1><p class="nw254-error">${esc(r.error.message)}</p></div></section>`;return}const rows=r.data||[];h.innerHTML=`<section class="nw254"><div class="nw254-head"><div><h1>👥 Πελάτες</h1><div class="nw254-sub">Το κεντρικό σου CRM — κάθε πελάτης με δικό του ψηφιακό φάκελο.</div></div><button class="primary" id="nw254-new">＋ Νέος πελάτης</button></div><div class="nw254-tools"><input id="nw254-search" class="nw254-search" placeholder="🔎 Αναζήτηση ονόματος, τηλεφώνου ή email..."></div><div id="nw254-list" class="nw254-grid"></div></section>`;const paint=filter=>{const q=filter.toLowerCase();const arr=rows.filter(c=>[c.name,c.phone,c.email,c.area,c.goal].some(v=>String(v||'').toLowerCase().includes(q)));const box=document.querySelector('#nw254-list');box.innerHTML=arr.length?arr.map(c=>`<article class="nw254-card"><div class="nw254-profile">${c.photo_url?`<img class="nw254-avatar" src="${esc(c.photo_url)}" alt="">`:'<div class="nw254-avatar">👤</div>'}<div><b>${esc(c.name)}</b><div class="nw254-muted">${esc(c.phone||c.email||c.area||'Πλήρης ψηφιακός φάκελος')}</div></div></div><div style="margin-top:9px"><span class="nw254-chip">${esc(c.status||'active')}</span>${c.goal?`<span class="nw254-chip">🎯 ${esc(c.goal)}</span>`:''}</div><div class="nw254-actions"><button class="primary" data-open="${c.id}">📁 Άνοιγμα φακέλου</button><button data-edit="${c.id}">✏️ Επεξεργασία</button><button class="danger" data-del="${c.id}">🗑️ Διαγραφή</button></div></article>`).join(''):'<div class="nw254-card">Δεν υπάρχει πελάτης ακόμη.</div>';box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>go('#client/'+encodeURIComponent(b.dataset.open)));box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{const c=await client(b.dataset.edit);if(c)clientModal(c)});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{const c=await client(b.dataset.del);if(!c||!confirm(`Να διαγραφεί ο πελάτης «${c.name}»;`))return;const u=await uid();const x=await sb.from('clients').delete().eq('id',c.id).eq('user_id',u.id);if(x.error)alert('Δεν διαγράφηκε: '+x.error.message);else renderClients()})};paint('');document.querySelector('#nw254-search').oninput=e=>paint(e.target.value);document.querySelector('#nw254-new').onclick=()=>clientModal()}
const related={appointments:['appointments','📅 Ραντεβού','appointment_date'],tanita_measurements:['tanita_measurements','⚖️ Tanita','measurement_date'],programs:['programs','🥤 Διατροφικά προγράμματα','start_date'],follow_ups:['follow_ups','📞 Follow-ups','follow_up_date'],orders:['orders','🛒 Παραγγελίες','order_date'],finance_transactions:['finance_transactions','💰 Οικονομικά','transaction_date'],communication_history:['communication_history','💬 Επικοινωνίες','communication_date'],documents:['documents','📄 Έγγραφα','created_at'],client_trainings:['client_trainings','🎓 Εκπαιδεύσεις','training_date'],wellness_touch_points:['wellness_touch_points','🌿 Wellness Touch Point','check_in_at']};
async function relatedCount(table,id){const u=await uid();if(!u)return 0;let q=sb.from(table).select('id',{count:'exact',head:true}).eq('user_id',u.id);q=table==='documents'?q.eq('related_type','client').eq('related_id',id):q.eq('client_id',id);const r=await q;return r.count||0}
async function renderFolder(){const id=idFrom();const c=await client(id);if(!c){go('#clients');return}const h=app();const counts=await Promise.all(Object.entries(related).map(async([k,v])=>[k,await relatedCount(v[0],id)]));const cm=new Map(counts);h.innerHTML=`<section class="nw254"><div class="nw254-head"><div><button id="nw254-back">← Πελάτες</button><h1 style="margin-top:10px">📁 ${esc(c.name)}</h1><div class="nw254-sub">Πλήρης ψηφιακός φάκελος πελάτη</div></div><button class="primary" id="nw254-edit">✏️ Επεξεργασία</button></div><div class="nw254-banner"><div class="nw254-profile">${c.photo_url?`<img class="nw254-avatar" src="${esc(c.photo_url)}">`:'<div class="nw254-avatar">👤</div>'}<div><b>${esc(c.name)}</b><div class="nw254-muted">${esc(c.phone||'')} ${c.email?' · '+esc(c.email):''}</div><div>${c.area?`<span class="nw254-chip">📍 ${esc(c.area)}</span>`:''}${c.goal?`<span class="nw254-chip">🎯 ${esc(c.goal)}</span>`:''}<span class="nw254-chip">${esc(c.status||'active')}</span></div></div></div></div><div class="nw254-sections">${Object.entries(related).map(([k,v])=>`<article class="nw254-section"><h3>${v[1]}</h3><div class="nw254-muted">Συνδεδεμένα δεδομένα</div><strong>${cm.get(k)||0}</strong><div class="nw254-actions"><button data-section="${k}">Άνοιγμα</button></div></article>`).join('')}</div></section>`;h.querySelector('#nw254-back').onclick=()=>go('#clients');h.querySelector('#nw254-edit').onclick=()=>clientModal(c);h.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{const k=b.dataset.section;if(k==='appointments')go('#appointments');else alert('Η ενότητα '+related[k][1]+' είναι συνδεδεμένη στον φάκελο και θα ενεργοποιηθεί στο επόμενο βήμα της σειράς.')})}
function route(){if(location.hash==='#clients'||location.hash==='#clients/')renderClients();else if(location.hash.startsWith('#client/'))renderFolder()}
const click=e=>{const t=e.target.closest?.('[data-v="clients"],[data-new="clients"],[data-open-client]');if(!t)return;e.preventDefault();e.stopImmediatePropagation();go('#clients')};document.addEventListener('click',click,true);window.addEventListener('hashchange',route);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(route,30));else setTimeout(route,30);
})();
