(()=>{
const KEY='nwceo_notifications_v2',VAPID_PUBLIC_KEY='BBZn_vxGIsg_qTkFK1z-TQyKxgq9A6I7aZf3nVg0533AJ-Q_Bnx-LQ-BSsYhARVluL3smO92amxRgo1_Ypa5I-E',SUPABASE_URL='https://vbkuvexyqehmpeeejqbh.supabase.co';
const parse=(d,t)=>{if(!d)return null;const[a,b,c]=String(d).slice(0,10).split('-').map(Number),[h,m]=String(t||'00:00').slice(0,5).split(':').map(Number),x=new Date(a,b-1,c,h||0,m||0);return isNaN(x)?null:x};
const get=()=>{try{return JSON.parse(localStorage.getItem('nwceo_final_v1')||'{}')}catch(e){return{}}};
const collect=()=>{const d=get(),o=[],add=(a,type,dk,tk)=>{if(!Array.isArray(a))return;a.forEach(x=>{const at=parse(x[dk]||x.date||x.start_date,x[tk]||x.time||x.start_time);if(at&&x.reminder_minutes!=null)o.push({id:String(x.id),at:new Date(at.getTime()-Number(x.reminder_minutes||0)*60000),title:x.title||x.name||x.task||type,body:x.notes||x.description||'',type})})};add(d.appointments,'Ραντεβού','appointment_date','start_time');add(d.followups,'Follow-up','follow_up_date','follow_up_time');add(d.tasks,'Planner','task_date','start_time');if(Array.isArray(d.reminders))d.reminders.forEach(x=>{const at=parse(x.reminder_date||x.date,x.reminder_time||x.time);if(at)o.push({id:String(x.id),at,title:x.title||'Υπενθύμιση',body:x.notes||'',type:'Υπενθύμιση'})});return o};
const sent=new Set(JSON.parse(localStorage.getItem(KEY)||'[]'));
async function notify(title,body,tag){try{if(!('Notification'in window)||Notification.permission!=='granted')return false;const r=await navigator.serviceWorker.ready;if(r.showNotification)await r.showNotification(title,{body,tag,icon:'./icon-192.png',badge:'./icon-192.png',data:{url:'./'}});else new Notification(title,{body,tag});return true}catch(e){return false}}
function b64(s){const p='='.repeat((4-s.length%4)%4),r=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...r],c=>c.charCodeAt(0))}
async function token(){try{if(window.db?.auth?.getSession)return (await window.db.auth.getSession()).data.session?.access_token||null}catch(e){}return null}
async function registerPush(){try{if(!('PushManager'in window)||!('serviceWorker'in navigator))return false;const r=await navigator.serviceWorker.ready;let s=await r.pushManager.getSubscription();if(!s)s=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(VAPID_PUBLIC_KEY)});const t=await token();if(!t)return false;const q=await fetch(SUPABASE_URL+'/functions/v1/register-push',{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({...s.toJSON(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Athens'})});return q.ok}catch(e){console.warn(e);return false}}
async function request(){if(!('Notification'in window))return'unsupported';const p=Notification.permission==='default'?await Notification.requestPermission():Notification.permission;if(p==='granted')await registerPush();return p}
function tick(){const n=Date.now();collect().forEach(x=>{if(x.at.getTime()<=n+30000&&x.at.getTime()>n-90000&&!sent.has(x.id)){notify('Nikoleta Wellness CEO',`${x.title}${x.body?' — '+x.body:''}`,'nwceo-'+x.id);sent.add(x.id)}});localStorage.setItem(KEY,JSON.stringify([...sent].slice(-500)))}
function button(){if(document.querySelector('#enable-notifications')||!('Notification'in window)||Notification.permission==='granted')return;const b=document.createElement('button');b.id='enable-notifications';b.textContent='🔔 Ενεργοποίηση ειδοποιήσεων';b.style.cssText='position:fixed;right:16px;bottom:16px;z-index:9999;border:0;border-radius:999px;padding:12px 18px;background:#245b2b;color:white;font-weight:700;box-shadow:0 8px 24px #0002';b.onclick=async()=>{if((await request())==='granted')b.remove()};document.body.appendChild(b)}
window.NWNotifications={request,refresh:tick,registerPush};window.addEventListener('load',()=>{button();request().catch(()=>{});tick();setInterval(tick,15000)});
})();