(()=>{'use strict';
if(window.__NW602)return;window.__NW602=true;
const URL='https://vbkuvexyqehmpeeejqbh.supabase.co',KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const TABLES={clients:'clients',partners:'partners',followups:'follow_ups',finance:'finance_entries',orders:'orders',documents:'documents',trips:'trips',training:'trainings',inventory:'inventory_products',planner:'planner_tasks',appointments:'appointments',calendar:'calendar_events'};
const LABELS={clients:'👥 Πελάτες',partners:'🤝 Συνεργάτες',followups:'📞 Follow-ups',finance:'💰 Οικονομικά',orders:'🛒 Παραγγελίες',documents:'📄 Έγγραφα',trips:'✈️ Ταξίδια',training:'🎓 Εκπαιδεύσεις',inventory:'📦 Αποθήκη',planner:'✓ Planner',appointments:'📅 Ραντεβού',calendar:'🗓️ Ημερολόγιο'};
let sb,user;
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const time=x=>x?String(x).slice(0,5):'';
const dateField={appointments:'appointment_date',training:'training_date',planner:'task_date',followups:'follow_up_date',calendar:'event_date',trips:'start_date'};
const timeField={appointments:'start_time',training:'start_time',planner:'start_time',followups:'follow_up_time',calendar:'start_time'};
const fields={appointments:[['title','Τίτλος','text'],['client_name','Ονοματεπώνυμο πελάτη','text'],['appointment_date','Ημερομηνία','date'],['start_time','Ώρα έναρξης','time'],['end_time','Ώρα λήξης','time'],['appointment_type','Τύπος','text'],['status','Κατάσταση','text'],['notes','Σημειώσεις','textarea']],clients:[['name','Ονοματεπώνυμο','text'],['phone','Τηλέφωνο','tel'],['email','Email','email'],['address','Διεύθυνση','text'],['birth_date','Ημερομηνία γέννησης','date'],['goal','Στόχος','text'],['start_date','Ημερομηνία έναρξης','date'],['next_measurement_date','Επόμενη μέτρηση','date'],['notes','Σημειώσεις','textarea']],partners:[['name','Ονοματεπώνυμο','text'],['id_number','Προσωπικό ID','text'],['phone','Τηλέφωνο','tel'],['email','Email','email'],['registration_date','Ημερομηνία εγγραφής','date'],['current_rank','Βαθμίδα','text'],['goals','Στόχοι','textarea'],['notes','Σημειώσεις','textarea']],followups:[['title','Τίτλος','text'],['follow_up_date','Ημερομηνία','date'],['follow_up_time','Ώρα','time'],['status','Κατάσταση','text'],['notes','Σημειώσεις','textarea']],finance:[['entry_date','Ημερομηνία','date'],['entry_type','Τύπος','text'],['category','Κατηγορία','text'],['description','Περιγραφή','text'],['amount','Ποσό','number'],['payment_method','Τρόπος πληρωμής','text'],['notes','Σημειώσεις','textarea']],orders:[['order_date','Ημερομηνία','date'],['product_name','Προϊόν','text'],['quantity','Ποσότητα','number'],['unit_price','Τιμή μονάδας','number'],['status','Κατάσταση','text'],['notes','Σημειώσεις','textarea']],documents:[['title','Τίτλος','text'],['file_name','Όνομα αρχείου','text'],['file_type','Τύπος','text'],['related_type','Σχετίζεται με','text'],['file_path','Σύνδεσμος','url']],trips:[['start_date','Έναρξη','date'],['end_date','Λήξη','date'],['destination','Προορισμός','text'],['trip_type','Τύπος ταξιδιού','text'],['duration_days','Ημέρες','number'],['notes','Σημειώσεις','textarea']],training:[['title','Τίτλος','text'],['training_date','Ημερομηνία','date'],['start_time','Ώρα έναρξης','time'],['end_time','Ώρα λήξης','time'],['role','Ρόλος','text'],['description','Περιγραφή','textarea'],['reminder_minutes','Υπενθύμιση λεπτά πριν','number']],inventory:[['product_name','Προϊόν','text'],['sku','SKU','text'],['category','Κατηγορία','text'],['stock','Απόθεμα','number'],['minimum_stock','Ελάχιστο απόθεμα','number'],['unit_cost','Κόστος μονάδας','number'],['unit_price','Τιμή πώλησης','number'],['notes','Σημειώσεις','textarea']],planner:[['title','Εργασία','text'],['description','Περιγραφή','textarea'],['task_date','Ημερομηνία','date'],['start_time','Έναρξη','time'],['end_time','Λήξη','time'],['priority','Προτεραιότητα','text'],['notes','Σημειώσεις','textarea']],calendar:[['title','Τίτλος','text'],['event_type','Τύπος','text'],['event_date','Ημερομηνία','date'],['start_time','Έναρξη','time'],['end_time','Λήξη','time'],['all_day','Ολοήμερο','checkbox'],['notes','Σημειώσεις','textarea']]};
const css=`.nw602-modal{position:fixed;inset:0;background:#10261c99;z-index:99999;display:flex;align-items:center;justify-content:center;padding:14px}.nw602-box{background:#fffdf8;width:min(720px,100%);max-height:94vh;overflow:auto;border-radius:24px;padding:20px;box-shadow:0 20px 60px #0005}.nw602-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.nw602-box label{display:block;font-weight:800;margin:10px 0}.nw602-box input,.nw602-box textarea{width:100%;padding:11px;border:1px solid #d7cebd;border-radius:10px;margin-top:5px;background:#fff}.nw602-box textarea{min-height:110px}.nw602-close{border:0;background:#eee;border-radius:9px;padding:7px 11px}.nw602-save{background:#245b2b;color:#fff;border:0;border-radius:11px;padding:11px 16px;font-weight:800}.nw602-bell{background:#c9a45b!important;color:#fff!important;border:0!important;border-radius:10px!important;padding:9px 12px!important;font-weight:800!important}.nw602-edit{background:#245b2b!important;color:#fff!important;border:0!important;border-radius:10px!important;padding:9px 12px!important;font-weight:800!important}.nw602-sub{display:block;color:#777;font-size:13px;margin-bottom:7px}`;
function addStyle(){if(document.getElementById('nw602style'))return;let s=document.createElement('style');s.id='nw602style';s.textContent=css;document.head.appendChild(s)}
function currentKey(){let h=(location.hash||'').toLowerCase();for(const k in LABELS)if(h.includes(k))return k;return /ραντεβού/.test(document.body.innerText.toLowerCase())?'appointments':null}
async function rows(k){const r=await sb.from(TABLES[k]).select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]}
function title(k,x){return k==='appointments'?(x.client_name||x.title||'Ραντεβού'):x.name||x.title||x.product_name||x.destination||x.file_name||'Καταχώρηση'}
async function clientName(x){if(!x?.client_id)return x?.client_name||'';const r=await sb.from('clients').select('name').eq('id',x.client_id).eq('user_id',user.id).maybeSingle();return r.data?.name||x.client_name||''}
function inputField(n,l,v,t){if(t==='textarea')return `<label>${l}<textarea name="${n}">${esc(v||'')}</textarea></label>`;if(t==='checkbox')return `<label><input style="width:auto" type="checkbox" name="${n}" ${v?'checked':''}> ${l}</label>`;return `<label>${l}<input name="${n}" type="${t}" value="${esc(t==='time'?time(v):v||'')}"></label>`}
async function openEdit(k,id){let all=await rows(k),x=all.find(z=>String(z.id)===String(id))||{};if(k==='appointments'&&!x.client_name)x.client_name=await clientName(x);const fs=fields[k]||[['title','Τίτλος','text'],['notes','Σημειώσεις','textarea']];const m=document.createElement('div');m.className='nw602-modal';m.innerHTML=`<div class="nw602-box"><div class="nw602-head"><h2>✏️ Επεξεργασία — ${esc(LABELS[k])}</h2><button class="nw602-close">×</button></div><p class="nw602-sub">Όλα όσα είχες γράψει φορτώθηκαν για διόρθωση.</p><form>${fs.map(([n,l,t])=>inputField(n,l,x[n],t)).join('')}<button class="nw602-save">💾 Αποθήκευση αλλαγών</button></form></div>`;document.body.appendChild(m);m.querySelector('.nw602-close').onclick=()=>m.remove();m.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),o={};fs.forEach(([n,,t])=>o[n]=t==='checkbox'?fd.get(n)==='on':(fd.get(n)||null));const q=await sb.from(TABLES[k]).update(o).eq('id',x.id).eq('user_id',user.id);if(q.error){alert(q.error.message);return}m.remove();location.hash='#'+k;location.reload()}}
function base64url(v){const b=atob(v.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-v.length%4)%4)),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u}
async function setupPush(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window))return false;const p=await Notification.requestPermission();if(p!=='granted')return false;const reg=await navigator.serviceWorker.register('./sw.js?v=602',{updateViaCache:'none'});await reg.update();const r0=await sb.functions.invoke('register-push',{body:{}});if(r0.error||!r0.data?.publicKey)return false;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64url(r0.data.publicKey)});const s=sub.toJSON();const r=await sb.functions.invoke('register-push',{body:{endpoint:s.endpoint,keys:{p256dh:s.keys?.p256dh,auth:s.keys?.auth}}});if(r.error)throw r.error;await reg.showNotification('🔔 Nikoleta Wellness CEO',{body:'Οι ειδοποιήσεις ενεργοποιήθηκαν.',tag:'nw602-test',renotify:true,requireInteraction:true,silent:false,vibrate:[250,100,250]});return true}
function reminderValue(k,x){const d=x[dateField[k]]||x.order_date||x.entry_date||new Date().toISOString().slice(0,10);const t=x[timeField[k]]||'09:00';return {d,t:String(t).slice(0,5)}}
async function reminder(k,x){try{const ok=await setupPush();if(!ok){alert('Για να λειτουργήσουν οι ειδοποιήσεις, επίτρεψέ τες όταν το Chrome το ζητήσει.');return}const v=reminderValue(k,x),m=document.createElement('div');m.className='nw602-modal';m.innerHTML=`<div class="nw602-box"><div class="nw602-head"><h2>🔔 Υπενθύμιση</h2><button class="nw602-close">×</button></div><p><b>${esc(title(k,x))}</b></p><form><label>Ημερομηνία<input name="d" type="date" value="${v.d}" required></label><label>Ώρα<input name="t" type="time" value="${v.t}" required></label><label>Πόσα λεπτά πριν<input name="m" type="number" min="0" value="30"></label><label>Μήνυμα<textarea name="b">Υπενθύμιση: ${esc(title(k,x))}</textarea></label><button class="nw602-save">🔔 Αποθήκευση υπενθύμισης</button></form></div>`;document.body.appendChild(m);m.querySelector('.nw602-close').onclick=()=>m.remove();m.querySelector('form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),at=new Date(`${fd.get('d')}T${fd.get('t')}:00`);at.setMinutes(at.getMinutes()-Number(fd.get('m')||0));const eventKey=`${k}:${x.id}:${Date.now()}`;let q=await sb.from('scheduled_notifications').insert({user_id:user.id,event_key,notify_at:at.toISOString(),title:'Nikoleta Wellness CEO',body:String(fd.get('b')||''),sent:false});if(q.error){alert(q.error.message);return}q=await sb.from('reminders').insert({user_id:user.id,title:title(k,x),reminder_date:fd.get('d'),reminder_time:fd.get('t'),reminder_minutes:Number(fd.get('m')||0),related_type:k,related_id:x.id,notes:String(fd.get('b')||'')});if(q.error){alert(q.error.message);return}m.remove();alert('🔔 Η υπενθύμιση αποθηκεύτηκε.')};}catch(e){alert('Δεν μπόρεσα να ενεργοποιήσω τις ειδοποιήσεις: '+(e?.message||e))}}
async function decorateAppointments(){if(currentKey()!=='appointments')return;const all=await rows('appointments');const cs=await sb.from('clients').select('id,name').eq('user_id',user.id);const map=new Map((cs.data||[]).map(c=>[String(c.id),c.name]));document.querySelectorAll('.item').forEach(card=>{const b=card.querySelector('b');const btn=card.querySelector('[data-e]');if(!b||!btn)return;const x=all[Number(btn.dataset.e)];if(!x)return;const name=x.client_name||map.get(String(x.client_id))||x.title||'Ραντεβού';b.textContent=name;let sub=card.querySelector('.nw602-sub');if(!sub){sub=document.createElement('span');sub.className='nw602-sub';b.insertAdjacentElement('afterend',sub)}sub.textContent=x.title&&x.title!==name?x.title:''})}
async function enhance(){const k=currentKey();if(!k)return;const all=await rows(k);document.querySelectorAll('.item').forEach(card=>{const editBtn=card.querySelector('[data-e]');if(!editBtn)return;const idx=Number(editBtn.dataset.e),x=all[idx];if(!x)return;const actions=card.querySelector('.actions')||card;if(!actions.querySelector('.nw602-edit')){const e=document.createElement('button');e.className='nw602-edit';e.textContent='✏️ Επεξεργασία';e.onclick=ev=>{ev.preventDefault();ev.stopPropagation();openEdit(k,x.id)};actions.insertBefore(e,actions.firstChild)}if(!actions.querySelector('.nw602-bell')){const b=document.createElement('button');b.className='nw602-bell';b.textContent='🔔 Ειδοποίηση';b.onclick=ev=>{ev.preventDefault();ev.stopPropagation();reminder(k,x)};actions.appendChild(b)}});if(k==='appointments')await decorateAppointments()}
function intercept(){document.addEventListener('click',e=>{const b=e.target.closest('button[data-e]');if(!b)return;const k=currentKey();if(!k)return;e.preventDefault();e.stopImmediatePropagation();const idx=Number(b.dataset.e);rows(k).then(a=>a[idx]&&openEdit(k,a[idx].id)).catch(err=>alert(err.message))},true)}
async function init(){addStyle();const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.0/+esm');sb=m.createClient(URL,KEY);user=(await sb.auth.getUser()).data.user;if(!user)return;if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js?v=602',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{})}intercept();const ob=new MutationObserver(()=>setTimeout(()=>enhance().catch(()=>{}),150));ob.observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(()=>enhance().catch(()=>{}),300));setTimeout(()=>enhance().catch(()=>{}),300)}
init().catch(()=>{});
})();
