(()=>{
'use strict';
if(window.__NWCEO_RECOVERY242)return;
window.__NWCEO_RECOVERY242=true;
const app=document.getElementById('app');
if(!app)return;
const fallback=`<div id="nw242-recovery" style="min-height:100vh;background:#f6f8f4;color:#17351e;font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;padding:18px;box-sizing:border-box"><div style="max-width:760px;margin:0 auto"><div style="background:#fff;border-radius:22px;padding:24px;box-shadow:0 4px 18px #0001"><div style="font-size:12px;letter-spacing:.08em;font-weight:900;color:#6d876f">WELLNESS BUSINESS SYSTEM</div><h1 style="margin:8px 0 4px">Nikoleta Wellness CEO</h1><p style="margin:0;color:#657267">Η εφαρμογή επαναφέρει την ασφαλή αρχική οθόνη. Τα δεδομένα σου δεν διαγράφονται.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px;margin-top:20px"><button data-recover="#" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">🏠 Αρχική</button><button data-recover="#appointments" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">📅 Ραντεβού</button><button data-recover="#clients" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">👥 Πελάτες</button><button data-recover="#partners" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">🤝 Συνεργάτες</button><button data-recover="#followups" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">📞 Follow-ups</button><button data-recover="#orders" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">🛒 Παραγγελίες</button><button data-recover="#finance" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">💰 Οικονομικά</button><button data-recover="#planner" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">📋 Planner</button><button data-recover="#documents" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">📄 Έγγραφα</button><button data-recover="#trips" style="padding:14px;border:1px solid #ccd8cc;border-radius:12px;background:#fff;font-weight:800">✈️ Ταξίδια</button></div><div style="margin-top:18px;padding:12px 14px;border-radius:12px;background:#eef6ec;color:#49614d;font-size:13px">Μόλις ολοκληρωθεί η φόρτωση, η κανονική εφαρμογή θα εμφανιστεί αυτόματα.</div></div></div></div>`;
const show=()=>{if(!document.getElementById('nw242-recovery') && !app.querySelector('header')){app.innerHTML=fallback;app.querySelectorAll('[data-recover]').forEach(b=>b.addEventListener('click',()=>{location.hash=b.dataset.recover.slice(1);setTimeout(()=>location.reload(),50)}));}};
show();
const timer=setInterval(()=>{if(app.querySelector('header')){document.getElementById('nw242-recovery')?.remove();clearInterval(timer)}else show()},500);
setTimeout(()=>clearInterval(timer),30000);
})();
