(()=>{
const URL='https://vbkuvexyqehmpeeejqbh.supabase.co',KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const db=window.__nw_db||window.supabase?.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});if(!db)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const timeToMin=t=>{if(!t)return null;const m=String(t).match(/^(\d{1,2}):(\d{2})$/);return m?(+m[1]*60+ +m[2]):null};
const datesBetween=(a,b)=>{const out=[],d=new Date(a+'T00:00:00'),e=new Date(b+'T00:00:00');while(d<=e){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return out};
async function uid(){return (await db.auth.getSession()).data.session?.user?.id||null}
async function blocks(){const u=await uid();if(!u)return[];const [a,t,f,r,p]=await Promise.all([db.from('appointments').select('id,appointment_date,start_time,end_time,title,notes').eq('user_id',u),db.from('trips').select('id,start_date,end_date,destination,trip_type').eq('user_id',u),db.from('follow_ups').select('id,follow_up_date,follow_up_time,title,notes').eq('user_id',u),db.from('reminders').select('id,reminder_date,reminder_time,title,notes').eq('user_id',u),db.from('planner_tasks').select('id,task_date,start_time,end_time,title,description').eq('user_id',u)]);const out=[];(a.data||[]).forEach(x=>out.push({date:x.appointment_date,start:x.start_time,end:x.end_time,label:'📅 '+(x.title||'Ραντεβού'),notes:x.notes,type:'appointment'}));(f.data||[]).forEach(x=>out.push({date:x.follow_up_date,start:x.follow_up_time,end:x.follow_up_time,label:'📞 '+(x.title||'Follow-up'),notes:x.notes,type:'followup'}));(r.data||[]).forEach(x=>out.push({date:x.reminder_date,start:x.reminder_time,end:x.reminder_time,label:'🔔 '+(x.title||'Υπενθύμιση'),notes:x.notes,type:'reminder'}));(p.data||[]).forEach(x=>out.push({date:x.task_date,start:x.start_time,end:x.end_time,label:'📝 '+(x.title||'Εργασία'),notes:x.description,type:'task'}));(t.data||[]).forEach(x=>datesBetween(x.start_date,x.end_date).forEach(d=>out.push({date:d,start:'00:00',end:'23:59',label:'✈️ '+x.destination,notes:x.trip_type,type:'trip'})));return out}
async function conflict(date,start,end,ignoreId){const s=timeToMin(start),e=timeToMin(end);if(s==null)return null;const b=await blocks();return b.find(x=>x.date===date&&x.id!==ignoreId&&(x.type==='trip'||(()=>{const xs=timeToMin(x.start),xe=timeToMin(x.end);return xs!=null&&xe!=null&&s<xe&&e>xs})()));}
function normalizeTimes(root=document){root.querySelectorAll('input[type="time"]').forEach(i=>{if(i.dataset.nw24)return;i.dataset.nw24='1';i.type='text';i.inputMode='numeric';i.pattern='[0-2][0-9]:[0-5][0-9]';i.placeholder='HH:MM';i.maxLength=5;i.addEventListener('blur',()=>{let v=i.value.trim().replace('.',':');const m=v.match(/^(\d{1,2}):(\d{1,2})$/);if(m){const h=Math.min(23,+m[1]),mm=Math.min(59,+m[2]);i.value=String(h).padStart(2,'0')+':'+String(mm).padStart(2,'0')}})})}
function addSecretary(){if(document.querySelector('[data-secretary-card]'))return;const app=document.querySelector('#app');if(!app)return;const card=document.createElement('section');card.dataset.secretaryCard='1';card.className='secretary-card';card.innerHTML='<div class="secretary-head"><div><div class="eyebrow">SMART SECRETARY</div><h2>🧠 Η γραμματέας σου</h2><p>Βλέπει δεσμευμένο χρόνο από ραντεβού, follow-ups, εργασίες και ταξίδια.</p></div></div><div class="secretary-body">Φόρτωση προγράμματος…</div>';app.prepend(card);renderSecretary(card.querySelector('.secretary-body'))}
async function renderSecretary(el){const b=await blocks(),today=new Date().toISOString().slice(0,10),day=b.filter(x=>x.date===today).sort((a,c)=>(timeToMin(a.start)||0)-(timeToMin(c.start)||0));el.innerHTML=day.length?day.map(x=>`<div class="secretary-item"><b>${esc(x.start||'—')} ${esc(x.label)}</b><span>${esc(x.notes||'')}</span></div>`).join(''):'<div class="secretary-free">🟢 Σήμερα δεν υπάρχει καταχωρημένη δέσμευση χρόνου.</div>'}
document.addEventListener('submit',async e=>{const f=e.target;if(!f||!f.matches('form'))return;const date=f.querySelector('[name="appointment_date"],[name="date"],[name="follow_up_date"],[name="task_date"]')?.value;const start=f.querySelector('[name="start_time"],[name="follow_up_time"],[name="time"]')?.value;const end=f.querySelector('[name="end_time"]')?.value||start;if(!date||!start)return;const c=await conflict(date,start,end,f.querySelector('[name="id"]')?.value);if(c){e.preventDefault();e.stopImmediatePropagation();alert(`⚠️ Ο χρόνος είναι ήδη δεσμευμένος.\n\n${c.label}\n${c.date} ${c.start}${c.end&&c.end!==c.start?'–'+c.end:''}\n\nΔεν μπορεί να καταχωρηθεί δεύτερη εργασία/ραντεβού στον ίδιο χρόνο.`);return}},true);
document.addEventListener('click',e=>{if(e.target.closest('[data-view="dashboard"]'))setTimeout(()=>{normalizeTimes();addSecretary()},150)},true);new MutationObserver(()=>normalizeTimes()).observe(document.body,{childList:true,subtree:true});normalizeTimes();
window.NWSecretary={blocks,conflict,normalizeTimes};
})();