(()=>{
'use strict';
const URL='https://vbkuvexyqehmpeeejqbh.supabase.co';
const KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const sb=window.supabase?.createClient(URL,KEY); if(!sb)return;
const $=s=>document.querySelector(s);
const getUser=async()=> (await sb.auth.getSession()).data?.session?.user||null;
const time=v=>v?String(v).slice(0,5):'';
const ranks=['Ανεξάρτητος Συνεργάτης (Distributor)','Senior Consultant (Ανώτερος Σύμβουλος)','Success Builder (Δημιουργός Επιτυχίας)','Qualified Producer (Πιστοποιημένος Παραγωγός)','Supervisor (Επόπτης)','World Team (Παγκόσμια Ομάδα)','Active World Team (Ενεργή Παγκόσμια Ομάδα)','GET Team (Ομάδα Παγκόσμιας Επέκτασης)','Millionaire Team (Ομάδα Εκατομμυριούχων)','President\'s Team (Ομάδα Προέδρου)','Chairman\'s Club (Λέσχη Προέδρου)','Founder\'s Circle (Κύκλος Ιδρυτών)'];
async function repairLegacyPartners(){const u=await getUser();if(!u)return;const {data,error}=await sb.from('partners').select('*').eq('user_id',u.id);if(error)return;for(const r of data||[]){let j;try{j=JSON.parse(r.notes||'')}catch{continue}if(!j||typeof j!=='object'||Array.isArray(j))continue;await sb.from('partners').update({name:r.name||j.name||'',phone:r.phone||j.phone||'',email:r.email||j.email||'',id_number:r.id_number||j.partner_id_number||'',registration_date:r.registration_date||j.registration_date||null,current_rank:r.current_rank||j.tier||ranks[0],goals:r.goals||j.goal||'',actions:r.actions||[j.activity_1,j.activity_2,j.activity_3].filter(Boolean).join('\n'),notes:j.notes||''}).eq('id',r.id).eq('user_id',u.id)}}
function toast(msg){let x=document.getElementById('st118');if(!x){x=document.createElement('div');x.id='st118';x.style.cssText='position:fixed;bottom:18px;left:50%;transform:translateX(-50%);z-index:9999;background:#17351e;color:white;padding:12px 16px;border-radius:12px;box-shadow:0 8px 30px #0004;font-weight:700';document.body.appendChild(x)}x.textContent=msg;clearTimeout(x.t);x.t=setTimeout(()=>x.remove(),2800)}
async function savePartnerForm(f){const u=await getUser();if(!u)return toast('Συνδέσου πρώτα στον λογαριασμό σου.');const o=Object.fromEntries(new FormData(f));const row={user_id:u.id,name:String(o.name||'').trim(),id_number:String(o.id_number||'').trim(),registration_date:o.registration_date||null,current_rank:o.current_rank||ranks[0],goals:String(o.goals||'').trim(),actions:String(o.actions||'').trim(),phone:String(o.phone||'').trim(),email:String(o.email||'').trim(),notes:String(o.notes||'').trim()};if(!row.name)return toast('Βάλε ονοματεπώνυμο συνεργάτη.');const {error}=await sb.from('partners').insert(row);if(error)return toast('Δεν αποθηκεύτηκε: '+error.message);f.closest('.modal')?.remove();location.reload()}
async function eventAction(el,mode){const u=await getUser();if(!u)return;const b=el.querySelector('b');if(!b)return;const m=b.textContent.trim().match(/^(\d\d:\d\d)(?:–(\d\d:\d\d))? · (.*)$/);if(!m)return;const date=$('#calday')?.value;if(!date)return;const {data,error}=await sb.from('calendar_events').select('*').eq('user_id',u.id).eq('event_date',date).eq('start_time',m[1]+':00').limit(20);if(error||!data?.length)return toast('Δεν βρέθηκε το γεγονός.');const target=data.find(x=>x.title===m[3])||data[0];if(mode==='delete'){if(!confirm('Να διαγραφεί αυτό το γεγονός;'))return;const r=await sb.from('calendar_events').delete().eq('id',target.id).eq('user_id',u.id);if(r.error)return toast('Δεν διαγράφηκε: '+r.error.message);location.reload();return}const nt=prompt('Τίτλος:',target.title);if(nt===null)return;const ns=prompt('Ώρα έναρξης (HH:MM):',time(target.start_time));if(ns===null)return;const ne=prompt('Ώρα λήξης (HH:MM):',time(target.end_time));if(ne===null)return;if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(ns)||(ne&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(ne)))return toast('Η ώρα πρέπει να είναι HH:MM.');const r=await sb.from('calendar_events').update({title:nt.trim(),start_time:ns,end_time:ne||null}).eq('id',target.id).eq('user_id',u.id);if(r.error)return toast('Δεν έγινε η αλλαγή: '+r.error.message);location.reload()}
function addEventControls(){document.querySelectorAll('.event').forEach(el=>{if(el.querySelector('.st118-actions'))return;const box=document.createElement('span');box.className='st118-actions';box.style.cssText='display:flex;gap:5px;margin-left:auto';const e=document.createElement('button');e.type='button';e.textContent='✏️';e.title='Διόρθωση ώρας/τίτλου';const d=document.createElement('button');d.type='button';d.textContent='🗑️';d.title='Διαγραφή';box.append(e,d);el.append(box);e.onclick=()=>eventAction(el,'edit');d.onclick=()=>eventAction(el,'delete')})}
document.addEventListener('submit',e=>{const f=e.target;if(f?.id!=='f')return;if(f.querySelector('[name="id_number"]')&&f.querySelector('[name="current_rank"]')){e.preventDefault();e.stopImmediatePropagation();savePartnerForm(f)}},true);
const mo=new MutationObserver(()=>addEventControls());mo.observe(document.body,{childList:true,subtree:true});(async()=>{await repairLegacyPartners();addEventControls()})();
})();