(()=>{
'use strict';
const URL='https://vbkuvexyqehmpeeejqbh.supabase.co',KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const sb=window.supabase?.createClient(URL,KEY); if(!sb)return;
let sessionUser=null;
async function getUser(){const r=await sb.auth.getSession(); return r.data?.session?.user||null}
async function savePartner(form){
 const fd=new FormData(form), u=sessionUser||await getUser(); if(!u)return;
 let notes=String(fd.get('notes')||'').trim(), legacy={};
 try{ if(notes.startsWith('{')&&notes.endsWith('}')) legacy=JSON.parse(notes)||{} }catch{}
 const row={user_id:u.id,name:String(fd.get('name')||legacy.name||'').trim(),id_number:String(fd.get('id_number')||legacy.partner_id_number||'').trim(),registration_date:fd.get('registration_date')||legacy.registration_date||null,current_rank:String(fd.get('current_rank')||legacy.tier||'Ανεξάρτητος Συνεργάτης (Distributor)'),goals:String(fd.get('goals')||legacy.goal||'').trim(),actions:String(fd.get('actions')||legacy.activity_1||'').trim(),phone:String(fd.get('phone')||'').trim(),email:String(fd.get('email')||'').trim(),notes:(legacy.notes&&Object.keys(legacy).length>1)?String(legacy.notes||'').trim():notes};
 const {error}=await sb.from('partners').insert(row); if(error){alert('Δεν αποθηκεύτηκε ο συνεργάτης: '+error.message);return}
 document.querySelectorAll('.modal').forEach(x=>x.remove()); location.reload();
}
document.addEventListener('submit',async e=>{const f=e.target;if(f?.id!=='f')return;const h=f.querySelector('h2')?.textContent||'';if(!h.includes('Συνεργάτες'))return;e.preventDefault();e.stopImmediatePropagation();await savePartner(f)},true);
function addEventControls(){document.querySelectorAll('.event').forEach(el=>{if(el.querySelector('.st-edit'))return;const b=el.querySelector('b');if(!b)return;const txt=b.textContent.trim(),m=txt.match(/^(\d\d:\d\d)(?:–(\d\d:\d\d))? · (.*)$/);if(!m)return;const row=document.createElement('span');row.style.cssText='display:flex;gap:6px;margin-left:auto';const edit=document.createElement('button');edit.className='st-edit';edit.textContent='✏️';edit.title='Διόρθωση';const del=document.createElement('button');del.className='st-del';del.textContent='🗑️';del.title='Διαγραφή';row.append(edit,del);el.appendChild(row);
 edit.onclick=async()=>{const u=sessionUser||await getUser();if(!u)return;const start=prompt('Ώρα έναρξης (24ωρο HH:MM):',m[1]);if(start===null)return;const end=prompt('Ώρα λήξης (24ωρο HH:MM):',m[2]||'');if(end===null)return;const title=prompt('Τίτλος:',m[3]);if(title===null)return;const date=document.querySelector('#calday')?.value;if(!date)return;const {data:rows,error:qerr}=await sb.from('calendar_events').select('id,title,start_time').eq('user_id',u.id).eq('event_date',date).eq('start_time',m[1]+':00').limit(10);if(qerr||!rows?.length){alert('Δεν βρέθηκε το γεγονός για διόρθωση.');return}const target=rows.find(x=>x.title===m[3])||rows[0];const {error}=await sb.from('calendar_events').update({title:title.trim(),start_time:start,end_time:end||null}).eq('id',target.id).eq('user_id',u.id);if(error)alert('Δεν έγινε η αλλαγή: '+error.message);else location.reload()};
 del.onclick=async()=>{const u=sessionUser||await getUser();if(!u)return;if(!confirm('Να διαγραφεί αυτό το γεγονός;'))return;const date=document.querySelector('#calday')?.value;const {data:rows}=await sb.from('calendar_events').select('id,title,start_time').eq('user_id',u.id).eq('event_date',date).eq('start_time',m[1]+':00');const target=rows?.find(x=>x.title===m[3])||rows?.[0];if(!target)return alert('Δεν βρέθηκε το γεγονός.');const {error}=await sb.from('calendar_events').delete().eq('id',target.id).eq('user_id',u.id);if(error)alert('Δεν διαγράφηκε: '+error.message);else location.reload()};});}
async function migrateLegacyPartners(){const u=sessionUser||await getUser();if(!u)return;const {data:rows}=await sb.from('partners').select('id,notes,name,id_number,registration_date,current_rank,goals,actions,phone,email,rank_history').eq('user_id',u.id);for(const r of rows||[]){let j;try{j=JSON.parse(r.notes||'')}catch{continue}if(!j||typeof j!=='object')continue;const patch={name:r.name||j.name||'',id_number:r.id_number||j.partner_id_number||'',registration_date:r.registration_date||j.registration_date||null,current_rank:r.current_rank||j.tier||'Ανεξάρτητος Συνεργάτης (Distributor)',goals:r.goals||j.goal||'',actions:r.actions||j.activity_1||'',phone:r.phone||j.phone||'',email:r.email||j.email||'',notes:j.notes||'',rank_history:r.rank_history||[]};await sb.from('partners').update(patch).eq('id',r.id).eq('user_id',u.id)}}
async function init(){sessionUser=await getUser();if(!sessionUser)return;await migrateLegacyPartners();addEventControls();new MutationObserver(addEventControls).observe(document.body,{childList:true,subtree:true})}init();
})();