(()=>{
const U='https://vbkuvexyqehmpeeejqbh.supabase.co',K='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const db=window.supabase?.createClient?.(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});if(!db)return;
const map={clients:['clients',{name:'name',phone:'phone',email:'email',address:'address',birth_date:'birth_date',notes:'notes',status:'status'}],appointments:['appointments',{client_id:'client_id',title:'title',date:'appointment_date',start_time:'start_time',end_time:'end_time',type:'appointment_type',status:'status',notes:'notes',reminder_minutes:'reminder_minutes'}],partners:['partners',{name:'name',phone:'phone',email:'email',business:'business',notes:'notes',status:'status'}],measurements:['tanita_measurements',{client_id:'client_id',date:'measurement_date',weight:'weight',fat:'body_fat',muscle:'muscle_mass',water:'water_percent',bone:'bone_mass',visceral:'visceral_fat',calories:'calories',metabolic_age:'metabolic_age',fitness_score:'fitness_score',notes:'notes'}],programs:['programs',{client_id:'client_id',title:'title',start_date:'start_date',end_date:'end_date',calories:'calories',protein:'protein',description:'description',notes:'notes',status:'status'}],followups:['follow_ups',{client_id:'client_id',title:'title',date:'follow_up_date',time:'follow_up_time',status:'status',notes:'notes',reminder_minutes:'reminder_minutes'}],orders:['orders',{client_id:'client_id',date:'order_date',product:'product_name',quantity:'quantity',unit_price:'unit_price',total:'total_amount',status:'status',notes:'notes'}],finance:['finance_transactions',{type:'transaction_type',amount:'amount',date:'transaction_date',category:'category',description:'description',client_id:'client_id'}],tasks:['planner_tasks',{title:'title',description:'description',date:'task_date',start_time:'start_time',end_time:'end_time',completed:'completed',reminder_minutes:'reminder_minutes',priority:'priority'}],reminders:['reminders',{title:'title',date:'reminder_date',time:'reminder_time',reminder_minutes:'reminder_minutes',related_type:'related_type',related_id:'related_id',completed:'completed',notes:'notes'}],success:['daily_success',{date:'success_date',task:'task',completed:'completed',notes:'notes'}],documents:['documents',{title:'title',file_name:'file_name',file_path:'file_path',file_type:'file_type',file_size:'file_size',related_type:'related_type',related_id:'related_id'}}};
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const nums=new Set(['amount','quantity','unit_price','total','weight','fat','muscle','water','bone','visceral','calories','protein','metabolic_age','fitness_score','file_size','reminder_minutes']);
const toDb=(k,o,uid)=>{const r={id:o.id,user_id:uid};for(const [a,b] of Object.entries(map[k][1])){let v=o[a];if(a==='type')v=v==='Έσοδο'?'income':v==='Έξοδο'?'expense':v;if(a==='completed')v=!!v;if(nums.has(a)&&v!==''&&v!=null)v=Number(v);r[b]=v===''?null:v}return r};
let busy=false;async function sync113(){if(busy)return false;busy=true;try{const {data:s}=await db.auth.getSession();const u=s?.session?.user;if(!u)return false;const st=read('nwceo_final_v1',{});for(const k of Object.keys(map)){for(const o of st[k]||[]){const {error}=await db.from(map[k][0]).upsert(toDb(k,o,u.id),{onConflict:'id'});if(error)throw error}}write('nwceo_sync_last_push',new Date().toISOString());return true}catch(e){console.warn('sync-v113',e);return false}finally{busy=false}}
window.nwceoSyncV113=sync113;window.addEventListener('online',sync113);window.addEventListener('focus',sync113);setTimeout(sync113,1200);setInterval(sync113,3000);
})();
