(()=>{
const U='https://vbkuvexyqehmpeeejqbh.supabase.co',K='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const db=window.supabase?.createClient?.(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});if(!db)return;
const SK='nwceo_final_v1',PK='nwceo_pending_final',SS='nwceo_cloud_snapshot_v112';
const cfg={clients:['clients',{name:'name',phone:'phone',email:'email',address:'address',birth_date:'birth_date',notes:'notes',status:'status'}],appointments:['appointments',{client_id:'client_id',title:'title',date:'appointment_date',start_time:'start_time',end_time:'end_time',type:'appointment_type',status:'status',notes:'notes',reminder_minutes:'reminder_minutes'}],partners:['partners',{name:'name',phone:'phone',email:'email',business:'business',notes:'notes',status:'status'}],measurements:['tanita_measurements',{client_id:'client_id',date:'measurement_date',weight:'weight',fat:'body_fat',muscle:'muscle_mass',water:'water_percent',bone:'bone_mass',visceral:'visceral_fat',calories:'calories',metabolic_age:'metabolic_age',fitness_score:'fitness_score',notes:'notes'}],programs:['programs',{client_id:'client_id',title:'title',start_date:'start_date',end_date:'end_date',calories:'calories',protein:'protein',description:'description',notes:'notes',status:'status'}],followups:['follow_ups',{client_id:'client_id',title:'title',date:'follow_up_date',time:'follow_up_time',status:'status',notes:'notes',reminder_minutes:'reminder_minutes'}],orders:['orders',{client_id:'client_id',date:'order_date',product:'product_name',quantity:'quantity',unit_price:'unit_price',total:'total_amount',status:'status',notes:'notes'}],finance:['finance_transactions',{type:'transaction_type',amount:'amount',date:'transaction_date',category:'category',description:'description',client_id:'client_id'}],tasks:['planner_tasks',{title:'title',description:'description',date:'task_date',start_time:'start_time',end_time:'end_time',completed:'completed',reminder_minutes:'reminder_minutes',priority:'priority'}],reminders:['reminders',{title:'title',date:'reminder_date',time:'reminder_time',reminder_minutes:'reminder_minutes',related_type:'related_type',related_id:'related_id',completed:'completed',notes:'notes'}],success:['daily_success',{date:'success_date',task:'task',completed:'completed',notes:'notes'}],documents:['documents',{title:'title',file_name:'file_name',file_path:'file_path',file_type:'file_type',file_size:'file_size',related_type:'related_type',related_id:'related_id'}]};
const num=new Set(['amount','quantity','unit_price','total','weight','fat','muscle','water','bone','visceral','calories','protein','metabolic_age','fitness_score','file_size','reminder_minutes']);
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const status=(t,c)=>{const e=document.querySelector('.sync-badge');if(e){e.className='sync-badge '+c;e.textContent=t}};
const toDb=(k,o,uid)=>{const r={id:o.id,user_id:uid},m=cfg[k][1];for(const [a,b] of Object.entries(m)){let v=o[a];if(a==='type')v=v==='Έσοδο'?'income':v==='Έξοδο'?'expense':v;if(num.has(a)&&v!==''&&v!=null)v=Number(v);if(a==='completed')v=!!v;r[b]=v===''?null:v}return r};
const fromDb=(k,r)=>{const o={id:r.id},m=cfg[k][1];for(const [a,b] of Object.entries(m)){let v=r[b];if(a==='type')v=v==='income'?'Έσοδο':v==='expense'?'Έξοδο':v;o[a]=v}return o};
let busy=false;
async function sync(){if(busy)return false;busy=true;status('↻ Συγχρονισμός…','sync');try{const {data:s,error:se}=await db.auth.getSession();if(se||!s?.session?.user){status('🔐 Απαιτείται σύνδεση','offline');return false}const uid=s.session.user.id;let pending=read(PK,[]),failed=[];for(const op of pending){try{const k=op.k;if(!cfg[k])continue;if(op.type==='upsert'){const {error}=await db.from(cfg[k][0]).upsert(toDb(k,op.data,uid),{onConflict:'id'});if(error)throw error}else{const {error}=await db.from(cfg[k][0]).delete().eq('id',op.id).eq('user_id',uid);if(error)throw error}}catch(e){failed.push(op)}}write(PK,failed);
const local=read(SK,{}),old=read(SS,null),cloud={};for(const k of Object.keys(cfg)){const q=await db.from(cfg[k][0]).select('*').eq('user_id',uid).order('created_at',{ascending:false});if(q.error)throw q.error;cloud[k]=(q.data||[]).map(r=>fromDb(k,r));}
// Push local records that exist locally but are missing from cloud (covers records created before the queue was fixed).
for(const k of Object.keys(cfg)){const cm=new Map((cloud[k]||[]).map(x=>[x.id,x]));for(const x of local[k]||[]){if(!cm.has(x.id)){const q=await db.from(cfg[k][0]).upsert(toDb(k,x,uid),{onConflict:'id'});if(q.error)throw q.error;}}}
const final={};for(const k of Object.keys(cfg)){const q=await db.from(cfg[k][0]).select('*').eq('user_id',uid).order('created_at',{ascending:false});if(q.error)throw q.error;final[k]=(q.data||[]).map(r=>fromDb(k,r));}
write(SK,final);write(SS,final);status(failed.length?'⚠️ Μερικός συγχρονισμός':'☁️ Συγχρονισμένο',failed.length?'sync':'ok');if(typeof window.render==='function')window.render();return !failed.length}catch(e){console.warn('sync-v112',e);status('⚠️ Δεν ολοκληρώθηκε ο συγχρονισμός','offline');return false}finally{busy=false}}
window.sync=sync;window.nwceoSyncV112=sync;
db.auth.onAuthStateChange(()=>setTimeout(sync,250));window.addEventListener('online',()=>sync());window.addEventListener('focus',()=>sync());setTimeout(sync,500);setInterval(()=>{if(document.visibilityState!=='hidden')sync()},5000);
})();
