(()=>{
'use strict';
if(window.__NWCEO_TANITA214)return;window.__NWCEO_TANITA214=1;
const URL='https://vbkuvexyqehmpeeejqbh.supabase.co',KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCxH_Gk';
const sb=window.__NWCEO_DB||window.supabase?.createClient(URL,KEY);if(!sb)return;
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const cid=()=>location.hash.startsWith('#client/')?decodeURIComponent(location.hash.slice(8).split('/')[0]):'';
const active=()=>location.hash.startsWith('#client/')&&decodeURIComponent(location.hash.slice(8).split('/')[1]||'')==='tanita';
const today=()=>new Date().toISOString().slice(0,10);
const nowTime=()=>new Date().toTimeString().slice(0,5);
const time=v=>String(v||'').slice(0,5);
const F=[['weight','Βάρος','kg'],['body_fat','Σωματικό λίπος','%'],['muscle_mass','Μυϊκή μάζα','kg'],['water_percent','Νερό','%'],['visceral_fat','Σπλαχνικό λίπος',''],['metabolic_age','Μεταβολική ηλικία',''],['bone_mass','Οστική μάζα','kg'],['calories','Θερμίδες','kcal'],['fitness_score','Fitness Score','']];
const css=document.createElement('style');css.textContent=`
.nw214-modal{position:fixed;inset:0;z-index:2000000;background:#0008;display:grid;place-items:center;padding:14px}
.nw214-box{width:min(760px,96vw);max-height:94vh;overflow:auto;background:#fff;border-radius:20px;padding:18px;box-shadow:0 22px 80px #0008}
.nw214-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.nw214-head h2{margin:0;color:#245b2b}
.nw214-form{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.nw214-field{display:flex;flex-direction:column;gap:5px;font-weight:800;color:#344054}.nw214-full{grid-column:1/-1}
.nw214-field input,.nw214-field textarea{width:100%;box-sizing:border-box;padding:11px;border:1px solid #cbd5cb;border-radius:10px;font:inherit;color:#182018;background:#fff;pointer-events:auto;user-select:text;caret-color:#245b2b}.nw214-field textarea{min-height:90px}
.nw214-name{font-size:16px;min-height:46px}.nw214-hint{font-size:11px;color:#667085;font-weight:500}.nw214-actions{grid-column:1/-1;display:flex;justify-content:flex-end;gap:8px}.nw214-btn{border:1px solid #d5ddd5;background:#fff;border-radius:10px;padding:10px 13px;font:inherit;font-weight:800;color:#245b2b;cursor:pointer}.nw214-primary{background:#245b2b;color:#fff;border-color:#245b2b}.nw214-error{grid-column:1/-1;background:#fff3f3;border:1px solid #eccaca;color:#a40000;padding:10px;border-radius:10px;font-weight:700}
.nw214-next{margin:12px 0;background:linear-gradient(135deg,#f7fbf7,#fffdf8);border:1px solid #dfe8df;border-radius:14px;padding:12px;display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.nw214-next b{color:#245b2b}.nw214-next span{color:#667085;font-size:12px}
@media(max-width:700px){.nw214-form{grid-template-columns:1fr}.nw214-full,.nw214-actions,.nw214-error{grid-column:1}}
`;
document.head.appendChild(css);
async function user(){return (await sb.auth.getUser()).data?.user||null}
async function clients(){const u=await user();if(!u)return[];const r=await sb.from('clients').select('id,name').eq('user_id',u.id).order('name');return r.data||[]}
async function currentClient(){const u=await user();if(!u||!cid())return null;const r=await sb.from('clients').select('id,name,next_measurement_date').eq('id',cid()).eq('user_id',u.id).maybeSingle();return r.data||null}
function resolveClient(name,list,current){const q=String(name||'').trim().toLowerCase();if(!q)return current?.id||null;const exact=list.filter(x=>String(x.name||'').trim().toLowerCase()===q);if(exact.length===1)return exact[0].id;const partial=list.filter(x=>String(x.name||'').toLowerCase().includes(q));return partial.length===1?partial[0].id:null}
function modal(existing,current,list){const m=document.createElement('div');m.className='nw214-modal';const opts=list.map(x=>`<option value="${esc(x.name)}"></option>`).join('');m.innerHTML=`<div class="nw214-box"><div class="nw214-head"><h2>${existing?'✏️ Επεξεργασία Tanita':'⚖️ Νέα μέτρηση Tanita'}</h2><button class="nw214-btn" type="button" data-close>×</button></div><form class="nw214-form"><label class="nw214-field nw214-full">Όνομα πελάτη *<input class="nw214-name" name="client_name" type="text" value="${esc(existing?.client_name||current?.name||'')}" autocomplete="off" autocapitalize="words" spellcheck="false" list="nw214-client-list"><datalist id="nw214-client-list">${opts}</datalist><span class="nw214-hint">Γράψε κανονικά το όνομα. Μπορείς να επιλέξεις και από τη λίστα.</span></label><label class="nw214-field">Ημερομηνία μέτρησης *<input name="measurement_date" type="date" value="${esc(existing?.measurement_date||today())}"></label><label class="nw214-field">Ώρα μέτρησης<input name="measurement_time" type="text" inputmode="numeric" placeholder="HH:MM" maxlength="5" value="${esc(time(existing?.measurement_time)||nowTime())}"><span class="nw214-hint">24ωρη μορφή, π.χ. 14:05</span></label>${F.map(([k,l,u])=>`<label class="nw214-field">${l}${u?' ('+u+')':''}<input name="${k}" type="number" step="any" value="${esc(existing?.[k]??'')}"></label>`).join('')}<label class="nw214-field nw214-full">Σημειώσεις<textarea name="notes">${esc(existing?.notes||'')}</textarea></label><div class="nw214-actions"><button class="nw214-btn" type="button" data-close>Άκυρο</button><button class="nw214-btn nw214-primary" type="submit">Αποθήκευση</button></div></form></div>`;
document.body.appendChild(m);m.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>m.remove());
const name=m.querySelector('[name=client_name]');name.readOnly=false;name.disabled=false;name.tabIndex=0;name.style.pointerEvents='auto';name.addEventListener('keydown',e=>e.stopPropagation());setTimeout(()=>{name.focus({preventScroll:true});name.setSelectionRange(name.value.length,name.value.length)},80);
const ti=m.querySelector('[name=measurement_time]');ti.oninput=e=>{let v=e.target.value.replace(/\D/g,'').slice(0,4);if(v.length>2)v=v.slice(0,2)+':'+v.slice(2);e.target.value=v};
m.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,u=await user();if(!u)return;const client_id=resolveClient(f.client_name.value,list,current);const errs=[];if(!client_id)errs.push('Δεν βρέθηκε μοναδικός πελάτης με αυτό το όνομα. Διάλεξε το όνομα από τη λίστα ή γράψε ακριβώς το όνομα.');if(f.measurement_time.value&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(f.measurement_time.value))errs.push('Η ώρα πρέπει να είναι HH:MM.');if(errs.length){m.querySelector('.nw214-error')?.remove();f.insertAdjacentHTML('afterbegin',`<div class="nw214-error">${errs.map(esc).join('<br>')}</div>`);return}const p={user_id:u.id,client_id,measurement_date:f.measurement_date.value||today(),measurement_time:f.measurement_time.value||nowTime(),notes:f.notes.value||null};F.forEach(([k])=>p[k]=f[k].value===''?null:Number(f[k].value));const r=existing?await sb.from('tanita_measurements').update(p).eq('id',existing.id).eq('user_id',u.id):await sb.from('tanita_measurements').insert(p);if(r.error){m.querySelector('.nw214-error')?.remove();f.insertAdjacentHTML('afterbegin',`<div class="nw214-error">Δεν αποθηκεύτηκε: ${esc(r.error.message)}</div>`);return}m.remove();location.hash=location.hash;setTimeout(()=>location.reload(),80)};
}
async function patchNewButton(){if(!active())return;const btn=document.querySelector('.nw213 .newbtn');if(!btn||btn.dataset.nw214)return;btn.dataset.nw214='1';const clone=btn.cloneNode(true);clone.dataset.nw214='1';btn.replaceWith(clone);clone.onclick=async e=>{e.preventDefault();e.stopImmediatePropagation();const [c,list]=await Promise.all([currentClient(),clients()]);modal(null,c,list)};}
async function patchNext(){if(!location.hash.startsWith('#client/')||decodeURIComponent(location.hash.slice(8).split('/')[1]||'')==='tanita')return;const host=document.querySelector('#nw210');if(!host)return;const c=await currentClient();if(!c)return;let box=host.querySelector('.nw214-next');if(!box){box=document.createElement('section');box.className='nw214-next';const first=host.querySelector('.hero');if(first)first.after(box);else host.prepend(box)}box.innerHTML=`<div><b>📅 Επόμενη μέτρηση Tanita</b><br><span>${c.next_measurement_date?new Date(c.next_measurement_date+'T00:00:00').toLocaleDateString('el-GR'):'Δεν έχει οριστεί ημερομηνία'}</span></div><button type="button" class="nw214-btn nw214-primary">${c.next_measurement_date?'Αλλαγή ημερομηνίας':'Ορισμός ημερομηνίας'}</button>`;box.querySelector('button').onclick=async()=>{const d=prompt('Ποια είναι η επόμενη ημερομηνία μέτρησης; (YYYY-MM-DD)',c.next_measurement_date||'');if(d===null)return;if(d&&!/^\d{4}-\d{2}-\d{2}$/.test(d)){alert('Γράψε ημερομηνία σε μορφή YYYY-MM-DD.');return}const u=await user();const r=await sb.from('clients').update({next_measurement_date:d||null}).eq('id',c.id).eq('user_id',u.id);if(r.error){alert('Δεν αποθηκεύτηκε: '+r.error.message);return}patchNext()}}
function scan(){patchNewButton();patchNext()}
const obs=new MutationObserver(()=>scan());obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(scan,150));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(scan,400));else setTimeout(scan,400);
})();
