(()=>{
'use strict';
if(window.__NWCEO_TANITA212)return;window.__NWCEO_TANITA212=1;
const sb=window.__NWCEO_DB;if(!sb)return;
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const id=()=>location.hash.startsWith('#client/')?decodeURIComponent(location.hash.slice(8).split('/')[0]):'';
const active=()=>location.hash.startsWith('#client/')&&decodeURIComponent(location.hash.slice(8).split('/')[1]||'home')==='tanita';
const fmt=v=>v==null||v===''?'—':Number(v).toLocaleString('el-GR',{maximumFractionDigits:1});
const date=v=>v?new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString('el-GR'):'—';
const css=document.createElement('style');css.textContent=`.nw212{margin-top:14px;background:linear-gradient(135deg,#fbfdfb,#fffdf8);border:1px solid #dfe8df;border-radius:18px;padding:15px;box-shadow:0 7px 24px #173b1910}.nw212 h2{margin:0;color:#245b2b}.nw212 .sub{color:#667085;font-size:12px;margin-top:3px}.nw212 .latest{display:grid;grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:9px;margin-top:12px}.nw212 .metric{background:#fff;border:1px solid #e2e8e2;border-radius:12px;padding:10px}.nw212 .metric b{display:block;color:#245b2b;font-size:20px}.nw212 .metric span{font-size:11px;color:#667085}.nw212 .compare{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:9px;margin-top:12px}.nw212 .cmp{background:#f7faf7;border:1px solid #e1e8e1;border-radius:12px;padding:10px}.nw212 .cmp b{color:#245b2b}.nw212 .delta{font-weight:900}.nw212 .chartgrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.nw212 .chart{background:#fff;border:1px solid #e2e8e2;border-radius:14px;padding:10px}.nw212 .chart h3{margin:0 0 6px;color:#245b2b;font-size:15px}.nw212 svg{width:100%;height:170px;display:block}.nw212 .axis{font-size:10px;fill:#667085}.nw212 .empty{padding:14px;border:1px dashed #cbd7cb;border-radius:12px;color:#667085;text-align:center;margin-top:12px}.nw212 .history{margin-top:14px;overflow:auto}.nw212 table{width:100%;border-collapse:collapse;font-size:12px;background:#fff;border:1px solid #e2e8e2}.nw212 th,.nw212 td{padding:8px;border-bottom:1px solid #edf1ed;text-align:left;white-space:nowrap}.nw212 th{color:#245b2b;background:#f4f8f4}.nw212 tr:last-child td{border-bottom:0}@media(max-width:700px){.nw212 .chartgrid{grid-template-columns:1fr}}`;
document.head.appendChild(css);
async function user(){return (await sb.auth.getUser()).data?.user||null}
async function rows(){const u=await user();if(!u)return[];const r=await sb.from('tanita_measurements').select('*').eq('user_id',u.id).eq('client_id',id()).order('measurement_date',{ascending:true});return r.error?[]:(r.data||[])}
function chart(title,key,data){const vals=data.map(x=>Number(x[key])).filter(Number.isFinite);if(!vals.length)return `<div class="chart"><h3>${title}</h3><div class="empty">Δεν υπάρχουν δεδομένα για γράφημα.</div></div>`;const w=520,h=170,p=28,min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;const pts=data.map((x,i)=>{const v=Number(x[key]);if(!Number.isFinite(v))return null;const xx=p+(i*Math.max(1,w-2*p))/Math.max(1,data.length-1);const yy=h-p-((v-min)/range)*(h-2*p);return [xx,yy,v]}).filter(Boolean);const path=pts.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)).join(' ');const dots=pts.map(q=>`<circle cx="${q[0]}" cy="${q[1]}" r="3.5" fill="#245b2b"><title>${fmt(q[2])}</title></circle>`).join('');return `<div class="chart"><h3>${title}</h3><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="#d9e2d9"/><line x1="${p}" y1="${p}" x2="${p}" y2="${h-p}" stroke="#d9e2d9"/><path d="${path}" fill="none" stroke="#245b2b" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${dots}<text x="${p}" y="${h-7}" class="axis">${date(data[0]?.measurement_date)}</text><text x="${w-p}" y="${h-7}" text-anchor="end" class="axis">${date(data[data.length-1]?.measurement_date)}</text><text x="${p+4}" y="${p+10}" class="axis">${fmt(max)}</text><text x="${p+4}" y="${h-p-4}" class="axis">${fmt(min)}</text></svg></div>`}
async function render(){if(!active())return;const root=document.querySelector('main#app > div');if(!root)return;root.querySelector('.nw212')?.remove();const data=await rows();const hero=root.querySelector('.hero');if(!hero)return;const box=document.createElement('section');box.className='nw212';if(!data.length){box.innerHTML='<h2>📊 Tanita — Ιστορικό & γραφήματα</h2><div class="sub">Δεν υπάρχει ακόμη μέτρηση για αυτόν τον πελάτη.</div><div class="empty">Πρόσθεσε την πρώτη μέτρηση από «＋ Νέα καταχώρηση».</div>';hero.after(box);return}const latest=data[data.length-1],prev=data.length>1?data[data.length-2]:null;const delta=k=>{if(!prev||latest[k]==null||prev[k]==null)return '—';const d=Number(latest[k])-Number(prev[k]);return `${d>0?'+':''}${fmt(d)}`};box.innerHTML=`<h2>📊 Tanita — Ιστορικό & γραφήματα</h2><div class="sub">Τελευταία μέτρηση: ${date(latest.measurement_date)} · Σύνολο: ${data.length}</div><div class="latest"><div class="metric"><b>${fmt(latest.weight)} kg</b><span>Βάρος</span></div><div class="metric"><b>${fmt(latest.body_fat)}%</b><span>Σωματικό λίπος</span></div><div class="metric"><b>${fmt(latest.muscle_mass)} kg</b><span>Μυϊκή μάζα</span></div><div class="metric"><b>${fmt(latest.water_percent)}%</b><span>Νερό</span></div><div class="metric"><b>${fmt(latest.visceral_fat)}</b><span>Σπλαχνικό λίπος</span></div><div class="metric"><b>${fmt(latest.metabolic_age)}</b><span>Μεταβολική ηλικία</span></div></div>${prev?`<div class="compare"><div class="cmp"><b>Από προηγούμενη μέτρηση</b><div>Βάρος: <span class="delta">${delta('weight')} kg</span></div></div><div class="cmp"><b>Λίπος</b><div><span class="delta">${delta('body_fat')}%</span></div></div><div class="cmp"><b>Μύες</b><div><span class="delta">${delta('muscle_mass')} kg</span></div></div><div class="cmp"><b>Νερό</b><div><span class="delta">${delta('water_percent')}%</span></div></div></div>`:''}<div class="chartgrid">${chart('Βάρος (kg)','weight',data)}${chart('Σωματικό λίπος (%)','body_fat',data)}${chart('Μυϊκή μάζα (kg)','muscle_mass',data)}${chart('Νερό (%)','water_percent',data)}</div><div class="history"><table><thead><tr><th>Ημερομηνία</th><th>Βάρος</th><th>Λίπος</th><th>Μύες</th><th>Νερό</th><th>Σπλαχνικό</th><th>Μεταβ. ηλικία</th></tr></thead><tbody>${data.slice().reverse().map(x=>`<tr><td>${date(x.measurement_date)}</td><td>${fmt(x.weight)}</td><td>${fmt(x.body_fat)}%</td><td>${fmt(x.muscle_mass)}</td><td>${fmt(x.water_percent)}%</td><td>${fmt(x.visceral_fat)}</td><td>${fmt(x.metabolic_age)}</td></tr>`).join('')}</tbody></table></div>`;hero.after(box)}
function boot(){if(!active())return;setTimeout(render,1500);setTimeout(render,2100)}
window.addEventListener('hashchange',boot);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
