(()=>{
const URL='https://vbkuvexyqehmpeeejqbh.supabase.co',KEY='sb_publishable__nczNPWr3do_hqi6MCS0AQ_fjYCXhGk';
const db=window.__nw_db||window.supabase?.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}}); if(!db)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const TYPES=['Εταιρικό / Κερδισμένο','Extravaganza','Εκπαιδευτικό','Επαγγελματικό','Προσωπικό','Άλλο'];
const localKey='nwceo_trips_v1';
const getLocal=()=>{try{return JSON.parse(localStorage.getItem(localKey)||'[]')}catch(e){return[]}};
const setLocal=x=>{try{localStorage.setItem(localKey,JSON.stringify(x))}catch(e){}};
const user=async()=>{try{return (await db.auth.getSession()).data.session?.user||null}catch(e){return null}};
const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString('el-GR',{day:'2-digit',month:'2-digit',year:'numeric'}):'';
const isBlocked=(t,date)=>date>=t.start_date&&date<=t.end_date;
async function load(){const u=await user(); if(!u)return getLocal(); const {data,error}=await db.from('trips').select('*').eq('user_id',u.id).order('start_date'); if(error)return getLocal(); setLocal(data||[]); return data||[]}
async function save(t){const u=await user(); const row={...t,user_id:u?.id}; if(u){const {data,error}=await db.from('trips').upsert(row,{onConflict:'id'}).select().single(); if(!error){const a=getLocal().filter(x=>x.id!==t.id);setLocal([...a,data]);return data}} const a=getLocal().filter(x=>x.id!==t.id);setLocal([...a,t]);return t}
async function del(id){const u=await user();if(u)await db.from('trips').delete().eq('id',id);setLocal(getLocal().filter(x=>x.id!==id));}
function addNav(){if(document.querySelector('[data-view="trips"]'))return;const n=document.querySelector('#nav');if(!n)return;const b=document.createElement('button');b.type='button';b.dataset.view='trips';b.textContent='✈️ Ταξίδια';n.appendChild(b)}
function page(items){return `<div class="page-head"><div><h1>✈️ Ταξίδια</h1><p>Τα ταξίδια δεσμεύουν αυτόματα τις ημέρες σου από κάθε άλλη εργασία ή ραντεβού.</p></div><button class="primary big" data-trip-new>＋ Νέο ταξίδι</button></div><div class="data-list">${items.length?items.map(t=>`<article class="data-card"><div class="avatar">✈️</div><div class="card-main"><strong>${esc(t.destination)}</strong><span>${fmt(t.start_date)} – ${fmt(t.end_date)} · ${esc(t.trip_type)} · ${t.duration_days} ημέρες</span><span>${t.company_trip?'🏢 Εταιρεία':''} ${t.earned_trip?'🏆 Κερδισμένο':''} ${t.extravaganza?'✨ Extravaganza':''} ${t.educational?'🎓 Εκπαιδευτικό':''}</span>${t.notes?`<span>📝 ${esc(t.notes)}</span>`:''}</div><div class="card-actions"><button class="icon-btn" data-trip-edit="${esc(t.id)}">✏️</button><button class="icon-btn danger" data-trip-delete="${esc(t.id)}">🗑️</button></div></article>`).join(''):`<div class="empty-state"><div>✈️</div><strong>Δεν έχεις καταχωρήσει ταξίδια</strong><span>Πρόσθεσε το επόμενο ταξίδι σου και οι ημέρες του θα μπλοκαριστούν αυτόματα στο πρόγραμμα.</span></div>`}</div><div class="section-title"><h2>🧠 Διαθεσιμότητα</h2></div><div class="data-card"><div class="avatar">☁️</div><div class="card-main"><strong>Έξυπνος αποκλεισμός χρόνου</strong><span>Οι ημέρες ενός ταξιδιού θεωρούνται μη διαθέσιμες για ραντεβού, follow-ups, παρουσιάσεις, εκπαιδεύσεις και εργασίες.</span></div></div>`}
function modal(t={}){const id=t.id||crypto.randomUUID();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="trip-modal"><div class="modal-card form-card"><button class="x" data-trip-close>×</button><div class="form-head"><div class="logo-mark">✈️</div><div><h2>${t.id?'Επεξεργασία ταξιδιού':'Νέο ταξίδι'}</h2><p>Οι ημερομηνίες δεσμεύουν αυτόματα το πρόγραμμά σου.</p></div></div><form id="trip-form"><input type="hidden" name="id" value="${esc(id)}"><div class="form-grid"><label>Ημερομηνία έναρξης<input name="start_date" type="date" required value="${esc(t.start_date)}"></label><label>Ημερομηνία επιστροφής<input name="end_date" type="date" required value="${esc(t.end_date)}"></label><label>Προορισμός<input name="destination" required value="${esc(t.destination)}" placeholder="π.χ. Αθήνα"></label><label>Διάρκεια (ημέρες)<input name="duration_days" type="number" min="1" value="${esc(t.duration_days||1)}"></label><label>Τύπος ταξιδιού<select name="trip_type">${TYPES.map(x=>`<option ${x===(t.trip_type||'Επαγγελματικό')?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Άλλος χαρακτηρισμός<input name="custom_type" value="${esc(t.custom_type)}" placeholder="προαιρετικό"></label><label><input name="company_trip" type="checkbox" ${t.company_trip?'checked':''}> 🏢 Από την εταιρεία</label><label><input name="earned_trip" type="checkbox" ${t.earned_trip?'checked':''}> 🏆 Κερδισμένο</label><label><input name="extravaganza" type="checkbox" ${t.extravaganza?'checked':''}> ✨ Extravaganza</label><label><input name="educational" type="checkbox" ${t.educational?'checked':''}> 🎓 Εκπαιδευτικό</label><label class="wide">Σημειώσεις<textarea name="notes" placeholder="Πληροφορίες, πρόγραμμα, ξενοδοχείο, πτήση, τι χρειάζεται να θυμάμαι...">${esc(t.notes)}</textarea></label></div><div class="modal-actions"><button type="button" data-trip-close>Ακύρωση</button><button class="primary" type="submit">Αποθήκευση ταξιδιού</button></div></form></div></div>`)}
async function render(){const main=document.querySelector('#app');if(!main)return;const items=await load();main.innerHTML=page(items)}
async function open(){addNav();await render()}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view="trips"]');if(nav){e.preventDefault();e.stopImmediatePropagation();await open();return}if(e.target.closest('[data-trip-new]'))modal();if(e.target.closest('[data-trip-close]'))document.querySelector('#trip-modal')?.remove();const ed=e.target.closest('[data-trip-edit]');if(ed){const a=await load();const t=a.find(x=>x.id===ed.dataset.tripEdit);if(t)modal(t)}const de=e.target.closest('[data-trip-delete]');if(de&&confirm('Να διαγραφεί το ταξίδι;')){await del(de.dataset.tripDelete);await render()}} ,true);
document.addEventListener('submit',async e=>{if(e.target.id!=='trip-form')return;e.preventDefault();const f=e.target,fd=new FormData(f),t={id:fd.get('id'),start_date:fd.get('start_date'),end_date:fd.get('end_date'),destination:fd.get('destination'),duration_days:Number(fd.get('duration_days')||1),trip_type:fd.get('trip_type'),custom_type:fd.get('custom_type')||'',company_trip:fd.has('company_trip'),earned_trip:fd.has('earned_trip'),extravaganza:fd.has('extravaganza'),educational:fd.has('educational'),notes:fd.get('notes')||''};if(t.end_date<t.start_date){alert('Η ημερομηνία επιστροφής δεν μπορεί να είναι πριν από την έναρξη.');return}await save(t);f.closest('.modal')?.remove();await render()},true);
window.NWTrips={load,isBlocked,async getBlockedDates(){const a=await load(),s=new Set();a.forEach(t=>{let d=new Date(t.start_date+'T00:00:00'),end=new Date(t.end_date+'T00:00:00');while(d<=end){s.add(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}});return s}};
addNav();
})();